In [1]:
summary_all = {}

hotels_sweep = [542., 543., 545., 546., 547., 548., 549., 550., 551., 552., 554., 555., 643., 956., 957., 960.]

for hotel_sel in hotels_sweep:

    %run nb0_arr_analysis.ipynb
    
    summary_all[hotel_sel] = summary_df

/usr/local/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 542.0

reservations_df shape: (92634, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-10-10,breakfast board,deluxe carmel&se,4.0,1402.0,t.a.,home site,,,,can,0.0,1.0,2.0,252.0,2.0,0.0,0.0,0.0,1273.85
2018-10-30,breakfast board,deluxe bay view,4.0,2837.0,t.a.,home site,,,,usa,0.0,1.0,2.0,267.0,2.0,0.0,0.0,0.0,1298.88
2018-10-30,breakfast board,deluxe bay view,4.0,2837.0,t.a.,home site,,,,usa,0.0,1.0,2.0,267.0,2.0,0.0,0.0,0.0,1298.88
2018-10-12,breakfast board,deluxe carmel&se,4.0,12845.0,web,home site,silver,,,irl,0.0,3.0,1.0,244.0,1.0,0.0,0.0,0.0,1186.80
2018-10-11,breakfast board,deluxe carmel&se,4.0,12845.0,web,home site,silver,,,irl,0.0,3.0,1.0,244.0,1.0,0.0,0.0,0.0,1186.80

<class 'pandas.core.frame.DataFrame'>
Index: 92634 entries, 2018-10-10 to 2019-04-05
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   plan_desc             92634 non-null  object
 1   RoomTypes_desc        92634 non-null  object
 2   market_segment_bi_id  92634 non-null  float64
 3   MainCust              92634 non-null  float64
 4   source                92634 non-null  object
 5   sales_channel         92634 non-null  object
 6   club_code             92634 non-null  object
 7   StatisticSource       92634 non-null  object
 8   package_code          92634 non-null  object
 9   nationality           92634 non-null  object
 10  group_member          92634 non-null  float64
 11  m_length_of_stay      92634 non-null  float64
 12  bed_nights            92634 non-null  float64
 13  m_lead_days           92634 non-null  float64
 14  adults                92634 non-null  float64
 15  juniors               92634 non-null  float64
 16  children              92634 non-null  float64
 17  babies                92634 non-null  float64
 18  ARR                   92634 non-null  float64
dtypes: float64(11), object(8)
memory usage: 14.1+ MB
(92634, 200)

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-10-10,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,4.0,1402.0,0.0,1.0,2.0,252.0,2.0,0.0,0.0,0.0
2018-10-30,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,2837.0,0.0,1.0,2.0,267.0,2.0,0.0,0.0,0.0
2018-10-30,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,2837.0,0.0,1.0,2.0,267.0,2.0,0.0,0.0,0.0
2018-10-12,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,4.0,12845.0,0.0,3.0,1.0,244.0,1.0,0.0,0.0,0.0
2018-10-11,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,4.0,12845.0,0.0,3.0,1.0,244.0,1.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000,...,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000,92634.000000
mean,0.559935,0.000086,0.002343,0.068053,0.369497,0.000054,0.000032,0.000032,0.087927,0.763683,...,25.668178,8624.376892,0.471328,3.824071,1.589071,55.595408,1.421346,0.000086,0.167638,0.040978
std,0.496398,0.009293,0.048343,0.251838,0.482671,0.007347,0.005691,0.005691,0.283190,0.424821,...,15.162372,2922.944945,0.499180,4.639945,0.757587,70.092222,0.553092,0.013142,0.528359,0.209159
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,186.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,13.000000,7677.000000,0.000000,2.000000,1.000000,9.000000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,20.000000,9313.000000,0.000000,2.000000,1.000000,24.000000,1.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,40.000000,10224.000000,1.000000,4.000000,2.000000,75.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13165.000000,1.000000,55.000000,4.000000,299.000000,4.000000,2.000000,4.000000,2.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

RoomTypes_desc_2        0.387321
RoomTypes_desc_5        0.233581
source_1                0.234298
source_5                0.266693
source_7                0.246585
sales_channel_4         0.217509
club_code_6             0.216521
market_segment_bi_id    0.301002
group_member            0.244779
bed_nights              0.417831
adults                  0.341799
children                0.241554
ARR                     1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

RoomTypes_desc_1        0.210326
RoomTypes_desc_2        0.411724
source_1                0.230596
source_5                0.333860
source_7                0.243762
club_code_6             0.218878
market_segment_bi_id    0.219543
group_member            0.242472
bed_nights              0.393291
adults                  0.346686
children                0.229174
ARR                     1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -8.513734822544483e+25
CV STD Accuracy:  8.61782557363333e+25

Train Accuracy:  0.506014376156138
Test Accuracy:  -2.94722449335647e+27

plan_desc_0 --> -1037624779290790.25
plan_desc_1 --> -19424691133124.50
plan_desc_2 --> -101052828433153.25
plan_desc_3 --> -526419109612574.31
plan_desc_4 --> -1008932628768460.25
plan_desc_5 --> -15356815391131.41
plan_desc_6 --> -11895466470590.14
RoomTypes_desc_0 --> 8448242167388.02
RoomTypes_desc_1 --> 420410137709019.88
RoomTypes_desc_2 --> 630669876494249.75
RoomTypes_desc_3 --> 402286394929669.38
RoomTypes_desc_4 --> 269640116937868.19
RoomTypes_desc_5 --> 63351892065126.73
RoomTypes_desc_6 --> 214816714919590.44
RoomTypes_desc_7 --> 134177297848061.28
RoomTypes_desc_8 --> 8448242167398.82
RoomTypes_desc_9 --> 8448242167383.91
RoomTypes_desc_10 --> 79586902164856.69
source_0 --> 27660302256327.54
source_1 --> 655857035361501.62
source_2 --> 106844073245411.02
source_3 --> 406035594670998.62
source_4 --> 18703696282420.04
source_5 --> 348116985758405.44
source_6 --> 290575259238619.62
source_7 --> 451656429332580.31
source_8 --> 673166005080606.38
source_9 --> 261601435748482.22
source_10 --> 95618698202942.89
sales_channel_0 --> 244140198817807.97
sales_channel_1 --> 98013477671210.34
sales_channel_2 --> 70674851888242.84
sales_channel_3 --> 111504507358627.06
sales_channel_4 --> 115451597586277.06
sales_channel_5 --> 30076614588672.34
sales_channel_6 --> 171660385244146.53
club_code_0 --> 1436453919801183.50
club_code_1 --> 61736981019004.18
club_code_2 --> 122827808165113.25
club_code_3 --> 534880773443917.50
club_code_4 --> 52777878358387.02
club_code_5 --> 188904306410757.62
club_code_6 --> 1354705777706494.75
StatisticSource_0 --> -2333618485029768.50
StatisticSource_1 --> -2333618485029769.00
package_code_0 --> -309542795403408.44
package_code_1 --> -104508533306562.84
package_code_2 --> -118211899865632.84
package_code_3 --> -30652163985092.94
package_code_4 --> -55907889640405.94
package_code_5 --> -4910289167773.09
package_code_6 --> -49899495115879.91
package_code_7 --> -50378218836621.05
package_code_8 --> -3472117509424.89
package_code_9 --> -9820260279025.08
package_code_10 --> -8504686689412.36
package_code_11 --> -18370041136413.66
package_code_12 --> -26205987508864.89
package_code_13 --> -11515089412875.66
package_code_14 --> -67545426981897.59
package_code_15 --> -12027053713389.75
package_code_16 --> -32184316826645.23
package_code_17 --> -66384667202879.75
package_code_18 --> -109366227029588.28
package_code_19 --> -68337292549586.64
package_code_20 --> -42912471128370.25
package_code_21 --> -6013819014213.16
package_code_22 --> -191619167977852.75
package_code_23 --> -12518086817703.25
package_code_24 --> -6944122570407.29
package_code_25 --> -7763723148242.84
package_code_26 --> -10979266235095.40
package_code_27 --> -25270301224254.97
package_code_28 --> -19328801472159.77
package_code_29 --> -23543326072116.05
package_code_30 --> -37049451938767.47
nationality_0 --> -5840753467330.54
nationality_1 --> -7153394241966.91
nationality_2 --> -14890173773206.45
nationality_3 --> -40234402929304.59
nationality_4 --> -100251612809771.59
nationality_5 --> -65083928949169.84
nationality_6 --> -47774551947605.86
nationality_7 --> -58635443855064.96
nationality_8 --> -36693306231058.98
nationality_9 --> -22991469618278.61
nationality_10 --> -13697115611090.92
nationality_11 --> -11681128608720.64
nationality_12 --> -120206534065998.83
nationality_13 --> -7534118093813131.00
nationality_14 --> -11681128608728.47
nationality_15 --> -9234892558896.99
nationality_16 --> -128151021641175.47
nationality_17 --> -54271984453016.50
nationality_18 --> -25117284073037.66
nationality_19 --> -229250313363394.25
nationality_20 --> -14306093445426.75
nationality_21 --> -61047326397029.98
nationality_22 --> -33029232037594.88
nationality_23 --> -31981107343021.80
nationality_24 --> -31443911114232.43
nationality_25 --> -182295573240995.38
nationality_26 --> -37835651079612.20
nationality_27 --> -10926754268886.54
nationality_28 --> -26115285360126.84
nationality_29 --> 608496384376942.62
nationality_30 --> -81078361829694.44
nationality_31 --> -10926754268886.53
nationality_32 --> -19804713401921.59
nationality_33 --> -32509405323645.86
nationality_34 --> -168278952208998.12
nationality_35 --> -197452302396203.81
nationality_36 --> -14890173773206.33
nationality_37 --> -41071821997008.81
nationality_38 --> -4130058676637.72
nationality_39 --> -34541678213273.71
nationality_40 --> -33029232037587.71
nationality_41 --> -20230560723628.28
nationality_42 --> -33286092949199.76
nationality_43 --> -34787341648176.93
nationality_44 --> -50204449950418.62
nationality_45 --> -221622468340425.62
nationality_46 --> -94095036429156.31
nationality_47 --> -23359230364850.62
nationality_48 --> -18468289592670.11
nationality_49 --> -625223552325224.75
nationality_50 --> -142315730295286.34
nationality_51 --> -46876029194472.45
nationality_52 --> -102657523907815.56
nationality_53 --> -35273520442744.17
nationality_54 --> -32246341107651.56
nationality_55 --> -20230560723631.16
nationality_56 --> -28606625907310.96
nationality_57 --> -5840753467330.85
nationality_58 --> -102821318203639.81
nationality_59 --> -1782223274134092.00
nationality_60 --> -4130058676635.44
nationality_61 --> -19369496389770.91
nationality_62 --> -11681128608725.30
nationality_63 --> -18924263250532.37
nationality_64 --> -13059757814715.92
nationality_65 --> -7153394241968.12
nationality_66 --> -14306093445426.84
nationality_67 --> -77667436939978.89
nationality_68 --> -14306093445429.78
nationality_69 --> -1292806097352860.00
nationality_70 --> -30620405989786.85
nationality_71 --> -279083237386458.19
nationality_72 --> -16518897097090.67
nationality_73 --> -88168819315925.78
nationality_74 --> -24429272147468.00
nationality_75 --> -21851031130031.60
nationality_76 --> -58924365864339.00
nationality_77 --> -8259983596657.75
nationality_78 --> -22237685003433.08
nationality_79 --> -106753649763739.86
nationality_80 --> -87399186138328.53
nationality_81 --> -10116263334499.23
nationality_82 --> -35273520442742.11
nationality_83 --> -16518897097094.43
nationality_84 --> -45774393703646.62
nationality_85 --> -44262683717235.22
nationality_86 --> -133881006262338.56
nationality_87 --> -18924263250532.17
nationality_88 --> -8259983596661.33
nationality_89 --> -21056407834117.27
nationality_90 --> -92467509582321.38
nationality_91 --> -12389640996239.80
nationality_92 --> -13697115611088.52
nationality_93 --> -15452180171239.85
nationality_94 --> -71537717317164.50
nationality_95 --> -10116263334497.45
nationality_96 --> -38944384140720.05
nationality_97 --> -27389350738031.12
nationality_98 --> -7153394241967.78
nationality_99 --> -5840753467331.82
nationality_100 --> -10926754268884.61
nationality_101 --> -38283012196625.79
nationality_102 --> -99068669451057.78
nationality_103 --> -41688802243929.15
nationality_104 --> -4130058676637.03
nationality_105 --> -4130058676637.58
nationality_106 --> -554491742403451.12
nationality_107 --> -21851031130030.61
nationality_108 --> -22237685003430.99
nationality_109 --> -26759915325042.49
nationality_110 --> -10926754268884.38
nationality_111 --> -52196714852180.02
nationality_112 --> -30340925585119.65
nationality_113 --> -11681128608723.79
market_segment_bi_id --> -37.12
MainCust --> 16.38
group_member --> -37.12
m_length_of_stay --> -8.06
bed_nights --> 1788129347984145.25
m_lead_days --> 9.12
adults --> -1305460992227254.00
juniors --> -31019463794027.47
children --> -1247084261133742.75
babies --> 14.19
Model: ridge_regressor
CV Mean Accuracy:  0.5044344868397689
CV STD Accuracy:  0.004161457888765251

Train Accuracy:  0.5077069094428461
Test Accuracy:  0.5160745290403488

Model: lasso_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 674325.4719772339, tolerance: 590687.2001209782
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 858269.2314543724, tolerance: 590533.8087721382
  positive)

CV Mean Accuracy:  0.5044773821591033
CV STD Accuracy:  0.004153336965656081

Train Accuracy:  0.5076439767527139
Test Accuracy:  0.5162135920353713

Model: elasticnet_regressor
CV Mean Accuracy:  0.4732173185014286
CV STD Accuracy:  0.004683665561396256

Train Accuracy:  0.4752490978190208
Test Accuracy:  0.4817412070369822

Model: supportvect_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

CV Mean Accuracy:  0.47887379642354677
CV STD Accuracy:  0.006232803643201195

Train Accuracy:  0.483039331573205
Test Accuracy:  0.4892638572403022

Model: decisiontree_regressor
CV Mean Accuracy:  0.7022439646606884
CV STD Accuracy:  0.008839657741774897

Train Accuracy:  0.9126895720719719
Test Accuracy:  0.7209365541790853

Model: randomforest_regressor
CV Mean Accuracy:  0.28238345769885004
CV STD Accuracy:  0.006068004886240692

Train Accuracy:  0.2814580450465243
Test Accuracy:  0.301966094242326

Model: xgboost_regressor
CV Mean Accuracy:  0.6758473693383069
CV STD Accuracy:  0.005400136050312968

Train Accuracy:  0.6818557542595094
Test Accuracy:  0.6803570382628199

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -5.178651768366149e+34
CV STD Accuracy:  4.058038184799178e+34

Train Accuracy:  0.8247621432063893
Test Accuracy:  -1.0877440062256279e+35

                        train_accuracy  test_accuracy
linear_regressor                0.5060         0.0000
ridge_regressor                 0.5077         0.5161
lasso_regressor                 0.5076         0.5162
elasticnet_regressor            0.4752         0.4817
supportvect_regressor           0.4830         0.4893
decisiontree_regressor          0.9127         0.7209
randomforest_regressor          0.2815         0.3020
xgboost_regressor               0.6819         0.6804
mlp_regressor                   0.8248         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 543.0

reservations_df shape: (144841, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-11-12,full board,superior carmel vi,40.0,7956.0,co,,,,,usa,1.0,11.0,1.0,13.0,1.0,0.0,0.0,0.0,452.4
2018-11-09,full board,superior carmel vi,40.0,7956.0,co,,,,,usa,1.0,11.0,1.0,13.0,1.0,0.0,0.0,0.0,452.4
2018-11-10,full board,superior carmel vi,40.0,7956.0,co,,,,,usa,1.0,11.0,1.0,13.0,1.0,0.0,0.0,0.0,452.4
2018-11-06,full board,superior carmel vi,40.0,7956.0,co,,,,,usa,1.0,11.0,1.0,13.0,1.0,0.0,0.0,0.0,452.4
2018-11-11,full board,superior carmel vi,40.0,7956.0,co,,,,,usa,1.0,11.0,1.0,13.0,1.0,0.0,0.0,0.0,452.4

<class 'pandas.core.frame.DataFrame'>
Index: 144841 entries, 2018-11-12 to 2019-05-26
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   plan_desc             144841 non-null  object
 1   RoomTypes_desc        144841 non-null  object
 2   market_segment_bi_id  144841 non-null  float64
 3   MainCust              144841 non-null  float64
 4   source                144841 non-null  object
 5   sales_channel         144841 non-null  object
 6   club_code             144841 non-null  object
 7   StatisticSource       144841 non-null  object
 8   package_code          144841 non-null  object
 9   nationality           144841 non-null  object
 10  group_member          144841 non-null  float64
 11  m_length_of_stay      144841 non-null  float64
 12  bed_nights            144841 non-null  float64
 13  m_lead_days           144841 non-null  float64
 14  adults                144841 non-null  float64
 15  juniors               144841 non-null  float64
 16  children              144841 non-null  float64
 17  babies                144841 non-null  float64
 18  ARR                   144841 non-null  float64
dtypes: float64(11), object(8)
memory usage: 22.1+ MB
(144841, 226)

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,plan_desc_7,plan_desc_8,RoomTypes_desc_0,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-11-12,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,40.0,7956.0,1.0,11.0,1.0,13.0,1.0,0.0,0.0,0.0
2018-11-09,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,40.0,7956.0,1.0,11.0,1.0,13.0,1.0,0.0,0.0,0.0
2018-11-10,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,40.0,7956.0,1.0,11.0,1.0,13.0,1.0,0.0,0.0,0.0
2018-11-06,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,40.0,7956.0,1.0,11.0,1.0,13.0,1.0,0.0,0.0,0.0
2018-11-11,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,40.0,7956.0,1.0,11.0,1.0,13.0,1.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,plan_desc_7,plan_desc_8,RoomTypes_desc_0,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000,...,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000,144841.000000
mean,0.589101,0.000746,0.000490,0.003652,0.065845,0.325992,0.000131,0.001671,0.012372,0.019290,...,27.800436,8564.885405,0.516594,9.821245,1.350384,51.320759,1.281163,0.000028,0.069193,0.015362
std,0.491999,0.027296,0.022135,0.060324,0.248011,0.468746,0.011453,0.040841,0.110540,0.137543,...,14.475088,2782.301318,0.499726,16.757560,0.582173,66.279981,0.499474,0.005255,0.328316,0.126146
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,388.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,13.000000,7720.000000,0.000000,2.000000,1.000000,8.000000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,40.000000,9006.000000,1.000000,3.000000,1.000000,22.000000,1.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,40.000000,9961.000000,1.000000,10.000000,2.000000,63.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13187.000000,1.000000,203.000000,4.000000,299.000000,3.000000,1.000000,3.000000,2.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

RoomTypes_desc_2        0.202510
RoomTypes_desc_5        0.211013
RoomTypes_desc_7        0.337328
source_1                0.322805
source_8                0.322199
sales_channel_5         0.223365
club_code_6             0.263427
package_code_0          0.263934
nationality_54          0.324364
market_segment_bi_id    0.343452
group_member            0.301726
m_length_of_stay        0.227464
bed_nights              0.481495
adults                  0.412766
children                0.225796
ARR                     1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

RoomTypes_desc_7        0.340857
source_1                0.307913
source_7                0.226432
source_8                0.292457
sales_channel_0         0.210793
sales_channel_5         0.204704
club_code_6             0.225688
package_code_0          0.257080
nationality_54          0.267875
market_segment_bi_id    0.251523
group_member            0.323628
m_length_of_stay        0.348394
bed_nights              0.438608
adults                  0.389731
children                0.225778
ARR                     1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -4.3226372907596924e+24
CV STD Accuracy:  6.863323655923746e+24

Train Accuracy:  0.47032360761413616
Test Accuracy:  -1.0053958067549853e+25

plan_desc_0 --> -39719840523055.62
plan_desc_1 --> -2203683620094.67
plan_desc_2 --> -1786989683596.74
plan_desc_3 --> -4870041281049.11
plan_desc_4 --> -20022338207599.22
plan_desc_5 --> -37842609644989.62
plan_desc_6 --> -924586727087.87
plan_desc_7 --> -3297189525421.99
plan_desc_8 --> -8924111739721.91
RoomTypes_desc_0 --> -51106121323710.07
RoomTypes_desc_1 --> -74728924070626.66
RoomTypes_desc_2 --> -14633328406939.79
RoomTypes_desc_3 --> -46716537251309.21
RoomTypes_desc_4 --> -45687429857261.15
RoomTypes_desc_5 --> -24490542729844.05
RoomTypes_desc_6 --> -58746705686038.41
RoomTypes_desc_7 --> -126046956149884.34
RoomTypes_desc_8 --> -14600824168304.08
RoomTypes_desc_9 --> -10734965420820.22
RoomTypes_desc_10 --> -28180679905315.30
source_0 --> -769651317918.22
source_1 --> -36567500108622.22
source_2 --> -9058254939078.36
source_3 --> -19586582294714.66
source_4 --> -1105262677681.02
source_5 --> -1609541076437.85
source_6 --> -2990904768940.85
source_7 --> -16512455115318.04
source_8 --> -20892683483545.58
source_9 --> -32135360483078.70
source_10 --> -11136857881641.01
source_11 --> -4062006300751.14
sales_channel_0 --> 1420302216845.86
sales_channel_1 --> 608917737086.26
sales_channel_2 --> 56838530021.22
sales_channel_3 --> 504382801053.24
sales_channel_4 --> 569923931102.13
sales_channel_5 --> 628367932586.13
sales_channel_6 --> 261239545933.85
sales_channel_7 --> 971642081300.73
club_code_0 --> -249555594883754.19
club_code_1 --> -12220836237522.16
club_code_2 --> -41200244848014.96
club_code_3 --> -115435108715454.59
club_code_4 --> -3088009299559.67
club_code_5 --> -71117218552874.59
club_code_6 --> -217520014899574.31
StatisticSource_0 --> 194455835047911.75
StatisticSource_1 --> 193883732647996.56
StatisticSource_2 --> -250991472291783.44
package_code_0 --> 80283537074173.97
package_code_1 --> 32739767606398.97
package_code_2 --> 2051850820394.85
package_code_3 --> 40904271142464.03
package_code_4 --> 5363022321069.36
package_code_5 --> 11659742935605.04
package_code_6 --> 8204852858398.99
package_code_7 --> 8782345516947.82
package_code_8 --> 12130361318593.59
package_code_9 --> 2648891439947.95
package_code_10 --> 9473100690057.73
package_code_11 --> 10523754090578.64
package_code_12 --> 1184652981808.18
package_code_13 --> 2901695152835.32
package_code_14 --> 3553762641554.56
package_code_15 --> 11838429737704.84
package_code_16 --> 7396214263390.01
package_code_17 --> 2512967742900.64
package_code_18 --> 1675340746540.65
package_code_19 --> 18567876563372.67
package_code_20 --> 24250763295953.94
package_code_21 --> 16813700514099.37
package_code_22 --> 6647448117311.84
package_code_23 --> 19447563280854.63
package_code_24 --> 14590148263626.59
package_code_25 --> 10523754090579.67
package_code_26 --> 2216244535497.36
package_code_27 --> 7720779420492.67
package_code_28 --> 2051850820393.53
package_code_29 --> 31824455999794.50
package_code_30 --> 9728447708892.58
package_code_31 --> 3134167337866.52
package_code_32 --> 1873081431165.98
package_code_33 --> 1675340746543.76
package_code_34 --> 2216244535496.86
package_code_35 --> 1675340746542.82
package_code_36 --> 4510603680966.63
package_code_37 --> 2512967742900.48
package_code_38 --> 2051850820394.42
package_code_39 --> 5025466989260.61
nationality_0 --> 1582651208580.85
nationality_1 --> 1043616141567.82
nationality_2 --> 1682687510757.32
nationality_3 --> 17257648245824.71
nationality_4 --> 1278141453878.86
nationality_5 --> 9655231326891.25
nationality_6 --> 7381654730888.88
nationality_7 --> 5860370227933.30
nationality_8 --> 6006569586294.56
nationality_9 --> 330030654831.30
nationality_10 --> 873160951793.83
nationality_11 --> 3506917304866.88
nationality_12 --> 571625915579.17
nationality_13 --> 3732233281341.20
nationality_14 --> 11778019289722.53
nationality_15 --> 1143216310693.36
nationality_16 --> 12499903979084.96
nationality_17 --> 6201918302126.99
nationality_18 --> 3506917304866.42
nationality_19 --> 22629670724113.32
nationality_20 --> 330030654831.29
nationality_21 --> 990064621063.04
nationality_22 --> 3958412346869.31
nationality_23 --> 1234806219251.07
nationality_24 --> 5681830609880.77
nationality_25 --> 8350166358405.63
nationality_26 --> 7683128979118.06
nationality_27 --> 29830032108893.18
nationality_28 --> 660054473863.71
nationality_29 --> 4558121796194.54
nationality_30 --> 4198269167550.33
nationality_31 --> 3380593527293.66
nationality_32 --> 15310196506955.26
nationality_33 --> 1475845148081.66
nationality_34 --> 5595254195592.10
nationality_35 --> 4510202589485.20
nationality_36 --> 808392750250.98
nationality_37 --> 15454366669058.95
nationality_38 --> 19910614248664.26
nationality_39 --> 2402228097679.15
nationality_40 --> 466732216854.14
nationality_41 --> 2639670972074.80
nationality_42 --> 6006569586289.95
nationality_43 --> 1475845148081.16
nationality_44 --> 2819082206374.34
nationality_45 --> 5387791145735.03
nationality_46 --> 13753507768278.42
nationality_47 --> 5662706727500.09
nationality_48 --> 3164548257151.54
nationality_49 --> 1278141453878.77
nationality_50 --> 32549315980420.70
nationality_51 --> 5507305886060.77
nationality_52 --> 466732216853.51
nationality_53 --> 1682687510757.33
nationality_54 --> 58071943706903.44
nationality_55 --> 14617415001564.96
nationality_56 --> 571625915579.39
nationality_57 --> 1278141453879.34
nationality_58 --> 11773476517229.07
nationality_59 --> 4510202589481.00
nationality_60 --> 3553127539498.21
nationality_61 --> 1278141453878.46
nationality_62 --> 330030654831.54
nationality_63 --> 9864694389359.40
nationality_64 --> 1512286035806.37
nationality_65 --> 737960788636.69
nationality_66 --> 466732216855.70
nationality_67 --> 1512286035806.22
nationality_68 --> 2512943970091.23
nationality_69 --> 1866735512149.40
nationality_70 --> 1475845148081.24
nationality_71 --> 2660204281153.77
nationality_72 --> 737960788636.24
nationality_73 --> 990064621063.12
nationality_74 --> 12439978641496.99
nationality_75 --> 1512286035805.00
nationality_76 --> 1895672328542.51
nationality_77 --> 466732216853.65
nationality_78 --> 1952258506179.12
nationality_79 --> 1143216310693.66
nationality_80 --> 5076616409955.29
nationality_81 --> 1777097671379.24
nationality_82 --> 2402228097678.72
nationality_83 --> 10498077557932.34
nationality_84 --> 3428512071108.30
nationality_85 --> 1582651208579.39
nationality_86 --> 737960788639.07
nationality_87 --> 2680580028667.66
nationality_88 --> 5337197537519.57
nationality_89 --> 1360676088620.75
nationality_90 --> 2112935463282.72
nationality_91 --> 15905047476114.01
nationality_92 --> 7711217160579.77
nationality_93 --> 1895672328543.23
nationality_94 --> 4640783715974.95
nationality_95 --> 1189893154057.85
nationality_96 --> 5614609707468.18
nationality_97 --> 3491377550323.80
nationality_98 --> 12011789975156.61
nationality_99 --> 3428512071106.68
nationality_100 --> 1682687510755.97
nationality_101 --> 12011789975154.79
nationality_102 --> 17656214762951.58
nationality_103 --> 2876395538862.94
nationality_104 --> 3506917304866.52
nationality_105 --> 4510202589487.08
nationality_106 --> 5306608142786.50
nationality_107 --> 2007248603602.32
nationality_108 --> 933445098981.87
nationality_109 --> 7322803469396.73
nationality_110 --> 933445098981.62
nationality_111 --> 330030654831.35
nationality_112 --> 6849344758182.77
nationality_113 --> 12512706252153.13
nationality_114 --> 660054473863.63
nationality_115 --> 2660204281151.81
nationality_116 --> 7877611305347.26
nationality_117 --> 1777097671379.68
nationality_118 --> 52028404677241.34
nationality_119 --> 1895672328543.08
nationality_120 --> 466732216853.25
nationality_121 --> 4891443523566.69
nationality_122 --> 737960788636.09
nationality_123 --> 4350802655303.10
nationality_124 --> 1189893154057.74
nationality_125 --> 3266042605093.49
market_segment_bi_id --> -7.38
MainCust --> 14.23
group_member --> -34.03
m_length_of_stay --> -17.02
bed_nights --> 49229109717966.95
m_lead_days --> -7.59
adults --> -42236008634041.95
juniors --> -444374837847.28
children --> -27762740560858.21
babies --> 8.60
Model: ridge_regressor
CV Mean Accuracy:  0.4676232927516219
CV STD Accuracy:  0.00864254969653624

Train Accuracy:  0.47036759579893095
Test Accuracy:  0.47745185563688286

Model: lasso_regressor
CV Mean Accuracy:  0.4677160388377771
CV STD Accuracy:  0.00864371904579128

Train Accuracy:  0.4702600354693872
Test Accuracy:  0.47726091468539544

Model: elasticnet_regressor
CV Mean Accuracy:  0.43795925887356724
CV STD Accuracy:  0.006978944948862078

Train Accuracy:  0.43940713115612273
Test Accuracy:  0.4409690616728561

Model: supportvect_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

CV Mean Accuracy:  0.42818630611560937
CV STD Accuracy:  0.009556708567094722

Train Accuracy:  0.4333533949383477
Test Accuracy:  0.44264424464544416

Model: decisiontree_regressor
CV Mean Accuracy:  0.675852172357766
CV STD Accuracy:  0.006398801668383113

Train Accuracy:  0.8921799511587185
Test Accuracy:  0.696384200095461

Model: randomforest_regressor
CV Mean Accuracy:  0.3028970676347253
CV STD Accuracy:  0.006273269864297783

Train Accuracy:  0.3029652271244403
Test Accuracy:  0.3004988889292898

Model: xgboost_regressor
CV Mean Accuracy:  0.6405818578364924
CV STD Accuracy:  0.009480331042714943

Train Accuracy:  0.6503687708829897
Test Accuracy:  0.6519664867483048

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -3.579311107217845e+34
CV STD Accuracy:  7.15862221443569e+34

Train Accuracy:  0.7802121824797208
Test Accuracy:  -4.644123359466579e+34

                        train_accuracy  test_accuracy
linear_regressor                0.4703         0.0000
ridge_regressor                 0.4704         0.4775
lasso_regressor                 0.4703         0.4773
elasticnet_regressor            0.4394         0.4410
supportvect_regressor           0.4334         0.4426
decisiontree_regressor          0.8922         0.6964
randomforest_regressor          0.3030         0.3005
xgboost_regressor               0.6504         0.6520
mlp_regressor                   0.7802         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 545.0

reservations_df shape: (31309, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2019-10-18,breakfast board,caesarea room,4.0,4715.0,ot,expedia,,,,isr,0.0,3.0,3.0,241.0,2.0,0.0,1.0,0.0,1639.73
2019-10-16,breakfast board,caesarea room,4.0,4715.0,ot,expedia,,,,gbr,0.0,3.0,3.0,241.0,2.0,0.0,1.0,0.0,1639.73
2019-10-17,breakfast board,caesarea room,4.0,4715.0,ot,expedia,,,,isr,0.0,3.0,3.0,241.0,2.0,0.0,1.0,0.0,1639.73
2019-10-18,breakfast board,deluxe room,4.0,4715.0,ot,expedia,,,,isr,0.0,3.0,2.0,241.0,2.0,0.0,0.0,0.0,1622.89
2019-10-16,breakfast board,deluxe room,4.0,4715.0,ot,expedia,,,,gbr,0.0,3.0,2.0,241.0,2.0,0.0,0.0,0.0,1622.89

<class 'pandas.core.frame.DataFrame'>
Index: 31309 entries, 2019-10-18 to 2019-06-30
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   plan_desc             31309 non-null  object
 1   RoomTypes_desc        31309 non-null  object
 2   market_segment_bi_id  31309 non-null  float64
 3   MainCust              31309 non-null  float64
 4   source                31309 non-null  object
 5   sales_channel         31309 non-null  object
 6   club_code             31309 non-null  object
 7   StatisticSource       31309 non-null  object
 8   package_code          31309 non-null  object
 9   nationality           31309 non-null  object
 10  group_member          31309 non-null  float64
 11  m_length_of_stay      31309 non-null  float64
 12  bed_nights            31309 non-null  float64
 13  m_lead_days           31309 non-null  float64
 14  adults                31309 non-null  float64
 15  juniors               31309 non-null  float64
 16  children              31309 non-null  float64
 17  babies                31309 non-null  float64
 18  ARR                   31309 non-null  float64
dtypes: float64(11), object(8)
memory usage: 4.8+ MB
(31309, 143)

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,plan_desc_7,plan_desc_8,plan_desc_9,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2019-10-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4715.0,0.0,3.0,3.0,241.0,2.0,0.0,1.0,0.0
2019-10-16,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4715.0,0.0,3.0,3.0,241.0,2.0,0.0,1.0,0.0
2019-10-17,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4715.0,0.0,3.0,3.0,241.0,2.0,0.0,1.0,0.0
2019-10-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4715.0,0.0,3.0,2.0,241.0,2.0,0.0,0.0,0.0
2019-10-16,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4715.0,0.0,3.0,2.0,241.0,2.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,plan_desc_7,plan_desc_8,plan_desc_9,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,31309.000000,31309.000000,31309.000000,31309.000000,31309.000000,31309.00000,31309.000000,31309.000000,31309.000000,31309.000000,...,31309.000000,31309.000000,31309.000000,31309.000000,31309.000000,31309.000000,31309.000000,31309.0,31309.000000,31309.000000
mean,0.523236,0.000224,0.001437,0.022422,0.001437,0.08464,0.362548,0.000447,0.003226,0.000383,...,21.435178,9178.996710,0.460954,2.959181,1.813632,55.334217,1.522661,0.0,0.290971,0.064965
std,0.499468,0.014951,0.037885,0.148053,0.037885,0.27835,0.480743,0.021142,0.056706,0.019574,...,16.035273,3024.651549,0.498481,2.931361,0.867104,67.202421,0.591267,0.0,0.682027,0.261436
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,4.000000,388.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,7.000000,7880.000000,0.000000,1.000000,1.000000,9.000000,1.000000,0.0,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,15.000000,9525.000000,0.000000,2.000000,2.000000,23.000000,2.000000,0.0,0.000000,0.000000
75%,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.000000,...,40.000000,12346.000000,1.000000,3.000000,2.000000,78.000000,2.000000,0.0,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13200.000000,1.000000,35.000000,5.000000,299.000000,4.000000,0.0,4.000000,3.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

RoomTypes_desc_0        0.346894
RoomTypes_desc_1        0.211678
source_0                0.330518
source_6                0.352923
sales_channel_0         0.272622
sales_channel_4         0.211069
club_code_0             0.348214
club_code_6             0.331526
market_segment_bi_id    0.338992
group_member            0.498066
bed_nights              0.433418
adults                  0.253655
children                0.331132
ARR                     1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

plan_desc_0             0.249130
plan_desc_3             0.201166
RoomTypes_desc_0        0.312248
source_0                0.344399
source_6                0.371437
sales_channel_0         0.317761
sales_channel_4         0.222190
club_code_0             0.374039
club_code_6             0.356702
package_code_0          0.286288
package_code_15         0.223742
market_segment_bi_id    0.260172
MainCust                0.224590
group_member            0.536099
bed_nights              0.432021
adults                  0.289856
children                0.345083
ARR                     1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -3.2494428001901375e+25
CV STD Accuracy:  2.2651891675598336e+25

Train Accuracy:  0.5055551889839671
Test Accuracy:  -1.5005960844691884e+25

plan_desc_0 --> 58783597508990.20
plan_desc_1 --> 1759630566043.99
plan_desc_2 --> 4458768884296.32
plan_desc_3 --> 17424702488896.14
plan_desc_4 --> 4458768884285.94
plan_desc_5 --> 32759697812688.19
plan_desc_6 --> 56579877755291.07
plan_desc_7 --> 2488215147463.49
plan_desc_8 --> 6673906060049.62
plan_desc_9 --> 2303713205363.87
RoomTypes_desc_0 --> -2083144528514248.50
RoomTypes_desc_1 --> -1053002541233636.00
RoomTypes_desc_2 --> -1705880278705590.00
RoomTypes_desc_3 --> -83515903275371.64
RoomTypes_desc_4 --> -605474751136698.12
RoomTypes_desc_5 --> -359678404711309.06
RoomTypes_desc_6 --> -312163301014649.38
RoomTypes_desc_7 --> -91485626988659.50
source_0 --> 2384811461676454.00
source_1 --> 1004949107448403.12
source_2 --> 5614844992874439.00
source_3 --> 29188470186301.00
source_4 --> 71491148948448.69
source_5 --> 1197856079761516.00
source_6 --> 2129500994185158.75
source_7 --> 2400482912894640.00
source_8 --> -23862489549813.93
source_9 --> 343367725929236.19
sales_channel_0 --> -925852544529909.62
sales_channel_1 --> -408410852435967.31
sales_channel_2 --> -361799331773768.81
sales_channel_3 --> 581073131047472.25
sales_channel_4 --> -559640255867017.81
sales_channel_5 --> -204423492981183.25
sales_channel_6 --> -5308089220627709.00
club_code_0 --> -4258890286047465.00
club_code_1 --> -280685267873800.34
club_code_2 --> -475980743214984.12
club_code_3 --> -1517480276954156.00
club_code_4 --> -202443840924530.62
club_code_5 --> -112311783928553.66
club_code_6 --> -4082048051638124.50
StatisticSource_0 --> 201703859607627.50
StatisticSource_1 --> 201703859607627.75
package_code_0 --> -2849249822222431.00
package_code_1 --> -468385631490631.75
package_code_2 --> -214682716118675.38
package_code_3 --> -64749959961481.94
package_code_4 --> -254802752017517.50
package_code_5 --> -204698480668051.75
package_code_6 --> -416582482429051.69
package_code_7 --> -177288248058565.53
package_code_8 --> -963218712625327.25
package_code_9 --> -1263509388233109.00
package_code_10 --> -421558171152457.62
package_code_11 --> -590113113313426.75
package_code_12 --> -209750173427190.41
package_code_13 --> -171279456238462.25
package_code_14 --> -363054035668480.00
package_code_15 --> -1978849527406721.50
package_code_16 --> -310311607365958.31
package_code_17 --> -336171127908483.00
package_code_18 --> -224221617026748.12
package_code_19 --> -326715291241585.88
package_code_20 --> -303500446617554.50
package_code_21 --> -600562541318645.88
package_code_22 --> -765417216826842.50
nationality_0 --> 30529905629310.45
nationality_1 --> 183077014697360.31
nationality_2 --> -865104007123722.12
nationality_3 --> 450225633389348.50
nationality_4 --> 204656869717865.69
nationality_5 --> 335184746938335.31
nationality_6 --> 96530160954588.20
nationality_7 --> 383994838625057.06
nationality_8 --> 441982685682225.44
nationality_9 --> 289220150562429.00
nationality_10 --> 389954459173383.25
nationality_11 --> 133038512784598.50
nationality_12 --> 43175117060293.94
nationality_13 --> 152591008102912.03
nationality_14 --> 579086892145856.25
nationality_15 --> 258760931754355.75
nationality_16 --> 351345031306957.38
nationality_17 --> 61056885747200.11
nationality_18 --> 188087737500858.94
nationality_19 --> 829784965381281.88
nationality_20 --> 1096919301991209.88
nationality_21 --> 43175117060292.67
nationality_22 --> 177924566751227.56
nationality_23 --> 43175117060295.19
nationality_24 --> 96530160954594.78
nationality_25 --> 74776718916587.16
nationality_26 --> 80766797484323.00
nationality_27 --> 289220150562420.69
nationality_28 --> 245888259118326.47
nationality_29 --> 30529905629308.50
nationality_30 --> 2514004884627597.00
nationality_31 --> 505874242531875.00
nationality_32 --> 96530160954587.00
nationality_33 --> 197726806139154.56
nationality_34 --> 30529905629306.36
nationality_35 --> 242083554932293.38
nationality_36 --> 129492248832023.00
nationality_37 --> 30529905629303.16
nationality_38 --> 61056885747208.38
nationality_39 --> 347376605047221.00
nationality_40 --> 152591008102906.81
nationality_41 --> 30529905629302.12
nationality_42 --> 146364831726803.50
nationality_43 --> 381584383379578.00
nationality_44 --> 91578014375004.25
nationality_45 --> 30529905629304.61
nationality_46 --> 289220150562410.25
nationality_47 --> 52877658668926.19
nationality_48 --> 258760931754352.94
nationality_49 --> 200063650439546.12
nationality_50 --> 197726806139160.31
nationality_51 --> 86341959194370.00
nationality_52 --> 576723561316801.38
nationality_53 --> 122090364599138.31
nationality_54 --> 183077014697359.75
nationality_55 --> 86341959194362.53
nationality_56 --> 86341959194360.09
nationality_57 --> 167141716014472.06
nationality_58 --> 86341959194366.56
nationality_59 --> 172617703111625.53
nationality_60 --> 43175117060292.31
nationality_61 --> 195361859027010.16
nationality_62 --> 52877658668932.97
nationality_63 --> 1855632479157127.00
nationality_64 --> 74776718916593.33
nationality_65 --> 200063650439540.00
market_segment_bi_id --> -54.50
MainCust --> 55.50
group_member --> -213.19
m_length_of_stay --> -28.50
bed_nights --> -2648781292314122.00
m_lead_days --> 70.44
adults --> 1806169023057386.25
juniors --> 4.50
children --> 2083417748860220.00
babies --> 12.50
Model: ridge_regressor
CV Mean Accuracy:  0.5025453937679144
CV STD Accuracy:  0.00795607404031387

Train Accuracy:  0.507869223937303
Test Accuracy:  0.5159173557722359

Model: lasso_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1918781.8910713196, tolerance: 543960.6484574301
  positive)

CV Mean Accuracy:  0.5025485328928687
CV STD Accuracy:  0.007940854285456133

Train Accuracy:  0.507840972925315
Test Accuracy:  0.5160474724563988

Model: elasticnet_regressor
CV Mean Accuracy:  0.4712243923047691
CV STD Accuracy:  0.0064628918561100345

Train Accuracy:  0.4744532657567857
Test Accuracy:  0.48802447867124765

Model: supportvect_regressor
CV Mean Accuracy:  0.44136537564988887
CV STD Accuracy:  0.006961814329244017

Train Accuracy:  0.4517794784138142
Test Accuracy:  0.4589782724763989

Model: decisiontree_regressor
CV Mean Accuracy:  0.7820832279535078
CV STD Accuracy:  0.010119947888172384

Train Accuracy:  0.9550611573333402
Test Accuracy:  0.795969083901011

Model: randomforest_regressor
CV Mean Accuracy:  0.4205714196702398
CV STD Accuracy:  0.008699137495518441

Train Accuracy:  0.4216347792882067
Test Accuracy:  0.4336398772809989

Model: xgboost_regressor
CV Mean Accuracy:  0.7117733495979743
CV STD Accuracy:  0.00787753123306023

Train Accuracy:  0.7208280257819818
Test Accuracy:  0.7205689549529954

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -7.523644023017383e+34
CV STD Accuracy:  5.461618148639709e+34

Train Accuracy:  0.8558837597202119
Test Accuracy:  -4.955488166458926e+35

                        train_accuracy  test_accuracy
linear_regressor                0.5056         0.0000
ridge_regressor                 0.5079         0.5159
lasso_regressor                 0.5078         0.5160
elasticnet_regressor            0.4745         0.4880
supportvect_regressor           0.4518         0.4590
decisiontree_regressor          0.9551         0.7960
randomforest_regressor          0.4216         0.4336
xgboost_regressor               0.7208         0.7206
mlp_regressor                   0.8559         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 546.0

reservations_df shape: (84439, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-10-04,breakfast board,garden chalet,15.0,12845.0,dan,,,,,isr,0.0,2.0,2.0,156.0,2.0,0.0,0.0,0.0,1266.72
2018-10-05,breakfast board,garden chalet,15.0,12845.0,dan,,,,,isr,0.0,2.0,2.0,156.0,2.0,0.0,0.0,0.0,1266.72
2018-10-04,breakfast board,garden chalet,15.0,12845.0,dan,,,,,isr,0.0,1.0,2.0,156.0,2.0,0.0,0.0,0.0,1266.72
2018-10-04,breakfast board,garden chalet,15.0,12845.0,dan,,,,,isr,0.0,1.0,2.0,156.0,2.0,0.0,0.0,0.0,1266.72
2018-10-04,breakfast board,garden chalet,15.0,12845.0,dan,,,,,isr,0.0,1.0,2.0,156.0,2.0,0.0,0.0,0.0,1266.72

<class 'pandas.core.frame.DataFrame'>
Index: 84439 entries, 2018-10-04 to 2019-06-30
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   plan_desc             84439 non-null  object
 1   RoomTypes_desc        84439 non-null  object
 2   market_segment_bi_id  84439 non-null  float64
 3   MainCust              84439 non-null  float64
 4   source                84439 non-null  object
 5   sales_channel         84439 non-null  object
 6   club_code             84439 non-null  object
 7   StatisticSource       84439 non-null  object
 8   package_code          84439 non-null  object
 9   nationality           84439 non-null  object
 10  group_member          84439 non-null  float64
 11  m_length_of_stay      84439 non-null  float64
 12  bed_nights            84439 non-null  float64
 13  m_lead_days           84439 non-null  float64
 14  adults                84439 non-null  float64
 15  juniors               84439 non-null  float64
 16  children              84439 non-null  float64
 17  babies                84439 non-null  float64
 18  ARR                   84439 non-null  float64
dtypes: float64(11), object(8)
memory usage: 12.9+ MB
(84439, 204)

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-10-04,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,12845.0,0.0,2.0,2.0,156.0,2.0,0.0,0.0,0.0
2018-10-05,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,12845.0,0.0,2.0,2.0,156.0,2.0,0.0,0.0,0.0
2018-10-04,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,12845.0,0.0,1.0,2.0,156.0,2.0,0.0,0.0,0.0
2018-10-04,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,12845.0,0.0,1.0,2.0,156.0,2.0,0.0,0.0,0.0
2018-10-04,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,12845.0,0.0,1.0,2.0,156.0,2.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000,...,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000,84439.000000
mean,0.000047,0.822499,0.003091,0.041024,0.132628,0.000711,0.000012,0.002463,0.054584,0.042433,...,23.676630,8981.506816,0.216961,5.243335,1.546501,39.772510,1.387901,0.000071,0.158529,0.037518
std,0.006883,0.382094,0.055511,0.198346,0.339175,0.026647,0.003441,0.049571,0.227167,0.201576,...,16.034245,2851.634048,0.412179,4.958819,0.716112,54.965824,0.568593,0.008429,0.526090,0.199811
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,-2.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9.000000,7924.000000,0.000000,2.000000,1.000000,6.000000,1.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,15.000000,9482.000000,0.000000,4.000000,1.000000,17.000000,1.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,40.000000,10539.000000,0.000000,7.000000,2.000000,46.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13186.000000,1.000000,96.000000,4.000000,298.000000,4.000000,1.000000,4.000000,3.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

RoomTypes_desc_2        0.270348
RoomTypes_desc_7        0.465910
RoomTypes_desc_8        0.598804
source_1                0.485644
source_3                0.246067
source_7                0.339966
source_8                0.362200
sales_channel_4         0.382864
sales_channel_6         0.245720
club_code_0             0.311833
club_code_6             0.275784
package_code_0          0.276498
market_segment_bi_id    0.484323
bed_nights              0.597265
adults                  0.435190
children                0.342748
ARR                     1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

plan_desc_1             0.205531
RoomTypes_desc_2        0.250231
RoomTypes_desc_7        0.374355
RoomTypes_desc_8        0.580237
source_1                0.499220
source_3                0.277788
source_7                0.338186
source_8                0.384598
sales_channel_4         0.345959
sales_channel_6         0.277345
club_code_0             0.310598
club_code_6             0.276406
package_code_0          0.297804
nationality_49          0.215548
market_segment_bi_id    0.442413
bed_nights              0.624499
adults                  0.500704
children                0.351435
ARR                     1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -6.822765521548065e+24
CV STD Accuracy:  1.0741978601122806e+25

Train Accuracy:  0.7284309955106241
Test Accuracy:  -1.1287777960678373e+23

plan_desc_0 --> -1574034491566.67
plan_desc_1 --> -87384436319020.11
plan_desc_2 --> -12695287791959.88
plan_desc_3 --> -45361500836277.31
plan_desc_4 --> -77568748644188.47
plan_desc_5 --> -6094187436092.37
RoomTypes_desc_0 --> 1293489174824.80
RoomTypes_desc_1 --> 18632085793324.70
RoomTypes_desc_2 --> 85384737606877.69
RoomTypes_desc_3 --> 75765825580600.31
RoomTypes_desc_4 --> 137823880472888.06
RoomTypes_desc_5 --> 12264647010019.50
RoomTypes_desc_6 --> 43415175559360.29
RoomTypes_desc_7 --> 96143617272354.66
RoomTypes_desc_8 --> 178621915605296.03
RoomTypes_desc_9 --> 1293489174819.69
source_0 --> 769507502970.96
source_1 --> 108651766425745.81
source_2 --> 42755006308642.98
source_3 --> 79345411036371.27
source_4 --> 11424639062711.67
source_5 --> 7376878382515.14
source_6 --> 42543240041764.80
source_7 --> 75996231108038.98
source_8 --> 91498256573786.25
source_9 --> 819946500424135.25
source_10 --> 25160921976120.13
sales_channel_0 --> 757427852225579.62
sales_channel_1 --> 242989686654437.41
sales_channel_2 --> 190735329635457.91
sales_channel_3 --> -487767105954664.62
sales_channel_4 --> 443764359931375.75
sales_channel_5 --> 78960863594732.42
sales_channel_6 --> 589354251963333.88
club_code_0 --> -149669839640619.53
club_code_1 --> -5545987628249.38
club_code_2 --> -13291326205393.61
club_code_3 --> -76159488143629.22
club_code_4 --> -4113233746399.36
club_code_5 --> -30372109053853.27
club_code_6 --> -134037658590931.88
StatisticSource_0 --> -376296401772144.62
package_code_0 --> -784319268725867.88
package_code_1 --> -13177320530079.67
package_code_2 --> -72748701494299.34
package_code_3 --> -9317827880410.24
package_code_4 --> -40611140788853.07
package_code_5 --> 39759248414882.31
package_code_6 --> -44680910819256.34
package_code_7 --> -315168249994398.25
package_code_8 --> -420970422232761.31
package_code_9 --> -93123638979249.75
package_code_10 --> -149438537309533.00
package_code_11 --> -98984156513110.55
package_code_12 --> -20834803032189.50
package_code_13 --> -13177320530077.96
package_code_14 --> -16138760170178.58
package_code_15 --> -49297427067725.34
package_code_16 --> -193394810429287.81
package_code_17 --> -279870146850479.62
package_code_18 --> -72150364105980.25
package_code_19 --> -110159243316520.38
package_code_20 --> -32275800070422.10
package_code_21 --> -74514809372055.72
package_code_22 --> -37268000841003.14
package_code_23 --> -39528215949395.91
package_code_24 --> -20834803032185.85
package_code_25 --> -29463988581711.14
package_code_26 --> -9317827880412.76
package_code_27 --> -163229668500092.81
package_code_28 --> -316104472498973.88
package_code_29 --> -256050867297451.38
package_code_30 --> -13177320530080.27
package_code_31 --> -41665904523197.76
package_code_32 --> -18635324704519.56
package_code_33 --> -16138760170181.69
nationality_0 --> 5179338269836.46
nationality_1 --> 2512541517754.92
nationality_2 --> 3553186123620.22
nationality_3 --> 16507117337940.80
nationality_4 --> 5891804053104.99
nationality_5 --> 34070530493318.23
nationality_6 --> 26283632941281.44
nationality_7 --> 4166406025667.50
nationality_8 --> 36463532888863.84
nationality_9 --> 15876021399254.56
nationality_10 --> 2512541517753.31
nationality_11 --> 7536196076657.66
nationality_12 --> 3768700685820.15
nationality_13 --> 2809090180217.71
nationality_14 --> 30638044551641.02
nationality_15 --> 3553186123619.69
nationality_16 --> 42148498369740.56
nationality_17 --> 38623352440990.47
nationality_18 --> 12366016227659.48
nationality_19 --> 59836587028233.53
nationality_20 --> 3323720959394.42
nationality_21 --> 4166406025670.14
nationality_22 --> 2512541517756.10
nationality_23 --> 18440140525045.55
nationality_24 --> 9646455466218.69
nationality_25 --> 14957955230771.64
nationality_26 --> 15876021399252.98
nationality_27 --> 62853291872004.67
nationality_28 --> 16507117337940.98
nationality_29 --> 3553186123620.67
nationality_30 --> 36442320644838.50
nationality_31 --> 5891804053097.12
nationality_32 --> 14585219593537.56
nationality_33 --> 86830426967326.64
nationality_34 --> 2809090180213.12
nationality_35 --> 99304899982238.62
nationality_36 --> 7215486642507.45
nationality_37 --> 4166406025670.66
nationality_38 --> 6153715735546.50
nationality_39 --> 19755165472163.97
nationality_40 --> 2175937667603.28
nationality_41 --> 3768700685818.62
nationality_42 --> 17965637813520.77
nationality_43 --> 2809090180215.58
nationality_44 --> 14367858378966.77
nationality_45 --> 8425274124775.47
nationality_46 --> 60047981194110.86
nationality_47 --> 27980582576711.66
nationality_48 --> 4351643396691.89
nationality_49 --> 164343313480908.44
nationality_50 --> 51318810507860.31
nationality_51 --> 2512541517752.97
nationality_52 --> 1256293076512.05
nationality_53 --> 5179338269835.21
nationality_54 --> 33910857590807.68
nationality_55 --> 18609657400435.82
nationality_56 --> 5329463546804.25
nationality_57 --> 41524241709067.30
nationality_58 --> 2512541517752.36
nationality_59 --> 2512541517754.96
nationality_60 --> 3553186123619.93
nationality_61 --> 6153715735545.46
nationality_62 --> 5756376268865.88
nationality_63 --> 11911959855892.06
nationality_64 --> 3323720959389.80
nationality_65 --> 3077185892944.59
nationality_66 --> 1776656186545.64
nationality_67 --> 5617681293417.06
nationality_68 --> 34455116369289.91
nationality_69 --> 5617681293411.36
nationality_70 --> 3323720959391.09
nationality_71 --> 2512541517753.00
nationality_72 --> 3972535803051.71
nationality_73 --> 2175937667604.12
nationality_74 --> 1776656186546.70
nationality_75 --> 3077185892942.78
nationality_76 --> 1776656186543.93
nationality_77 --> 6646615188628.84
nationality_78 --> 36442320644847.15
nationality_79 --> 15676687072678.80
nationality_80 --> 3972535803048.63
nationality_81 --> 14531186036174.28
nationality_82 --> 11370759834682.80
nationality_83 --> 5024725937509.38
nationality_84 --> 11090219918074.11
nationality_85 --> 13047505848519.37
nationality_86 --> 2809090180217.84
nationality_87 --> 24972696565255.34
nationality_88 --> 3768700685816.50
nationality_89 --> 14035466455305.22
nationality_90 --> 3768700685816.95
nationality_91 --> 1776656186544.91
nationality_92 --> 16976492304033.41
nationality_93 --> 14202640766118.70
nationality_94 --> 73498684641235.83
nationality_95 --> 6646615188630.43
nationality_96 --> 1256293076511.91
nationality_97 --> 2175937667604.16
nationality_98 --> 16883670110044.12
nationality_99 --> 2175937667604.53
nationality_100 --> 8701431037925.12
nationality_101 --> 3077185892946.92
nationality_102 --> 11644517271102.04
nationality_103 --> 6646615188624.16
nationality_104 --> 18567424784870.61
nationality_105 --> 5329463546805.75
nationality_106 --> 12555563851423.40
nationality_107 --> 4529307226302.62
nationality_108 --> 3323720959396.83
nationality_109 --> 19026774469116.95
nationality_110 --> 7640103259278.52
nationality_111 --> 40701382162162.34
nationality_112 --> 4166406025668.86
nationality_113 --> 154178090343413.31
nationality_114 --> 70626639411408.22
nationality_115 --> 5891804053100.21
nationality_116 --> 10431351197540.93
nationality_117 --> 32051759143109.90
market_segment_bi_id --> -103.69
MainCust --> 15.75
group_member --> -79.12
m_length_of_stay --> -24.98
bed_nights --> 104274146903077.78
m_lead_days --> 36.88
adults --> -82793775058573.25
juniors --> -1227402648517.83
children --> -76604735803391.17
babies --> 12.16
Model: ridge_regressor
CV Mean Accuracy:  0.7266237837429372
CV STD Accuracy:  0.0027656299689838323

Train Accuracy:  0.7285090421037407
Test Accuracy:  0.7296948702885877

Model: lasso_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 22234553.032776833, tolerance: 2250510.1929754675
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 114454577.19349003, tolerance: 1802032.7423921414
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 58720793.06854105, tolerance: 1802221.3968028047
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3631869.7291202545, tolerance: 1807407.2011699562
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 17758045.35491371, tolerance: 1804748.7973593515
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 27741169.912236214, tolerance: 1785549.8460911491
  positive)

CV Mean Accuracy:  0.7266867111362257
CV STD Accuracy:  0.002763304577708787

Train Accuracy:  0.7285018745538301
Test Accuracy:  0.7297093228232625

Model: elasticnet_regressor
CV Mean Accuracy:  0.7072285270330498
CV STD Accuracy:  0.0025832222045337277

Train Accuracy:  0.7083557271171494
Test Accuracy:  0.7088931842220707

Model: supportvect_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

CV Mean Accuracy:  0.714920293413808
CV STD Accuracy:  0.00284196886767916

Train Accuracy:  0.7176865102451898
Test Accuracy:  0.7184778787463924

Model: decisiontree_regressor
CV Mean Accuracy:  0.8719860202288547
CV STD Accuracy:  0.002791660334560993

Train Accuracy:  0.9650538600916635
Test Accuracy:  0.8837544509127038

Model: randomforest_regressor
CV Mean Accuracy:  0.5850621402120594
CV STD Accuracy:  0.016499830438439025

Train Accuracy:  0.5812991154771514
Test Accuracy:  0.5809099589550002

Model: xgboost_regressor
CV Mean Accuracy:  0.8004988793022149
CV STD Accuracy:  0.001593093244804742

Train Accuracy:  0.8033699116799536
Test Accuracy:  0.8023848970897992

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -1.8192244572821996e+35
CV STD Accuracy:  3.365983793260541e+35

Train Accuracy:  0.9032360160548469
Test Accuracy:  -2.3141439409653495e+35

                        train_accuracy  test_accuracy
linear_regressor                0.7284         0.0000
ridge_regressor                 0.7285         0.7297
lasso_regressor                 0.7285         0.7297
elasticnet_regressor            0.7084         0.7089
supportvect_regressor           0.7177         0.7185
decisiontree_regressor          0.9651         0.8838
randomforest_regressor          0.5813         0.5809
xgboost_regressor               0.8034         0.8024
mlp_regressor                   0.9032         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 547.0

reservations_df shape: (151070, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-10-15,bed & breakfast,executive seaview,4.0,1745.0,t.a.,,,,,usa,0.0,1.0,2.0,55.0,2.0,0.0,0.0,0.0,1321.30
2018-10-16,bb+lounge,deluxe room,40.0,10037.0,co,,,,,usa,0.0,3.0,1.0,54.0,1.0,0.0,0.0,0.0,861.40
2018-10-14,bb+lounge,deluxe room,40.0,10037.0,co,,,,,usa,0.0,3.0,1.0,54.0,1.0,0.0,0.0,0.0,861.40
2018-10-15,bb+lounge,deluxe room,40.0,10037.0,co,,,,,usa,0.0,3.0,1.0,54.0,1.0,0.0,0.0,0.0,861.40
2018-10-16,bed & breakfast,deluxe room,4.0,2865.0,ot,booking.com,,,,mex,0.0,5.0,2.0,55.0,2.0,0.0,0.0,0.0,1535.31

<class 'pandas.core.frame.DataFrame'>
Index: 151070 entries, 2018-10-15 to 2019-06-25
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   plan_desc             151070 non-null  object
 1   RoomTypes_desc        151070 non-null  object
 2   market_segment_bi_id  151070 non-null  float64
 3   MainCust              151070 non-null  float64
 4   source                151070 non-null  object
 5   sales_channel         151070 non-null  object
 6   club_code             151070 non-null  object
 7   StatisticSource       151070 non-null  object
 8   package_code          151070 non-null  object
 9   nationality           151070 non-null  object
 10  group_member          151070 non-null  float64
 11  m_length_of_stay      151070 non-null  float64
 12  bed_nights            151070 non-null  float64
 13  m_lead_days           151070 non-null  float64
 14  adults                151070 non-null  float64
 15  juniors               151070 non-null  float64
 16  children              151070 non-null  float64
 17  babies                151070 non-null  float64
 18  ARR                   151070 non-null  float64
dtypes: float64(11), object(8)
memory usage: 23.1+ MB
(151070, 225)

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,plan_desc_7,plan_desc_8,RoomTypes_desc_0,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-10-15,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,1745.0,0.0,1.0,2.0,55.0,2.0,0.0,0.0,0.0
2018-10-16,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40.0,10037.0,0.0,3.0,1.0,54.0,1.0,0.0,0.0,0.0
2018-10-14,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40.0,10037.0,0.0,3.0,1.0,54.0,1.0,0.0,0.0,0.0
2018-10-15,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40.0,10037.0,0.0,3.0,1.0,54.0,1.0,0.0,0.0,0.0
2018-10-16,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,2865.0,0.0,5.0,2.0,55.0,2.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,plan_desc_7,plan_desc_8,RoomTypes_desc_0,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000,...,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000,151070.000000
mean,0.195591,0.498808,0.000053,0.001807,0.000046,0.013888,0.067273,0.002224,0.220308,0.004362,...,21.845198,8367.407698,0.455014,4.738260,1.406097,42.050261,1.308049,0.000040,0.098008,0.023459
std,0.396657,0.500000,0.007277,0.042472,0.006807,0.117025,0.250496,0.047108,0.414456,0.065903,...,14.470534,3201.604784,0.497974,9.006432,0.661832,56.168395,0.538008,0.008136,0.418740,0.158702
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,388.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9.000000,7464.000000,0.000000,2.000000,1.000000,10.000000,1.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,19.000000,8273.000000,0.000000,3.000000,1.000000,22.000000,1.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,40.000000,10631.000000,1.000000,5.000000,2.000000,41.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13080.000000,1.000000,180.000000,4.000000,299.000000,4.000000,2.000000,3.000000,2.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

plan_desc_8             0.340948
RoomTypes_desc_4        0.428382
RoomTypes_desc_6        0.252682
RoomTypes_desc_10       0.569789
source_1                0.479594
source_7                0.260841
source_9                0.221695
sales_channel_0         0.360842
sales_channel_1         0.236379
sales_channel_4         0.277199
nationality_25          0.254925
market_segment_bi_id    0.300262
group_member            0.443004
bed_nights              0.515407
adults                  0.449843
children                0.236666
ARR                     1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

plan_desc_8             0.400803
RoomTypes_desc_4        0.449518
RoomTypes_desc_10       0.592780
source_1                0.522269
source_7                0.269147
source_9                0.269862
sales_channel_0         0.348124
sales_channel_1         0.222544
sales_channel_4         0.258414
nationality_25          0.292455
market_segment_bi_id    0.319747
group_member            0.469319
m_length_of_stay        0.258281
bed_nights              0.521298
adults                  0.471419
children                0.238673
ARR                     1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -8.303202010248019e+24
CV STD Accuracy:  7.975417075743825e+24

Train Accuracy:  0.6312537407583593
Test Accuracy:  -9.681066879436921e+22

plan_desc_0 --> -189683431857554.78
plan_desc_1 --> -239102930820291.97
plan_desc_2 --> -3479849870172.06
plan_desc_3 --> -20310264229000.78
plan_desc_4 --> -3255112266935.89
plan_desc_5 --> -55961966248896.31
plan_desc_6 --> -119788505383327.31
plan_desc_7 --> -22527507858115.71
plan_desc_8 --> -198195199445986.88
RoomTypes_desc_0 --> 31804697755085.42
RoomTypes_desc_1 --> 185524119718069.97
RoomTypes_desc_2 --> 14096368124393.07
RoomTypes_desc_3 --> 57148514478190.84
RoomTypes_desc_4 --> 176549201893761.03
RoomTypes_desc_5 --> 19655027478875.20
RoomTypes_desc_6 --> 57514204978776.42
RoomTypes_desc_7 --> 4301017942977.01
RoomTypes_desc_8 --> 2776359469912.39
RoomTypes_desc_9 --> 61250857522068.38
RoomTypes_desc_10 --> 236782701859447.19
RoomTypes_desc_11 --> 7653058818758.66
RoomTypes_desc_12 --> 52550278538172.12
source_0 --> 41151067635612.72
source_1 --> 442715772032562.31
source_2 --> 70396928940748.31
source_3 --> 219117698889885.09
source_4 --> 29721893978820.19
source_5 --> 39615315098856.87
source_6 --> 46622747915581.49
source_7 --> 234659868491104.34
source_8 --> 253037313290455.69
source_9 --> 367202547746104.56
source_10 --> 163565008525658.34
source_11 --> 48996920049896.48
sales_channel_0 --> -49619997259093.62
sales_channel_1 --> -21765480249670.43
sales_channel_2 --> -21464311263368.06
sales_channel_3 --> -22444901529479.25
sales_channel_4 --> -24453973618030.79
sales_channel_5 --> -9453849220312.14
sales_channel_6 --> -29687636181750.40
sales_channel_7 --> -1197277293048.41
club_code_0 --> 145245856674845.81
club_code_1 --> 5263996600860.18
club_code_2 --> 12596362732414.12
club_code_3 --> 69014689538155.56
club_code_4 --> 1788226871934.21
club_code_5 --> 20698495562247.72
club_code_6 --> 130727146786533.77
StatisticSource_0 --> 427117919595826.25
StatisticSource_1 --> 406272868785179.31
StatisticSource_2 --> 131819741467557.19
package_code_0 --> -409424374370149.69
package_code_1 --> -20493093319268.50
package_code_2 --> -25098561720178.08
package_code_3 --> -16732651392028.96
package_code_4 --> -30164317700183.76
package_code_5 --> -247464694367455.31
package_code_6 --> -39239207948523.75
package_code_7 --> -33463973591490.61
package_code_8 --> -131911295023048.12
package_code_9 --> -8366408768489.11
package_code_10 --> -75277738981608.75
package_code_11 --> -30164317700181.06
package_code_12 --> -71953178528790.28
package_code_13 --> -191002169266427.50
package_code_14 --> -88509213269080.17
package_code_15 --> -31302888222585.62
package_code_16 --> -11831849588144.58
package_code_17 --> -20493093319266.45
package_code_18 --> -23663229243524.93
package_code_19 --> -14490949140241.94
package_code_20 --> -165852321385225.91
package_code_21 --> -16732651392025.30
nationality_0 --> -1514939675570.82
nationality_1 --> -11435423633153.40
nationality_2 --> -7724067770782.55
nationality_3 --> -2623935119200.37
nationality_4 --> -3710767786231.46
nationality_5 --> -35076254802481.47
nationality_6 --> -10602892869195.55
nationality_7 --> -4544698687552.94
nationality_8 --> -1514939675570.46
nationality_9 --> -45537394703057.31
nationality_10 --> -41109893444258.73
nationality_11 --> -26430650272708.48
nationality_12 --> -41357892445636.29
nationality_13 --> -2142441144398.82
nationality_14 --> -17331814992052.51
nationality_15 --> -2623935119202.19
nationality_16 --> -14126393968461.03
nationality_17 --> -3387463248928.53
nationality_18 --> -62595954598530.97
nationality_19 --> -5461975733563.98
nationality_20 --> -2623935119202.24
nationality_21 --> -2623935119199.56
nationality_22 --> -71307383234649.53
nationality_23 --> -58111172529092.02
nationality_24 --> -21833796613845.29
nationality_25 --> -144515185241874.19
nationality_26 --> -6059457850893.45
nationality_27 --> -2142441144398.79
nationality_28 --> -3710767786230.80
nationality_29 --> -21087185005290.80
nationality_30 --> -18544993707226.07
nationality_31 --> -1514939675571.54
nationality_32 --> -3029849266600.25
nationality_33 --> -18911881015399.77
nationality_34 --> -26816975143505.09
nationality_35 --> -110845058952384.03
nationality_36 --> -15144432017499.21
nationality_37 --> -32124458321495.80
nationality_38 --> -6941866174706.15
nationality_39 --> -7871180036278.10
nationality_40 --> -2623935119201.16
nationality_41 --> -56600136744758.94
nationality_42 --> -8961495367747.94
nationality_43 --> -14045019663848.52
nationality_44 --> -42894603343392.38
nationality_45 --> -151251001707024.94
nationality_46 --> -3387463248929.81
nationality_47 --> -119209779935917.44
nationality_48 --> -14126393968458.37
nationality_49 --> -18421067591634.45
nationality_50 --> -5668141330480.41
nationality_51 --> -3029849266601.15
nationality_52 --> -28025298702936.07
nationality_53 --> -7421093403509.90
nationality_54 --> -123026590829799.45
nationality_55 --> -10494177119159.94
nationality_56 --> -18606646022801.87
nationality_57 --> -17528973315808.45
nationality_58 --> -13028854787408.18
nationality_59 --> -2142441144399.66
nationality_60 --> -57956088087611.88
nationality_61 --> -28106699877505.73
nationality_62 --> -3029849266599.20
nationality_63 --> -6245925513723.69
nationality_64 --> -217475883397090.78
nationality_65 --> -83938635121553.81
nationality_66 --> -12581201544268.57
nationality_67 --> -5461975733562.91
nationality_68 --> -48102308491069.66
nationality_69 --> -20313003545776.55
nationality_70 --> -9088585038709.59
nationality_71 --> -4284797196160.42
nationality_72 --> -17723930902530.47
nationality_73 --> -2142441144398.81
nationality_74 --> -15665159105294.73
nationality_75 --> -13461601771129.04
nationality_76 --> -14761210867754.88
nationality_77 --> -9580082947679.43
nationality_78 --> -4008074036217.45
nationality_79 --> -6774590131325.33
nationality_80 --> -10273290353217.24
nationality_81 --> -14045019663850.09
nationality_82 --> -7105203033242.74
nationality_83 --> -3387463248929.36
nationality_84 --> -30371710811911.28
nationality_85 --> -2623935119202.21
nationality_86 --> -10047542705487.61
nationality_87 --> -1514939675570.84
nationality_88 --> -1514939675571.23
nationality_89 --> -2623935119201.75
nationality_90 --> -51375905642454.69
nationality_91 --> -6245925513723.05
nationality_92 --> -10817042739044.54
nationality_93 --> -52614884324695.57
nationality_94 --> -15810779919719.57
nationality_95 --> -15518167945426.61
nationality_96 --> -69535309566556.98
nationality_97 --> -10922541199444.60
nationality_98 --> -11732380556007.15
nationality_99 --> -17723930902524.51
nationality_100 --> -6426983057012.89
nationality_101 --> -28429952604677.42
nationality_102 --> -2142441144396.98
nationality_103 --> -4284797196160.43
nationality_104 --> -28147311376681.41
nationality_105 --> -3029849266598.74
nationality_106 --> -30633637749775.67
nationality_107 --> -27656001439308.12
nationality_108 --> -97618627900595.31
nationality_109 --> -7574096666115.64
nationality_110 --> -3387463248928.59
nationality_111 --> -8701744107625.89
nationality_112 --> -23885714888694.48
nationality_113 --> -2142441144398.92
nationality_114 --> -18296298786749.50
nationality_115 --> -9932742758724.62
nationality_116 --> -12489742038595.84
nationality_117 --> -19683262017510.48
nationality_118 --> -36942315914948.45
nationality_119 --> -13116548740965.19
nationality_120 --> -3710767786230.53
nationality_121 --> -3710767786229.54
nationality_122 --> -17199116138347.08
nationality_123 --> -1514939675570.32
nationality_124 --> -7574096666114.59
nationality_125 --> -6774590131324.40
nationality_126 --> -29417018992099.64
nationality_127 --> -23353011108180.27
nationality_128 --> -35399565531704.53
nationality_129 --> -2142441144397.15
nationality_130 --> -15955067909893.53
nationality_131 --> -279683701296327.38
nationality_132 --> -8568913617425.52
nationality_133 --> -12489742038599.94
nationality_134 --> -21303187086003.17
nationality_135 --> -5024320183405.78
nationality_136 --> -2142441144399.28
nationality_137 --> -2142441144398.66
nationality_138 --> -36973120075491.95
nationality_139 --> -19212247428737.55
nationality_140 --> -3710767786231.36
market_segment_bi_id --> -44.72
MainCust --> 37.68
group_member --> -25.03
m_length_of_stay --> -20.55
bed_nights --> 426680887925190.50
m_lead_days --> 14.88
adults --> -346852212121705.06
juniors --> -5245210268665.61
children --> -269960386704013.84
babies --> 1.65

Model: ridge_regressor
CV Mean Accuracy:  0.6293881593129482
CV STD Accuracy:  0.0061959578295477085

Train Accuracy:  0.631287736077311
Test Accuracy:  0.6253916868432445

Model: lasso_regressor
CV Mean Accuracy:  0.6294084454754764
CV STD Accuracy:  0.006167181505187181

Train Accuracy:  0.6312584828606442
Test Accuracy:  0.6254361852841532

Model: elasticnet_regressor
CV Mean Accuracy:  0.6035056112146379
CV STD Accuracy:  0.00501308675045648

Train Accuracy:  0.6045849044157213
Test Accuracy:  0.5991819879379081

Model: supportvect_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

CV Mean Accuracy:  0.602810466181338
CV STD Accuracy:  0.007255789474048617

Train Accuracy:  0.6054987751509394
Test Accuracy:  0.5976133775466814

Model: decisiontree_regressor
CV Mean Accuracy:  0.8034175345889505
CV STD Accuracy:  0.0024207625136399833

Train Accuracy:  0.925266142127887
Test Accuracy:  0.8120739603527021

Model: randomforest_regressor
CV Mean Accuracy:  0.4465482121144729
CV STD Accuracy:  0.0035705966673404356

Train Accuracy:  0.4464250005040931
Test Accuracy:  0.44736635608804703

Model: xgboost_regressor
CV Mean Accuracy:  0.7218334597297313
CV STD Accuracy:  0.005605496731694304

Train Accuracy:  0.7253824499287826
Test Accuracy:  0.7184562622828651

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -6.009455908474674e+35
CV STD Accuracy:  6.695540546015007e+35

Train Accuracy:  0.8474766120516164
Test Accuracy:  -2.1916778402576824e+35

                        train_accuracy  test_accuracy
linear_regressor                0.6313         0.0000
ridge_regressor                 0.6313         0.6254
lasso_regressor                 0.6313         0.6254
elasticnet_regressor            0.6046         0.5992
supportvect_regressor           0.6055         0.5976
decisiontree_regressor          0.9253         0.8121
randomforest_regressor          0.4464         0.4474
xgboost_regressor               0.7254         0.7185
mlp_regressor                   0.8475         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 548.0

reservations_df shape: (271056, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-10-04,breakfast board,tel aviv room,14.0,7669.0,co,,,,,usa,0.0,405.0,1.0,1.0,1.0,0.0,0.0,0.0,934.4
2018-10-06,breakfast board,tel aviv room,14.0,7669.0,co,,,,,usa,0.0,405.0,1.0,1.0,1.0,0.0,0.0,0.0,934.4
2018-10-11,breakfast board,tel aviv room,14.0,7669.0,co,,,,,usa,0.0,405.0,1.0,1.0,1.0,0.0,0.0,0.0,934.4
2018-10-03,breakfast board,tel aviv room,14.0,7669.0,co,,,,,usa,0.0,405.0,1.0,1.0,1.0,0.0,0.0,0.0,467.2
2018-10-10,breakfast board,tel aviv room,14.0,7669.0,co,,,,,usa,0.0,405.0,1.0,1.0,1.0,0.0,0.0,0.0,934.4

<class 'pandas.core.frame.DataFrame'>
Index: 271056 entries, 2018-10-04 to 2019-06-30
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   plan_desc             271056 non-null  object
 1   RoomTypes_desc        271056 non-null  object
 2   market_segment_bi_id  271056 non-null  float64
 3   MainCust              271056 non-null  float64
 4   source                271056 non-null  object
 5   sales_channel         271056 non-null  object
 6   club_code             271056 non-null  object
 7   StatisticSource       271056 non-null  object
 8   package_code          271056 non-null  object
 9   nationality           271056 non-null  object
 10  group_member          271056 non-null  float64
 11  m_length_of_stay      271056 non-null  float64
 12  bed_nights            271056 non-null  float64
 13  m_lead_days           271056 non-null  float64
 14  adults                271056 non-null  float64
 15  juniors               271056 non-null  float64
 16  children              271056 non-null  float64
 17  babies                271056 non-null  float64
 18  ARR                   271056 non-null  float64
dtypes: float64(11), object(8)
memory usage: 41.4+ MB
(271056, 263)

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,plan_desc_7,plan_desc_8,plan_desc_9,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-10-04,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,7669.0,0.0,405.0,1.0,1.0,1.0,0.0,0.0,0.0
2018-10-06,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,7669.0,0.0,405.0,1.0,1.0,1.0,0.0,0.0,0.0
2018-10-11,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,7669.0,0.0,405.0,1.0,1.0,1.0,0.0,0.0,0.0
2018-10-03,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,7669.0,0.0,405.0,1.0,1.0,1.0,0.0,0.0,0.0
2018-10-10,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,7669.0,0.0,405.0,1.0,1.0,1.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,plan_desc_7,plan_desc_8,plan_desc_9,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000,...,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000,271056.000000
mean,0.029522,0.579766,0.000077,0.000819,0.000764,0.001915,0.000004,0.000679,0.005453,0.000365,...,25.270025,7990.912494,0.516672,6.277467,1.394015,61.246005,1.326626,0.000107,0.067281,0.015624
std,0.169264,0.493597,0.008802,0.028607,0.027624,0.043716,0.001921,0.026046,0.073641,0.019108,...,15.011255,3277.736744,0.499723,18.106415,0.602906,74.416451,0.547628,0.011033,0.341235,0.128027
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,388.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,13.000000,5153.000000,0.000000,2.000000,1.000000,11.000000,1.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,26.000000,9324.000000,1.000000,3.000000,1.000000,25.000000,1.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,40.000000,10101.000000,1.000000,6.000000,2.000000,86.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13109.000000,1.000000,405.000000,7.000000,299.000000,4.000000,2.000000,3.000000,2.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

source_1                0.279915
source_8                0.229378
sales_channel_0         0.354129
sales_channel_1         0.206638
sales_channel_5         0.279807
market_segment_bi_id    0.323794
group_member            0.301284
bed_nights              0.386403
adults                  0.352269
ARR                     1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

source_1                0.309479
source_8                0.244877
sales_channel_0         0.351901
sales_channel_1         0.210598
sales_channel_5         0.270874
market_segment_bi_id    0.303663
group_member            0.307047
bed_nights              0.408318
adults                  0.382284
ARR                     1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -7.385474598324868e+25
CV STD Accuracy:  8.301293634227386e+25

Train Accuracy:  0.40019714188279665
Test Accuracy:  -1.9774878795652485e+26

plan_desc_0 --> -178282369094515.62
plan_desc_1 --> -519897448223311.81
plan_desc_2 --> -9270624781509.88
plan_desc_3 --> -30131083376148.38
plan_desc_4 --> -29096145442718.81
plan_desc_5 --> -46045127705652.06
plan_desc_6 --> -2023090820016.91
plan_desc_7 --> -27433273716035.30
plan_desc_8 --> -77565055664931.64
plan_desc_9 --> -20125860258778.38
plan_desc_10 --> -249691729900218.00
plan_desc_11 --> -440135638321900.56
plan_desc_12 --> -4046159248679.61
plan_desc_13 --> -34374267787627.65
plan_desc_14 --> -75742556746815.80
plan_desc_15 --> -34255245698423.41
plan_desc_16 --> -51989326089678.96
plan_desc_17 --> -8341170946383.13
plan_desc_18 --> -294660481942676.06
RoomTypes_desc_0 --> -5981004843240.52
RoomTypes_desc_1 --> -98146591229486.94
RoomTypes_desc_2 --> -79721740137207.62
RoomTypes_desc_3 --> -1924154577628.44
RoomTypes_desc_4 --> -7265102166918.75
RoomTypes_desc_5 --> -702618760188.72
RoomTypes_desc_6 --> -116426148577350.42
RoomTypes_desc_7 --> -3815795404992.27
source_0 --> 12927954719878.76
source_1 --> 676755838275641.38
source_2 --> 48119816867389.82
source_3 --> 252270371902114.19
source_4 --> 285288647858138.88
source_5 --> 6027890122387.30
source_6 --> 35034203821024.77
source_7 --> 14006982357335.52
source_8 --> 367277443907995.50
source_9 --> 308779913510340.00
source_10 --> 687023884394594.25
source_11 --> 69066826678607.78
source_12 --> 225411370141872.31
source_13 --> 57391588532877.25
sales_channel_0 --> 200386335567792.38
sales_channel_1 --> 96227525373092.06
sales_channel_2 --> 3647051467389.48
sales_channel_3 --> 84171200362366.23
sales_channel_4 --> 80939110702534.27
sales_channel_5 --> 110919814687580.31
sales_channel_6 --> 45317403612530.44
sales_channel_7 --> 103057926055886.50
club_code_0 --> 1108594334587047.00
club_code_1 --> 66736551306175.84
club_code_2 --> 93242742959095.66
club_code_3 --> 490660397579178.69
club_code_4 --> 17152963938106.63
club_code_5 --> 396176031011539.00
club_code_6 --> 947575106757023.75
StatisticSource_0 --> -158568300679676.06
StatisticSource_1 --> -157781647522275.53
StatisticSource_2 --> -15781046946485.74
package_code_0 --> 27971235561918.59
package_code_1 --> 1611096043052.15
package_code_2 --> 12842085102418.48
package_code_3 --> 1701497645141.18
package_code_4 --> 8652890961128.70
package_code_5 --> 4342451988132.68
package_code_6 --> 1869224946031.33
package_code_7 --> 4544382360684.11
package_code_8 --> 3983150667170.73
package_code_9 --> 4399476273516.69
package_code_10 --> 1413040344954.78
package_code_11 --> 3237174443441.01
package_code_12 --> 4069833151536.33
package_code_13 --> 3283075929559.08
package_code_14 --> 1263871032627.22
package_code_15 --> 1223740122763.77
package_code_16 --> 1671907208632.45
package_code_17 --> 1921882382682.89
package_code_18 --> 1641783315619.89
package_code_19 --> 2997124123996.14
package_code_20 --> 10150885256671.43
package_code_21 --> 2487721484911.15
package_code_22 --> 8390699448447.23
package_code_23 --> 6179423066802.20
package_code_24 --> 5208612227567.99
package_code_25 --> 773974060114.64
package_code_26 --> 3474972047745.96
package_code_27 --> 1413040344952.80
package_code_28 --> 446857429150.71
package_code_29 --> 547285335039.83
package_code_30 --> 547285335041.55
package_code_31 --> 4307874081465.14
package_code_32 --> 773974060116.69
package_code_33 --> 4261332565250.26
package_code_34 --> 5506158425706.38
package_code_35 --> 6584934360319.30
package_code_36 --> 6945286750937.66
nationality_0 --> -13143226757366.76
nationality_1 --> -50429818642314.52
nationality_2 --> -17956635687256.84
nationality_3 --> -13991981736391.07
nationality_4 --> -15551103491538.56
nationality_5 --> -171652995520608.81
nationality_6 --> -20075869761266.07
nationality_7 --> -8978665669355.25
nationality_8 --> -4799342940782.69
nationality_9 --> -177314692935499.56
nationality_10 --> -95546356311167.95
nationality_11 --> -52986805973466.38
nationality_12 --> 1638735710746776.75
nationality_13 --> -103204269795219.39
nationality_14 --> -66627357567767.58
nationality_15 --> -7588385488446.86
nationality_16 --> -17956635687256.72
nationality_17 --> -70398185863381.59
nationality_18 --> -6787270836905.93
nationality_19 --> -4799342940781.35
nationality_20 --> -53418963991435.65
nationality_21 --> -234430386539057.75
nationality_22 --> -5877959809957.84
nationality_23 --> -22251954609389.49
nationality_24 --> -6787270836904.36
nationality_25 --> -219523698132121.00
nationality_26 --> -116371103403685.98
nationality_27 --> -240848497920543.69
nationality_28 --> -304033537140459.56
nationality_29 --> -26933214312408.51
nationality_30 --> -26718652904446.71
nationality_31 --> -7588385488445.84
nationality_32 --> -105992228188108.53
nationality_33 --> -4799342940782.51
nationality_34 --> -41134787651375.92
nationality_35 --> -6787270836905.70
nationality_36 --> -42374606417973.62
nationality_37 --> -93792529747280.41
nationality_38 --> -360167631701895.88
nationality_39 --> -74977459074753.73
nationality_40 --> -73196060158540.50
nationality_41 --> -5877959809958.35
nationality_42 --> -45134972030108.73
nationality_43 --> -199696072036602.06
nationality_44 --> -34267841145686.36
nationality_45 --> -34099510711558.72
nationality_46 --> -126425607709204.78
nationality_47 --> -3393654198756.24
nationality_48 --> -341287378994824.81
nationality_49 --> -378947290907294.75
nationality_50 --> -33930343938301.45
nationality_51 --> -13143226757367.79
nationality_52 --> -20360610532434.64
nationality_53 --> -10731498692470.55
nationality_54 --> -22763476634133.08
nationality_55 --> -88643681249874.75
nationality_56 --> -3393654198756.05
nationality_57 --> -18894021238476.66
nationality_58 --> -15917032514955.34
nationality_59 --> -60860877743457.03
nationality_60 --> -40429537412083.12
nationality_61 --> -99995065784699.94
nationality_62 --> -85685295742225.84
nationality_63 --> -23994589862912.65
nationality_64 --> -3393654198759.38
nationality_65 --> -270183454648675.75
nationality_66 --> -4799342940781.89
nationality_67 --> -132110253585534.72
nationality_68 --> -75282934303036.39
nationality_69 --> -764518887345053.50
nationality_70 --> -248292035164354.56
nationality_71 --> -31648877133279.08
nationality_72 --> -15551103491534.47
nationality_73 --> -200844272249951.12
nationality_74 --> -32545323052367.12
nationality_75 --> -23753475909906.09
nationality_76 --> -15176351028775.23
nationality_77 --> -15176351028775.33
nationality_78 --> -135597205767396.81
nationality_79 --> -3393654198755.25
nationality_80 --> -8312644479993.46
nationality_81 --> -12697586797115.06
nationality_82 --> -80225662633775.47
nationality_83 --> -22509169658045.52
nationality_84 --> -55321762156896.97
nationality_85 --> -36700127106996.41
nationality_86 --> -63448570047482.52
nationality_87 --> -21991729450042.76
nationality_88 --> -8312644479994.66
nationality_89 --> -17956635687255.95
nationality_90 --> -145233412292183.75
nationality_91 --> -6787270836904.15
nationality_92 --> -70398185863382.27
nationality_93 --> -18894021238475.48
nationality_94 --> -6787270836906.14
nationality_95 --> -8312644479994.75
nationality_96 --> -50429818642323.69
nationality_97 --> -15176351028776.28
nationality_98 --> -23994589862911.58
nationality_99 --> -16967519767060.61
nationality_100 --> -10180812353142.38
nationality_101 --> -23994589862911.48
nationality_102 --> -41828123200024.36
nationality_103 --> -163522481102826.88
nationality_104 --> -87472452507076.12
nationality_105 --> -8312644479994.88
nationality_106 --> -42238649977066.38
nationality_107 --> -97737786245557.12
nationality_108 --> -5877959809959.51
nationality_109 --> -23509887450547.68
nationality_110 --> -60196489760849.83
nationality_111 --> -107225491020397.48
nationality_112 --> -6787270836901.62
nationality_113 --> -148519550004931.06
nationality_114 --> -43973233302681.39
nationality_115 --> -9598579643630.73
nationality_116 --> -92748828086670.62
nationality_117 --> -33245057166490.84
nationality_118 --> -10180812353142.68
nationality_119 --> -113741092131152.27
nationality_120 --> -36543019830405.98
nationality_121 --> -191514240025061.69
nationality_122 --> -65497358035238.33
nationality_123 --> -5877959809958.77
nationality_124 --> -4799342940781.77
nationality_125 --> -282860847661681.94
nationality_126 --> -9598579643629.36
nationality_127 --> -13991981736390.74
nationality_128 --> -15917032514955.34
nationality_129 --> -6787270836904.58
nationality_130 --> -61983184341067.73
nationality_131 --> -4799342940782.77
nationality_132 --> -39856333975060.88
nationality_133 --> -60291852685105.75
nationality_134 --> -120087708920486.00
nationality_135 --> -60482125348040.12
nationality_136 --> -3393654198755.37
nationality_137 --> -60766412012717.59
nationality_138 --> -13574241184783.41
nationality_139 --> -360360339501699.94
nationality_140 --> -10180812353141.51
nationality_141 --> -16274733281426.43
nationality_142 --> -123459951543581.20
nationality_143 --> -159846027775653.34
nationality_144 --> -37933527666294.41
nationality_145 --> -5877959809957.95
nationality_146 --> -94461652076092.84
nationality_147 --> -7588385488446.33
nationality_148 --> -30912984184006.02
nationality_149 --> -777959619856313.62
nationality_150 --> -28792339097479.76
nationality_151 --> -33760328253685.59
nationality_152 --> -41690380585097.29
nationality_153 --> -9598579643630.73
nationality_154 --> -3393654198755.87
nationality_155 --> -111612167359122.72
nationality_156 --> -21461809564899.73
market_segment_bi_id --> -23.81
MainCust --> 5.59
group_member --> -10.64
m_length_of_stay --> -7.27
bed_nights --> 1544557516916079.25
m_lead_days --> 13.06
adults --> -1402944173334852.25
juniors --> -28265876639412.63
children --> -874194564735892.25
babies --> 4.36

Model: ridge_regressor
CV Mean Accuracy:  0.3989225874190631
CV STD Accuracy:  0.0026070652410620297

Train Accuracy:  0.40099242451264216
Test Accuracy:  0.39850143771842206

Model: lasso_regressor
CV Mean Accuracy:  0.3989380057784454
CV STD Accuracy:  0.002618445237282398

Train Accuracy:  0.400904942744886
Test Accuracy:  0.39834198827437106

Model: elasticnet_regressor
CV Mean Accuracy:  0.37883650531357443
CV STD Accuracy:  0.0029874843206988116

Train Accuracy:  0.3799688471225844
Test Accuracy:  0.3792011207080216

Model: supportvect_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

CV Mean Accuracy:  0.3774616493325313
CV STD Accuracy:  0.0035074750363948844

Train Accuracy:  0.3795051883604312
Test Accuracy:  0.3772616606557867

Model: decisiontree_regressor
CV Mean Accuracy:  0.682348382740449
CV STD Accuracy:  0.004762442362992476

Train Accuracy:  0.8755756003664253
Test Accuracy:  0.6957794598697875

Model: randomforest_regressor
CV Mean Accuracy:  0.24825051116322167
CV STD Accuracy:  0.004740444623587618

Train Accuracy:  0.24618659247939856
Test Accuracy:  0.24295920776012825

Model: xgboost_regressor
CV Mean Accuracy:  0.5229832727185517
CV STD Accuracy:  0.0049420602152870485

Train Accuracy:  0.5319929601785258
Test Accuracy:  0.5241317963245421

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -1.6459068797596459e+35
CV STD Accuracy:  2.4753497800834425e+35

Train Accuracy:  0.7214738636411948
Test Accuracy:  -2.957838861746911e+36

                        train_accuracy  test_accuracy
linear_regressor                0.4002         0.0000
ridge_regressor                 0.4010         0.3985
lasso_regressor                 0.4009         0.3983
elasticnet_regressor            0.3800         0.3792
supportvect_regressor           0.3795         0.3773
decisiontree_regressor          0.8756         0.6958
randomforest_regressor          0.2462         0.2430
xgboost_regressor               0.5320         0.5241
mlp_regressor                   0.7215         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 549.0

reservations_df shape: (82801, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-10-01,breakfast board,jerusalem room,4.0,8062.0,slf,,silver,,,gbr,0.0,18.0,1.0,189.0,1.0,0.0,0.0,0.0,2020.62
2018-10-05,breakfast board,jerusalem room,4.0,8062.0,slf,,silver,,,gbr,0.0,18.0,1.0,189.0,1.0,0.0,0.0,0.0,1602.86
2018-10-02,breakfast board,jerusalem room,4.0,8062.0,slf,,silver,,,gbr,0.0,18.0,1.0,189.0,1.0,0.0,0.0,0.0,1572.12
2018-10-03,breakfast board,jerusalem room,4.0,8062.0,slf,,silver,,,gbr,0.0,18.0,1.0,189.0,1.0,0.0,0.0,0.0,1572.12
2018-10-04,breakfast board,jerusalem room,4.0,8062.0,slf,,silver,,,gbr,0.0,18.0,1.0,189.0,1.0,0.0,0.0,0.0,1602.86

<class 'pandas.core.frame.DataFrame'>
Index: 82801 entries, 2018-10-01 to 2019-06-27
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   plan_desc             82801 non-null  object
 1   RoomTypes_desc        82801 non-null  object
 2   market_segment_bi_id  82801 non-null  float64
 3   MainCust              82801 non-null  float64
 4   source                82801 non-null  object
 5   sales_channel         82801 non-null  object
 6   club_code             82801 non-null  object
 7   StatisticSource       82801 non-null  object
 8   package_code          82801 non-null  object
 9   nationality           82801 non-null  object
 10  group_member          82801 non-null  float64
 11  m_length_of_stay      82801 non-null  float64
 12  bed_nights            82801 non-null  float64
 13  m_lead_days           82801 non-null  float64
 14  adults                82801 non-null  float64
 15  juniors               82801 non-null  float64
 16  children              82801 non-null  float64
 17  babies                82801 non-null  float64
 18  ARR                   82801 non-null  float64
dtypes: float64(11), object(8)
memory usage: 12.6+ MB
(82801, 218)

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-10-01,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,8062.0,0.0,18.0,1.0,189.0,1.0,0.0,0.0,0.0
2018-10-05,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,8062.0,0.0,18.0,1.0,189.0,1.0,0.0,0.0,0.0
2018-10-02,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,8062.0,0.0,18.0,1.0,189.0,1.0,0.0,0.0,0.0
2018-10-03,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,8062.0,0.0,18.0,1.0,189.0,1.0,0.0,0.0,0.0
2018-10-04,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,8062.0,0.0,18.0,1.0,189.0,1.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000,...,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000,82801.000000
mean,0.919929,0.000085,0.000290,0.007283,0.059891,0.012524,0.001341,0.391928,0.131774,0.144382,...,18.008140,7021.786621,0.455043,4.770582,1.599775,83.672359,1.461287,0.000217,0.138271,0.014348
std,0.271405,0.009194,0.017023,0.085027,0.237285,0.111208,0.036589,0.488184,0.338247,0.351479,...,15.999519,3243.814479,0.497978,5.513591,0.619041,80.578215,0.598732,0.016299,0.512429,0.123112
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,186.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,4715.000000,0.000000,3.000000,1.000000,18.000000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,14.000000,8025.000000,0.000000,4.000000,2.000000,54.000000,1.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,41.000000,8919.000000,1.000000,5.000000,2.000000,132.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13260.000000,1.000000,143.000000,4.000000,299.000000,4.000000,2.000000,4.000000,2.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

RoomTypes_desc_1        0.239265
RoomTypes_desc_3        0.244704
RoomTypes_desc_4        0.301202
RoomTypes_desc_13       0.224764
source_0                0.349757
source_3                0.215686
sales_channel_0         0.432892
sales_channel_4         0.269608
sales_channel_7         0.216018
market_segment_bi_id    0.465575
group_member            0.575184
bed_nights              0.359337
adults                  0.240521
ARR                     1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

RoomTypes_desc_1        0.240340
RoomTypes_desc_3        0.249182
RoomTypes_desc_4        0.296856
RoomTypes_desc_13       0.227967
source_0                0.353838
source_3                0.218543
sales_channel_0         0.442535
sales_channel_4         0.268606
sales_channel_7         0.218964
market_segment_bi_id    0.553240
group_member            0.592937
bed_nights              0.378216
adults                  0.278684
ARR                     1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -3.6266029450023908e+25
CV STD Accuracy:  4.030972720378059e+25

Train Accuracy:  0.6181878514863828
Test Accuracy:  -1.9455686052222616e+23

plan_desc_0 --> 659601360033996.38
plan_desc_1 --> 22344899318752.62
plan_desc_2 --> 41370465903329.09
plan_desc_3 --> 206642301898980.03
plan_desc_4 --> 576678814074521.25
plan_desc_5 --> 270271587527192.66
RoomTypes_desc_0 --> -4154207325888.52
RoomTypes_desc_1 --> -55426357700669.69
RoomTypes_desc_2 --> -38403136999392.90
RoomTypes_desc_3 --> -39905489232725.25
RoomTypes_desc_4 --> -34882439680306.13
RoomTypes_desc_5 --> -6103701340718.84
RoomTypes_desc_6 --> -4779591578311.50
RoomTypes_desc_7 --> -1115942930212.06
RoomTypes_desc_8 --> -1850425523448.59
RoomTypes_desc_9 --> -8017720988911.57
RoomTypes_desc_10 --> -4779591578339.23
RoomTypes_desc_11 --> -6911687420429.90
RoomTypes_desc_12 --> -7930738456206.27
RoomTypes_desc_13 --> -45202231698012.94
RoomTypes_desc_14 --> -882246333189.03
RoomTypes_desc_15 --> -6103701340668.09
RoomTypes_desc_16 --> -7011560242667.66
RoomTypes_desc_17 --> -1043875331068.57
RoomTypes_desc_18 --> -1626663965515.21
source_0 --> -930383400305664.25
source_1 --> -532537647926159.38
source_2 --> -107214754740799.97
source_3 --> -604313481739907.25
source_4 --> -167074733994850.88
source_5 --> -163982355391537.69
source_6 --> -643876941614468.38
source_7 --> -804111637421073.50
source_8 --> -1282108732072836.50
source_9 --> -575448868189934.75
source_10 --> -125246001097908.11
sales_channel_0 --> -586496987022068.38
sales_channel_1 --> -245305670795346.66
sales_channel_2 --> -240794526045844.06
sales_channel_3 --> -304581967127586.12
sales_channel_4 --> -349486070867150.06
sales_channel_5 --> -11481065230011.90
sales_channel_6 --> -14821633432448.71
sales_channel_7 --> -319074447957883.88
club_code_0 --> 1165823978032857.75
club_code_1 --> 45382060536317.98
club_code_2 --> 29449725848150.60
club_code_3 --> 98179025583482.62
club_code_4 --> 29449725848146.70
club_code_5 --> 83915732815313.81
club_code_6 --> 621206517469483.75
club_code_7 --> 10412490576469.08
club_code_8 --> 38956913708172.32
club_code_9 --> 254128649554626.12
club_code_10 --> 1011801491243718.25
StatisticSource_0 --> -1740464860553330.75
package_code_0 --> -580284516972299.88
package_code_1 --> -363054461947399.75
package_code_2 --> -373000748608545.00
package_code_3 --> -226419276408446.91
package_code_4 --> -121029848393836.45
nationality_0 --> 7964210613163.07
nationality_1 --> 3982249595342.48
nationality_2 --> 7964210613161.58
nationality_3 --> 6897292018248.86
nationality_4 --> 7449881858251.77
nationality_5 --> 52718732630420.50
nationality_6 --> 35137553861018.62
nationality_7 --> 110788312083143.34
nationality_8 --> 46787619879655.91
nationality_9 --> 10904983486230.85
nationality_10 --> 8904150609987.28
nationality_11 --> 40754628885640.23
nationality_12 --> 4877210316122.38
nationality_13 --> 7449881858246.28
nationality_14 --> 31206744845880.81
nationality_15 --> 4877210316124.44
nationality_16 --> 9753890473479.84
nationality_17 --> 8447269982186.85
nationality_18 --> 11262550492729.47
nationality_19 --> 152935075128091.31
nationality_20 --> 3982249595342.18
nationality_21 --> 5631683368935.53
nationality_22 --> 115334147290599.66
nationality_23 --> 68725057011686.95
nationality_24 --> 37842761085719.21
nationality_25 --> 154699620018978.69
nationality_26 --> 2815892697476.55
nationality_27 --> 9753890473475.11
nationality_28 --> 5631683368940.98
nationality_29 --> 36784754737196.57
nationality_30 --> 9338695545467.69
nationality_31 --> 17124682618101.20
nationality_32 --> 44544730185623.12
nationality_33 --> 103323761410117.47
nationality_34 --> 26100107482992.23
nationality_35 --> 30952366012454.57
nationality_36 --> 14897873996949.34
nationality_37 --> 5631683368934.85
nationality_38 --> 65640685785118.39
nationality_39 --> 7964210613165.03
nationality_40 --> 4877210316122.20
nationality_41 --> 38050802164488.59
nationality_42 --> 7449881858247.00
nationality_43 --> 159079698247357.50
nationality_44 --> 6897292018252.49
nationality_45 --> 169001137955440.59
nationality_46 --> 11945594441079.45
nationality_47 --> 18460359497577.94
nationality_48 --> 17354449571364.97
nationality_49 --> 4877210316122.33
nationality_50 --> 7964210613162.54
nationality_51 --> 27140395180966.27
nationality_52 --> 7449881858245.78
nationality_53 --> 35137553861010.53
nationality_54 --> 39074249161545.28
nationality_55 --> 16172945893521.82
nationality_56 --> 25486517498080.84
nationality_57 --> 4877210316122.12
nationality_58 --> 48360070242173.19
nationality_59 --> 13793084453141.98
nationality_60 --> 41331236223217.16
nationality_61 --> 29647557396209.27
nationality_62 --> 8904150609988.37
nationality_63 --> 243864391719722.31
nationality_64 --> 91005796118217.19
nationality_65 --> 4877210316123.53
nationality_66 --> 6296375397042.05
nationality_67 --> 47869165597987.77
nationality_68 --> 18026155059292.10
nationality_69 --> 6296375397038.19
nationality_70 --> 37946925458326.75
nationality_71 --> 7449881858246.00
nationality_72 --> 4877210316122.79
nationality_73 --> 2815892697480.17
nationality_74 --> 10904983486224.39
nationality_75 --> 5631683368935.75
nationality_76 --> 8904150609988.42
nationality_77 --> 17805074435407.94
nationality_78 --> 12591610039577.61
nationality_79 --> 2815892697479.44
nationality_80 --> 9338695545468.03
nationality_81 --> 22867439383438.56
nationality_82 --> 21065211640238.68
nationality_83 --> 69908470697501.66
nationality_84 --> 8904150609986.22
nationality_85 --> 3982249595343.86
nationality_86 --> 26401533661477.59
nationality_87 --> 6296375397035.17
nationality_88 --> 3982249595342.60
nationality_89 --> 5631683368934.98
nationality_90 --> 9753890473476.59
nationality_91 --> 3982249595344.15
nationality_92 --> 4877210316122.69
nationality_93 --> 23211049397279.66
nationality_94 --> 3982249595347.20
nationality_95 --> 10535278569672.48
nationality_96 --> 9753890473485.38
nationality_97 --> 59703434546258.60
nationality_98 --> 51128485362934.50
nationality_99 --> 118076904683536.38
nationality_100 --> 18460359497584.57
nationality_101 --> 38154393553740.75
nationality_102 --> -37786472460729.02
nationality_103 --> 54116604317354.20
nationality_104 --> 15420578326080.88
nationality_105 --> 38257701943790.02
nationality_106 --> 6897292018249.86
nationality_107 --> 24698015492132.31
nationality_108 --> 8447269982191.31
nationality_109 --> 24698015492137.62
nationality_110 --> 30307024016934.73
nationality_111 --> 18460359497586.72
nationality_112 --> 35695134721380.52
nationality_113 --> 11609101207241.22
nationality_114 --> 98803103197119.97
nationality_115 --> 7964210613163.65
nationality_116 --> 3982249595344.22
nationality_117 --> 4877210316122.39
nationality_118 --> 37105351470810.18
nationality_119 --> 3982249595342.08
nationality_120 --> 9753890473476.43
nationality_121 --> 3982249595344.77
nationality_122 --> 26994247895700.05
nationality_123 --> 8447269982186.11
nationality_124 --> 27574168977240.78
nationality_125 --> 15420578326073.34
nationality_126 --> 12902482881844.52
nationality_127 --> 9753890473481.95
nationality_128 --> 5631683368940.44
nationality_129 --> 6897292018249.83
nationality_130 --> 5631683368941.02
nationality_131 --> 3982249595342.02
nationality_132 --> 16891784929020.16
nationality_133 --> 23883395406096.92
nationality_134 --> 3982249595344.66
nationality_135 --> 5631683368936.95
nationality_136 --> 39972748640414.97
nationality_137 --> 13206032489577.83
nationality_138 --> 404464800241367.00
nationality_139 --> 8904150609990.64
nationality_140 --> 20685877177748.36
nationality_141 --> 6897292018252.19
nationality_142 --> 7449881858245.08
nationality_143 --> 5631683368934.09
nationality_144 --> 86472198995021.56
nationality_145 --> 6897292018254.34
nationality_146 --> 8904150609989.56
market_segment_bi_id --> -72.84
MainCust --> 59.00
group_member --> -196.16
m_length_of_stay --> -33.95
bed_nights --> 835293430064021.50
m_lead_days --> 46.20
adults --> -807889646679534.50
juniors --> -21992623843030.09
children --> -691438248477192.88
babies --> 9.06
Model: ridge_regressor
CV Mean Accuracy:  0.6158850350918108
CV STD Accuracy:  0.004558773648280156

Train Accuracy:  0.6182980779198513
Test Accuracy:  0.619365705500865

Model: lasso_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 78491730.73540115, tolerance: 2538472.658851883
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 62773529.06145096, tolerance: 2030049.7703557042
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 62687001.36748791, tolerance: 2030883.7673862001
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 62564591.684975624, tolerance: 2031976.0791552605
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 62725078.6853838, tolerance: 2033683.8792751038
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 63021821.51456833, tolerance: 2027282.3254556947
  positive)

CV Mean Accuracy:  0.615896703527615
CV STD Accuracy:  0.0045772333863567044

Train Accuracy:  0.6182744923646881
Test Accuracy:  0.6193709922058318

Model: elasticnet_regressor
CV Mean Accuracy:  0.58782272463682
CV STD Accuracy:  0.004291397969333686

Train Accuracy:  0.589440942461496
Test Accuracy:  0.5911036224155024

Model: supportvect_regressor
CV Mean Accuracy:  0.6060592171809883
CV STD Accuracy:  0.004854095118286444

Train Accuracy:  0.6106931303936072
Test Accuracy:  0.6104349897138255

Model: decisiontree_regressor
CV Mean Accuracy:  0.8582911656079618
CV STD Accuracy:  0.005824299337099685

Train Accuracy:  0.9618079703674473
Test Accuracy:  0.8745857804223709

Model: randomforest_regressor
CV Mean Accuracy:  0.4480773969812514
CV STD Accuracy:  0.00811936260176525

Train Accuracy:  0.4480605385356296
Test Accuracy:  0.45423550287183606

Model: xgboost_regressor
CV Mean Accuracy:  0.7006306104351061
CV STD Accuracy:  0.004686925049553802

Train Accuracy:  0.7066530646691827
Test Accuracy:  0.7037313835053784

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -1.8374122395477664e+33
CV STD Accuracy:  1.9069635594971904e+33

Train Accuracy:  0.8550095569953018
Test Accuracy:  -1.40881195349688e+34

                        train_accuracy  test_accuracy
linear_regressor                0.6182         0.0000
ridge_regressor                 0.6183         0.6194
lasso_regressor                 0.6183         0.6194
elasticnet_regressor            0.5894         0.5911
supportvect_regressor           0.6107         0.6104
decisiontree_regressor          0.9618         0.8746
randomforest_regressor          0.4481         0.4542
xgboost_regressor               0.7067         0.7037
mlp_regressor                   0.8550         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 550.0

reservations_df shape: (59007, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-10-18,breakfast board,jerusalem room,4.0,4715.0,ot,expedia,,,,usa,0.0,5.0,2.0,259.0,2.0,0.0,0.0,0.0,917.98
2018-10-19,breakfast board,jerusalem room,4.0,4715.0,ot,expedia,,,,usa,0.0,5.0,2.0,259.0,2.0,0.0,0.0,0.0,917.98
2018-10-20,breakfast board,jerusalem room,4.0,4715.0,ot,expedia,,,,usa,0.0,5.0,2.0,259.0,2.0,0.0,0.0,0.0,917.98
2018-10-16,breakfast board,jerusalem room,4.0,4715.0,ot,expedia,,,,usa,0.0,5.0,2.0,259.0,2.0,0.0,0.0,0.0,917.98
2018-10-17,breakfast board,jerusalem room,4.0,4715.0,ot,expedia,,,,usa,0.0,5.0,2.0,259.0,2.0,0.0,0.0,0.0,917.98

<class 'pandas.core.frame.DataFrame'>
Index: 59007 entries, 2018-10-18 to 2019-06-30
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   plan_desc             59007 non-null  object
 1   RoomTypes_desc        59007 non-null  object
 2   market_segment_bi_id  59007 non-null  float64
 3   MainCust              59007 non-null  float64
 4   source                59007 non-null  object
 5   sales_channel         59007 non-null  object
 6   club_code             59007 non-null  object
 7   StatisticSource       59007 non-null  object
 8   package_code          59007 non-null  object
 9   nationality           59007 non-null  object
 10  group_member          59007 non-null  float64
 11  m_length_of_stay      59007 non-null  float64
 12  bed_nights            59007 non-null  float64
 13  m_lead_days           59007 non-null  float64
 14  adults                59007 non-null  float64
 15  juniors               59007 non-null  float64
 16  children              59007 non-null  float64
 17  babies                59007 non-null  float64
 18  ARR                   59007 non-null  float64
dtypes: float64(11), object(8)
memory usage: 9.0+ MB
(59007, 195)

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-10-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,4715.0,0.0,5.0,2.0,259.0,2.0,0.0,0.0,0.0
2018-10-19,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,4715.0,0.0,5.0,2.0,259.0,2.0,0.0,0.0,0.0
2018-10-20,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,4715.0,0.0,5.0,2.0,259.0,2.0,0.0,0.0,0.0
2018-10-16,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,4715.0,0.0,5.0,2.0,259.0,2.0,0.0,0.0,0.0
2018-10-17,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,4715.0,0.0,5.0,2.0,259.0,2.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000,...,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000,59007.000000
mean,0.586524,0.000119,0.000390,0.014100,0.279916,0.005237,0.113715,0.045520,0.729574,0.000153,...,18.853153,6638.339485,0.369753,4.104462,1.627468,70.118342,1.545952,0.000017,0.081499,0.011473
std,0.492461,0.010891,0.019739,0.117904,0.448961,0.072176,0.317468,0.208443,0.444183,0.012349,...,15.954984,4126.790780,0.482742,2.765809,0.685073,79.878385,0.559953,0.004117,0.363651,0.114474
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,388.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,2865.000000,0.000000,2.000000,1.000000,8.000000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,15.000000,7178.000000,0.000000,4.000000,2.000000,37.000000,2.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,41.000000,10385.000000,1.000000,5.000000,2.000000,105.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13013.000000,1.000000,28.000000,4.000000,299.000000,4.000000,1.000000,4.000000,2.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

plan_desc_4             0.268888
RoomTypes_desc_0        0.216759
RoomTypes_desc_1        0.393383
RoomTypes_desc_5        0.306037
source_9                0.239501
sales_channel_0         0.303662
sales_channel_4         0.227189
market_segment_bi_id    0.412393
group_member            0.464412
bed_nights              0.415381
adults                  0.334069
children                0.268110
ARR                     1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

plan_desc_0             0.256639
plan_desc_4             0.368878
RoomTypes_desc_0        0.232297
RoomTypes_desc_1        0.426252
RoomTypes_desc_5        0.287402
source_9                0.311407
sales_channel_0         0.393304
sales_channel_4         0.274324
market_segment_bi_id    0.508882
group_member            0.583216
bed_nights              0.415985
adults                  0.366972
children                0.247339
ARR                     1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -1.099383060051986e+25
CV STD Accuracy:  1.1942471266766917e+25

Train Accuracy:  0.43810684594972826
Test Accuracy:  -1.5683833366874024e+24

plan_desc_0 --> 83223280844149.41
plan_desc_1 --> 1840552541300.14
plan_desc_2 --> 3335832397099.66
plan_desc_3 --> 19925216677116.65
plan_desc_4 --> 75872106804119.39
plan_desc_5 --> 12197310663811.80
plan_desc_6 --> 53650384895959.91
RoomTypes_desc_0 --> 291311647601520.75
RoomTypes_desc_1 --> 620771638847880.12
RoomTypes_desc_2 --> 17258759074141.71
RoomTypes_desc_3 --> 71764372087456.42
RoomTypes_desc_4 --> 84401849989023.64
RoomTypes_desc_5 --> 365668636582631.44
RoomTypes_desc_6 --> 491415254796017.62
source_0 --> -142064965755572.78
source_1 --> 461315254983343.25
source_2 --> 55585984533634.48
source_3 --> 229685216934841.19
source_4 --> 10702244594408.03
source_5 --> 69721010012781.01
source_6 --> 26212816839463.95
source_7 --> 763536193543835.75
source_8 --> 576670106594000.38
source_9 --> 919154625160755.38
source_10 --> 77108249516981.98
source_11 --> 486573657589033.50
source_12 --> 107638322431920.61
sales_channel_0 --> -179813365933855.59
sales_channel_1 --> -109360355890212.89
sales_channel_2 --> -107951338693909.27
sales_channel_3 --> -96564750836203.53
sales_channel_4 --> -110911333504597.16
sales_channel_5 --> -55871892530443.77
sales_channel_6 --> -45342768580980.52
sales_channel_7 --> -8359956197409.86
club_code_0 --> -1150513718666036.00
club_code_1 --> -35412991239253.22
club_code_2 --> -133742993323715.06
club_code_3 --> -348296472640437.81
club_code_4 --> -26770385719924.04
club_code_5 --> -55182483859068.03
club_code_6 --> -1103971385504734.25
StatisticSource_0 --> -157489859958733.28
StatisticSource_1 --> -157489859958744.94
package_code_0 --> 1062179852735074.75
package_code_1 --> 351618109183803.12
package_code_2 --> 434099210925124.00
package_code_3 --> 214530100149340.66
package_code_4 --> 79271566707693.00
package_code_5 --> 94348038285684.19
package_code_6 --> 158494752842572.19
package_code_7 --> 135355580711461.94
package_code_8 --> 174209339319395.44
package_code_9 --> 323912765729702.12
package_code_10 --> 204560310907056.94
package_code_11 --> 94348038285691.03
package_code_12 --> 56056312719433.88
package_code_13 --> 125320229601756.22
package_code_14 --> 118892232478353.12
package_code_15 --> 121072896902928.16
package_code_16 --> 196749823060487.16
package_code_17 --> 32365224290213.40
package_code_18 --> 45770563414224.95
package_code_19 --> 72365935371673.23
package_code_20 --> 534699234601276.00
package_code_21 --> 75897390084814.03
package_code_22 --> 82507763283425.81
package_code_23 --> 230937990171582.62
package_code_24 --> 102332213491304.69
package_code_25 --> 60547224764019.20
package_code_26 --> 39638806562983.77
package_code_27 --> 56056312719438.98
package_code_28 --> 51172611931669.39
package_code_29 --> 32365224290212.70
package_code_30 --> 214530100149341.59
package_code_31 --> 137274450017494.34
package_code_32 --> 163368495285784.06
package_code_33 --> 64727157396926.47
nationality_0 --> 14268020029943.00
nationality_1 --> 86265612627556.25
nationality_2 --> 10470396739794.25
nationality_3 --> 87506732095322.62
nationality_4 --> 36246842480157.92
nationality_5 --> 52574381186872.10
nationality_6 --> 11872112730494.08
nationality_7 --> 30125920809099.39
nationality_8 --> 11193230084885.30
nationality_9 --> 13708386418196.12
nationality_10 --> 130668053461761.06
nationality_11 --> 5596899613677.98
nationality_12 --> 157091389264978.03
nationality_13 --> 84459885263485.83
nationality_14 --> 46938578333925.83
nationality_15 --> 160397595323065.59
nationality_16 --> 6854716010915.93
nationality_17 --> 12514199564732.97
nationality_18 --> 30125920809099.47
nationality_19 --> 16788422174682.04
nationality_20 --> 29337204539523.16
nationality_21 --> 23070349901573.22
nationality_22 --> 187496892708582.38
nationality_23 --> 37308442029183.83
nationality_24 --> 16788422174680.55
nationality_25 --> 15828544543804.86
nationality_26 --> 14806498643066.31
nationality_27 --> 155765878406782.56
nationality_28 --> 3957639206498.51
nationality_29 --> 22029600222221.12
nationality_30 --> 20937066396529.30
nationality_31 --> 5596899613677.29
nationality_32 --> 160948860145628.81
nationality_33 --> 165239980173238.50
nationality_34 --> 11193230084886.56
nationality_35 --> 7915077195009.50
nationality_36 --> 6854716010916.45
nationality_37 --> 3957639206498.91
nationality_38 --> 58592240016118.53
nationality_39 --> 17248317922262.08
nationality_40 --> 27408406411775.11
nationality_41 --> 13708386418196.25
nationality_42 --> 7915077195011.18
nationality_43 --> 3957639206499.13
nationality_44 --> 32855672042798.14
nationality_45 --> 38543557638648.16
nationality_46 --> 69387142688347.25
nationality_47 --> 39935973759511.03
nationality_48 --> 25942737949183.60
nationality_49 --> 376704604067971.25
nationality_50 --> 146569989182755.00
nationality_51 --> 13124891996290.34
nationality_52 --> 13708386418197.67
nationality_53 --> 69832426815089.34
nationality_54 --> 12514199564734.28
nationality_55 --> 9693785903977.81
nationality_56 --> 7915077195010.53
nationality_57 --> 91630158106451.97
nationality_58 --> 6854716010913.56
nationality_59 --> 13124891996293.12
nationality_60 --> 13708386418199.70
nationality_61 --> 5596899613676.68
nationality_62 --> 5596899613676.97
nationality_63 --> 5596899613679.39
nationality_64 --> 7915077195008.75
nationality_65 --> 120935068238926.75
nationality_66 --> 31396279674919.75
nationality_67 --> 3957639206498.24
nationality_68 --> 9693785903976.27
nationality_69 --> 6854716010915.41
nationality_70 --> 5596899613677.33
nationality_71 --> 20937066396528.70
nationality_72 --> 87418684803657.78
nationality_73 --> 35594598817224.98
nationality_74 --> 40901350548604.85
nationality_75 --> 81768475894775.47
nationality_76 --> 5596899613678.03
nationality_77 --> 27973113192533.91
nationality_78 --> 23406962689338.38
nationality_79 --> 42948322512917.75
nationality_80 --> 44552684094274.94
nationality_81 --> 6854716010916.46
nationality_82 --> 43129556796946.17
nationality_83 --> 12514199564732.58
nationality_84 --> 36246842480162.43
nationality_85 --> 14806498643064.09
nationality_86 --> 107623424461017.42
nationality_87 --> 40901350548602.37
nationality_88 --> 16788422174681.69
nationality_89 --> 19784171314611.61
nationality_90 --> 12514199564732.61
nationality_91 --> 46437730281828.28
nationality_92 --> 32855672042799.66
nationality_93 --> 11872112730497.47
nationality_94 --> 7915077195012.34
nationality_95 --> 31644207041978.42
nationality_96 --> 19384614206280.90
nationality_97 --> 30384259427313.06
nationality_98 --> 18133107360158.08
nationality_99 --> 18976632218459.16
nationality_100 --> 477387508254494.44
nationality_101 --> 9693785903981.48
nationality_102 --> 20559965352333.97
nationality_103 --> 5596899613677.06
nationality_104 --> 58059114993534.78
nationality_105 --> 6854716010920.87
nationality_106 --> 22381906451114.50
market_segment_bi_id --> -38.38
MainCust --> 6.56
group_member --> -67.67
m_length_of_stay --> -24.56
bed_nights --> 2079061662833518.00
m_lead_days --> 7.94
adults --> -1699345702698458.00
juniors --> 1117708406340.50
children --> -1103608867785307.88
babies --> 7.45
Model: ridge_regressor
CV Mean Accuracy:  0.4332797932441686
CV STD Accuracy:  0.01649409246120867

Train Accuracy:  0.4388304072452547
Test Accuracy:  0.4271401944276857

Model: lasso_regressor
CV Mean Accuracy:  0.4334079316141578
CV STD Accuracy:  0.016516743384836375

Train Accuracy:  0.43875081718662134
Test Accuracy:  0.4270144301812694

Model: elasticnet_regressor
CV Mean Accuracy:  0.4104689617420728
CV STD Accuracy:  0.015345616594715257

Train Accuracy:  0.41370165405158543
Test Accuracy:  0.40439506597428326

Model: supportvect_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

CV Mean Accuracy:  0.40772624639964017
CV STD Accuracy:  0.01678835215219956

Train Accuracy:  0.4130371985544891
Test Accuracy:  0.40079034474600683

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

Model: decisiontree_regressor
CV Mean Accuracy:  0.5663559964952624
CV STD Accuracy:  0.030111753441698617

Train Accuracy:  0.912019881328321
Test Accuracy:  0.6031359622980382

Model: randomforest_regressor
CV Mean Accuracy:  0.30643980597963977
CV STD Accuracy:  0.014614697569978859

Train Accuracy:  0.3054877983089678
Test Accuracy:  0.3118229292947452

Model: xgboost_regressor
CV Mean Accuracy:  0.5249922499054287
CV STD Accuracy:  0.015027889322346485

Train Accuracy:  0.5441473223605349
Test Accuracy:  0.5215840227666423

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -7.85156316590678e+34
CV STD Accuracy:  1.1283987925645484e+35

Train Accuracy:  0.7250076423179829
Test Accuracy:  -3.175954560348567e+34

                        train_accuracy  test_accuracy
linear_regressor                0.4381         0.0000
ridge_regressor                 0.4388         0.4271
lasso_regressor                 0.4388         0.4270
elasticnet_regressor            0.4137         0.4044
supportvect_regressor           0.4130         0.4008
decisiontree_regressor          0.9120         0.6031
randomforest_regressor          0.3055         0.3118
xgboost_regressor               0.5441         0.5216
mlp_regressor                   0.7250         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 551.0

reservations_df shape: (262229, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-10-02,breakfast board,executive old city,4.0,12845.0,web,home site,,,,deu,0.0,2.0,2.0,198.0,2.0,0.0,0.0,0.0,1023.88
2018-10-01,breakfast board,executive old city,4.0,12845.0,web,home site,,,,deu,0.0,2.0,2.0,198.0,2.0,0.0,0.0,0.0,880.68
2018-10-01,breakfast board,jerusalem room,4.0,7245.0,t.a.,home site,,,,aus,0.0,1.0,2.0,188.0,2.0,0.0,0.0,0.0,665.88
2018-10-02,breakfast board,executive no lounge,4.0,12845.0,web,home site,silver,,,usa,0.0,5.0,1.0,167.0,1.0,0.0,0.0,0.0,780.94
2018-10-01,breakfast board,executive no lounge,4.0,12845.0,web,home site,silver,,,usa,0.0,5.0,1.0,167.0,1.0,0.0,0.0,0.0,700.18

<class 'pandas.core.frame.DataFrame'>
Index: 262229 entries, 2018-10-02 to 2019-06-30
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   plan_desc             262229 non-null  object
 1   RoomTypes_desc        262229 non-null  object
 2   market_segment_bi_id  262229 non-null  float64
 3   MainCust              262229 non-null  float64
 4   source                262229 non-null  object
 5   sales_channel         262229 non-null  object
 6   club_code             262229 non-null  object
 7   StatisticSource       262229 non-null  object
 8   package_code          262229 non-null  object
 9   nationality           262229 non-null  object
 10  group_member          262229 non-null  float64
 11  m_length_of_stay      262229 non-null  float64
 12  bed_nights            262229 non-null  float64
 13  m_lead_days           262229 non-null  float64
 14  adults                262229 non-null  float64
 15  juniors               262229 non-null  float64
 16  children              262229 non-null  float64
 17  babies                262229 non-null  float64
 18  ARR                   262229 non-null  float64
dtypes: float64(11), object(8)
memory usage: 40.0+ MB
(262229, 215)

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,plan_desc_7,RoomTypes_desc_0,RoomTypes_desc_1,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-10-02,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,12845.0,0.0,2.0,2.0,198.0,2.0,0.0,0.0,0.0
2018-10-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,12845.0,0.0,2.0,2.0,198.0,2.0,0.0,0.0,0.0
2018-10-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,7245.0,0.0,1.0,2.0,188.0,2.0,0.0,0.0,0.0
2018-10-02,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,4.0,12845.0,0.0,5.0,1.0,167.0,1.0,0.0,0.0,0.0
2018-10-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,4.0,12845.0,0.0,5.0,1.0,167.0,1.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,plan_desc_7,RoomTypes_desc_0,RoomTypes_desc_1,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000,...,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000,262229.000000
mean,0.000019,0.125615,0.000622,0.026496,0.827304,0.000587,0.000545,0.018812,0.076300,0.017435,...,29.362237,6384.342025,0.859954,4.100626,1.332606,72.925775,1.273925,0.000107,0.058575,0.010666
std,0.004367,0.331416,0.024924,0.160605,0.377985,0.024227,0.023346,0.135860,0.265478,0.130886,...,10.722505,3849.273042,0.347035,2.270869,0.622575,84.398244,0.514642,0.013244,0.306587,0.106838
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,388.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,26.000000,2788.000000,1.000000,3.000000,1.000000,9.000000,1.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,26.000000,7671.000000,1.000000,4.000000,1.000000,30.000000,1.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,41.000000,9264.000000,1.000000,5.000000,2.000000,125.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13172.000000,1.000000,74.000000,4.000000,299.000000,4.000000,3.000000,4.000000,2.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

plan_desc_1             0.228686
plan_desc_3             0.211802
plan_desc_4             0.296238
RoomTypes_desc_5        0.271787
RoomTypes_desc_7        0.358536
source_7                0.331027
source_8                0.319821
sales_channel_0         0.351565
sales_channel_5         0.258755
club_code_0             0.358945
club_code_6             0.348204
package_code_0          0.272224
nationality_53          0.388335
market_segment_bi_id    0.281763
group_member            0.455296
bed_nights              0.379358
adults                  0.246320
children                0.356380
ARR                     1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

plan_desc_1         0.278499
plan_desc_4         0.323141
RoomTypes_desc_0    0.207113
RoomTypes_desc_7    0.365319
source_7            0.236068
source_8            0.268251
sales_channel_0     0.298246
club_code_0         0.259357
club_code_6         0.251128
package_code_0      0.207861
nationality_53      0.308802
group_member        0.348564
bed_nights          0.239794
children            0.235493
ARR                 1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -9.745772988287188e+24
CV STD Accuracy:  1.0621231272277603e+25

Train Accuracy:  0.4695816817950202
Test Accuracy:  -6.806173264855167e+24

plan_desc_0 --> 842743119791.73
plan_desc_1 --> 63962790439781.03
plan_desc_2 --> 4810310790047.21
plan_desc_3 --> 30996534813309.84
plan_desc_4 --> 72950587930852.27
plan_desc_5 --> 4675705531117.26
plan_desc_6 --> 4505717144424.38
plan_desc_7 --> 26220807944035.71
RoomTypes_desc_0 --> -102880499824744.78
RoomTypes_desc_1 --> -50722355496349.26
RoomTypes_desc_2 --> -31552277442796.47
RoomTypes_desc_3 --> -74166841903705.19
RoomTypes_desc_4 --> -9509624228398.40
RoomTypes_desc_5 --> -46544914492789.80
RoomTypes_desc_6 --> -7217902590918.59
RoomTypes_desc_7 --> -139936381080888.92
RoomTypes_desc_8 --> -2140444926305.12
RoomTypes_desc_9 --> -2728516597858.58
source_0 --> 935690081109.61
source_1 --> 127770748194903.64
source_2 --> 5917383598560.77
source_3 --> -169483086682721.94
source_4 --> 2958861063084.40
source_5 --> 5691189867308.32
source_6 --> 72190189701914.11
source_7 --> 109252884966163.36
source_8 --> 181442011639301.56
source_9 --> 57696693646811.41
source_10 --> 16961263165919.85
sales_channel_0 --> 76524247765988.72
sales_channel_1 --> 34588914877552.84
sales_channel_2 --> 1444960104597.17
sales_channel_3 --> 32554908746060.56
sales_channel_4 --> 39928048432646.28
sales_channel_5 --> 42517951619940.09
sales_channel_6 --> 16174622633252.51
sales_channel_7 --> 204644991076816.69
club_code_0 --> -321332311940975.81
club_code_1 --> -7530868604142.11
club_code_2 --> -26392458403754.73
club_code_3 --> -83288672161490.03
club_code_4 --> -11023894665124.73
club_code_5 --> -25455438559773.48
club_code_6 --> -309203182392302.38
StatisticSource_0 --> -238782888137442.06
StatisticSource_1 --> -238782888137443.31
package_code_0 --> -72519591204358.94
package_code_1 --> -11841322990950.67
package_code_2 --> -18237207706216.86
package_code_3 --> -22035608478185.81
package_code_4 --> -14378107589729.27
package_code_5 --> -3973314663222.57
package_code_6 --> -9013338955325.29
package_code_7 --> -3333147276995.70
package_code_8 --> -8340044229169.74
package_code_9 --> -8716807114626.55
package_code_10 --> -13281486456492.38
package_code_11 --> -7908547059645.84
package_code_12 --> -13777354209481.41
package_code_13 --> -11841322990955.66
package_code_14 --> -10701856126602.55
package_code_15 --> -11260133406436.90
package_code_16 --> -5129351100894.99
package_code_17 --> -7172356862756.68
package_code_18 --> -12012607333889.71
package_code_19 --> -3152853708833.53
package_code_20 --> -7373231778806.20
package_code_21 --> -1324498834247.19
package_code_22 --> -2294073029657.91
package_code_23 --> -11103499291834.63
package_code_24 --> -10083793124309.65
package_code_25 --> -25582549769639.27
package_code_26 --> -8649527856238.08
package_code_27 --> -12205406938605.52
package_code_28 --> -1529396600797.88
package_code_29 --> -9300401642529.55
package_code_30 --> -38643184852101.94
package_code_31 --> -7908547059642.26
package_code_32 --> -764702674674.13
package_code_33 --> -1709914121569.28
package_code_34 --> -1081450831658.39
package_code_35 --> 258042928404741.19
package_code_36 --> -1709914121567.31
package_code_37 --> -3823338398881.53
package_code_38 --> -2861184486876.78
package_code_39 --> -6068921730854.38
package_code_40 --> -2023189957542.58
package_code_41 --> -5406759243433.57
package_code_42 --> -7333497596960.35
package_code_43 --> -2418160686539.17
nationality_0 --> 1023847174056.10
nationality_1 --> 1182234628865.38
nationality_2 --> 1182234628866.28
nationality_3 --> 1447930276745.76
nationality_4 --> 17985155425290.45
nationality_5 --> 3595399996314.91
nationality_6 --> 1182234628865.52
nationality_7 --> 23878089894765.73
nationality_8 --> 3127755676416.74
nationality_9 --> 5790727106385.80
nationality_10 --> 3395522669732.37
nationality_11 --> 4539982055384.15
nationality_12 --> 1960488171277.55
nationality_13 --> 1023847174055.69
nationality_14 --> 591120695777.97
nationality_15 --> 51022976287946.09
nationality_16 --> 1023847174056.33
nationality_17 --> 27801704449082.08
nationality_18 --> 13798145168184.48
nationality_19 --> 9134356161058.24
nationality_20 --> 90815802229541.06
nationality_21 --> 1023847174056.66
nationality_22 --> 835969310991.42
nationality_23 --> 16859523785417.29
nationality_24 --> 9526826555285.45
nationality_25 --> 1960488171277.70
nationality_26 --> 9229321182638.34
nationality_27 --> 37363399475575.30
nationality_28 --> 5084304655617.52
nationality_29 --> 4383417006589.45
nationality_30 --> 6580897535460.22
nationality_31 --> 9563361495005.65
nationality_32 --> 61621327226759.92
nationality_33 --> 2576546941399.73
nationality_34 --> 39491756731173.78
nationality_35 --> 6254509249399.70
nationality_36 --> 1023847174055.10
nationality_37 --> 35367418914286.38
nationality_38 --> 10567854708420.29
nationality_39 --> 35654376716979.88
nationality_40 --> 835969310990.98
nationality_41 --> 3395522669734.14
nationality_42 --> 4137466143460.67
nationality_43 --> 3875927189918.36
nationality_44 --> 5910091011485.48
nationality_45 --> 45734079925616.80
nationality_46 --> 34761539587048.84
nationality_47 --> 10215622807631.08
nationality_48 --> 5544283705944.55
nationality_49 --> 9761850045809.61
nationality_50 --> 44405167465348.55
nationality_51 --> 14665877256452.64
nationality_52 --> 9191453349787.75
nationality_53 --> 109375087237169.23
nationality_54 --> 48434864945623.77
nationality_55 --> 1773335036440.05
nationality_56 --> 3784730561833.94
nationality_57 --> 24293446390035.96
nationality_58 --> 1321775977434.36
nationality_59 --> 19923833848946.69
nationality_60 --> 835969310990.95
nationality_61 --> 70223537246229.73
nationality_62 --> 1773335036440.41
nationality_63 --> 1773335036441.33
nationality_64 --> 2047659207802.20
nationality_65 --> 1671919494109.97
nationality_66 --> 1960488171277.60
nationality_67 --> 1869255692279.14
nationality_68 --> 42769998105976.73
nationality_69 --> 2047659207799.43
nationality_70 --> 17830151079191.00
nationality_71 --> 1671919494108.42
nationality_72 --> 13684186970922.43
nationality_73 --> 9172460590169.85
nationality_74 --> 5480939290799.35
nationality_75 --> 10940567114245.50
nationality_76 --> 591120695778.89
nationality_77 --> 14085148663115.80
nationality_78 --> 4008831603793.19
nationality_79 --> 3875927189917.40
nationality_80 --> 35208537161162.03
nationality_81 --> 2895761160253.12
nationality_82 --> 18489196296693.25
nationality_83 --> -10995880082226.87
nationality_84 --> 6712201709106.62
nationality_85 --> 2643476344232.38
nationality_86 --> 1563940463401.11
nationality_87 --> 9991324137868.24
nationality_88 --> 7590708053217.69
nationality_89 --> 12119065643688.54
nationality_90 --> 8480861111859.55
nationality_91 --> -19806683691358.02
nationality_92 --> 25287629281280.90
nationality_93 --> 1671919494109.54
nationality_94 --> 1869255692277.61
nationality_95 --> 1773335036441.45
nationality_96 --> 7213511154108.38
nationality_97 --> 5910091011487.89
nationality_98 --> 8882679349629.79
nationality_99 --> 591120695778.52
nationality_100 --> 3127755676418.94
nationality_101 --> 21719023295649.35
nationality_102 --> 26341299101519.33
nationality_103 --> 16818279329166.03
nationality_104 --> 9153428276338.49
nationality_105 --> 4873883367496.61
nationality_106 --> 4909580586405.84
nationality_107 --> 145270534673361.28
nationality_108 --> 591120695783.11
nationality_109 --> 1023847174056.32
nationality_110 --> 3013992280078.11
nationality_111 --> 7727400109269.80
nationality_112 --> 16272471984832.79
nationality_113 --> 3691280077376.35
nationality_114 --> 10435079792514.25
market_segment_bi_id --> -3.11
MainCust --> 19.65
group_member --> -21.94
m_length_of_stay --> -12.16
bed_nights --> -33452415154388.79
m_lead_days --> 11.58
adults --> 27652920743965.34
juniors --> 711641386859.67
children --> 16473648992866.36
babies --> 9.94
Model: ridge_regressor
CV Mean Accuracy:  0.46677873139881776
CV STD Accuracy:  0.0055263862072764645

Train Accuracy:  0.46972399376326895
Test Accuracy:  0.4755306411703998

Model: lasso_regressor
CV Mean Accuracy:  0.466901071565462
CV STD Accuracy:  0.005466790219438731

Train Accuracy:  0.4696783867320829
Test Accuracy:  0.4754601007557045

Model: elasticnet_regressor
CV Mean Accuracy:  0.4439290931810886
CV STD Accuracy:  0.005707990323939896

Train Accuracy:  0.4455359022288345
Test Accuracy:  0.4526314796277681

Model: supportvect_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

CV Mean Accuracy:  0.4364643495435138
CV STD Accuracy:  0.00478630884402439

Train Accuracy:  0.4391707084230922
Test Accuracy:  0.4457848144703628

Model: decisiontree_regressor
CV Mean Accuracy:  0.6882682728126486
CV STD Accuracy:  0.012547751939041571

Train Accuracy:  0.8881214050775409
Test Accuracy:  0.7215323332887231

Model: randomforest_regressor
CV Mean Accuracy:  0.3291862670590809
CV STD Accuracy:  0.00568809737805068

Train Accuracy:  0.3345903655750385
Test Accuracy:  0.3422002120090064

Model: xgboost_regressor
CV Mean Accuracy:  0.5852275914166588
CV STD Accuracy:  0.006886935216128813

Train Accuracy:  0.5947758611610069
Test Accuracy:  0.5981043563206667

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -1.4493681249575935e+36
CV STD Accuracy:  1.996676535530075e+36

Train Accuracy:  0.7672871496050055
Test Accuracy:  -3.317253640997965e+36

                        train_accuracy  test_accuracy
linear_regressor                0.4696         0.0000
ridge_regressor                 0.4697         0.4755
lasso_regressor                 0.4697         0.4755
elasticnet_regressor            0.4455         0.4526
supportvect_regressor           0.4392         0.4458
decisiontree_regressor          0.8881         0.7215
randomforest_regressor          0.3346         0.3422
xgboost_regressor               0.5948         0.5981
mlp_regressor                   0.7673         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 552.0

reservations_df shape: (150988, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-10-02,half board,jerusalem room,20.0,10322.0,t.a.,,,,,usa,0.0,1.0,2.0,89.0,2.0,0.0,0.0,0.0,816.24
2018-10-01,breakfast board,deluxe room,4.0,12346.0,slf,,,,,pan,0.0,3.0,2.0,87.0,2.0,0.0,0.0,0.0,1113.20
2018-10-02,breakfast board,deluxe room,4.0,12346.0,slf,,,,,pan,0.0,3.0,2.0,87.0,2.0,0.0,0.0,0.0,1113.20
2018-11-05,breakfast board,jerusalem room,20.0,10322.0,t.a.,,,,,usa,0.0,3.0,1.0,123.0,1.0,0.0,0.0,0.0,745.38
2018-11-06,breakfast board,jerusalem room,20.0,10322.0,t.a.,,,,,usa,0.0,3.0,1.0,123.0,1.0,0.0,0.0,0.0,745.38

<class 'pandas.core.frame.DataFrame'>
Index: 150988 entries, 2018-10-02 to 2019-05-03
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   plan_desc             150988 non-null  object
 1   RoomTypes_desc        150988 non-null  object
 2   market_segment_bi_id  150988 non-null  float64
 3   MainCust              150988 non-null  float64
 4   source                150988 non-null  object
 5   sales_channel         150988 non-null  object
 6   club_code             150988 non-null  object
 7   StatisticSource       150988 non-null  object
 8   package_code          150988 non-null  object
 9   nationality           150988 non-null  object
 10  group_member          150988 non-null  float64
 11  m_length_of_stay      150988 non-null  float64
 12  bed_nights            150988 non-null  float64
 13  m_lead_days           150988 non-null  float64
 14  adults                150988 non-null  float64
 15  juniors               150988 non-null  float64
 16  children              150988 non-null  float64
 17  babies                150988 non-null  float64
 18  ARR                   150988 non-null  float64
dtypes: float64(11), object(8)
memory usage: 23.0+ MB
(150988, 193)

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-10-02,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,20.0,10322.0,0.0,1.0,2.0,89.0,2.0,0.0,0.0,0.0
2018-10-01,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,12346.0,0.0,3.0,2.0,87.0,2.0,0.0,0.0,0.0
2018-10-02,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,12346.0,0.0,3.0,2.0,87.0,2.0,0.0,0.0,0.0
2018-11-05,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.0,10322.0,0.0,3.0,1.0,123.0,1.0,0.0,0.0,0.0
2018-11-06,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.0,10322.0,0.0,3.0,1.0,123.0,1.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,plan_desc_6,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,150988.000000,150988.000000,150988.000000,150988.000000,150988.000000,150988.000000,150988.000000,150988.00000,150988.000000,150988.000000,...,150988.000000,150988.000000,150988.000000,150988.000000,150988.000000,150988.000000,150988.000000,150988.000000,150988.000000,150988.000000
mean,0.447075,0.000152,0.000252,0.013564,0.510551,0.000967,0.027439,0.02334,0.126401,0.021664,...,22.020922,6142.589544,0.598339,4.571026,1.514697,86.736542,1.424881,0.000086,0.089729,0.009908
std,0.497193,0.012341,0.015862,0.115672,0.499890,0.031081,0.163360,0.15098,0.332302,0.145584,...,12.841311,3790.061898,0.490236,3.080164,0.679103,87.717197,0.550683,0.009279,0.389484,0.100374
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,4.000000,-2.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,4.000000,3386.000000,0.000000,3.000000,1.000000,9.000000,1.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,26.000000,5153.000000,1.000000,4.000000,1.000000,59.000000,1.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,26.000000,9651.000000,1.000000,5.000000,2.000000,141.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,...,48.000000,13016.000000,1.000000,55.000000,5.000000,299.000000,4.000000,1.000000,4.000000,2.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

plan_desc_0             0.417291
plan_desc_4             0.481882
RoomTypes_desc_0        0.211593
RoomTypes_desc_1        0.200085
RoomTypes_desc_4        0.228515
RoomTypes_desc_5        0.435107
source_8                0.217230
source_9                0.309801
sales_channel_0         0.476676
sales_channel_5         0.403494
club_code_0             0.274127
club_code_5             0.228063
market_segment_bi_id    0.511214
MainCust                0.251623
group_member            0.604297
bed_nights              0.480125
adults                  0.391645
children                0.283346
ARR                     1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

plan_desc_0             0.499797
plan_desc_4             0.559779
RoomTypes_desc_0        0.200488
RoomTypes_desc_1        0.233957
RoomTypes_desc_5        0.445807
source_7                0.203515
source_8                0.219566
source_9                0.347383
source_10               0.204146
sales_channel_0         0.492081
sales_channel_4         0.202636
sales_channel_5         0.389457
club_code_0             0.300095
club_code_5             0.242921
nationality_53          0.234554
market_segment_bi_id    0.531398
MainCust                0.263955
group_member            0.656039
bed_nights              0.465818
adults                  0.403701
children                0.275148
ARR                     1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -3.9228995412277005e+24
CV STD Accuracy:  6.532025242931186e+24

Train Accuracy:  0.5898471678273445
Test Accuracy:  -8.091452741075828e+24

plan_desc_0 --> 57957485515466.45
plan_desc_1 --> 1438619113651.95
plan_desc_2 --> 1849064792476.27
plan_desc_3 --> 13483865856482.52
plan_desc_4 --> 58271943395088.68
plan_desc_5 --> 3623108511876.07
plan_desc_6 --> 19042800643138.62
RoomTypes_desc_0 --> 63582651142611.84
RoomTypes_desc_1 --> 139942973055333.45
RoomTypes_desc_2 --> 61310264385897.57
RoomTypes_desc_3 --> 7105935662645.12
RoomTypes_desc_4 --> 61053075758952.05
RoomTypes_desc_5 --> 184512769486309.31
RoomTypes_desc_6 --> 13442735762227.59
RoomTypes_desc_7 --> 103745432933280.73
source_0 --> -687481160108.56
source_1 --> -40032487573607.36
source_2 --> -13661991365559.88
source_3 --> -26105065149197.91
source_4 --> -1374935000282.86
source_5 --> -8700396602590.22
source_6 --> -8591524488693.15
source_7 --> -41728608868336.34
source_8 --> -40822274545227.39
source_9 --> -78656203368415.83
source_10 --> -39080419519368.80
source_11 --> -7786554278862.79
sales_channel_0 --> 229439123698761.88
sales_channel_1 --> 81761669980680.34
sales_channel_2 --> 5048242841694.10
sales_channel_3 --> 86708308768879.98
sales_channel_4 --> 118242655172023.44
sales_channel_5 --> 162469602146790.22
sales_channel_6 --> 43542133479199.32
sales_channel_7 --> 78247522433755.11
club_code_0 --> 26482676523434.55
club_code_1 --> 1251038805649.87
club_code_2 --> 2838187672100.27
club_code_3 --> 15411597932547.03
club_code_4 --> 3508921902083.68
club_code_5 --> 21962198541267.81
StatisticSource_0 --> 111917049339911.72
StatisticSource_1 --> 2571317807621.19
StatisticSource_2 --> 22033870299514.43
StatisticSource_3 --> 109807732427135.91
package_code_0 --> 359573560194970.44
package_code_1 --> 99610883374123.69
package_code_2 --> 33085030448346.03
package_code_3 --> 155783019314013.09
package_code_4 --> 137166892640079.91
package_code_5 --> 36457565652757.31
package_code_6 --> 43317038599675.59
package_code_7 --> 27962324669584.34
package_code_8 --> 49229328860851.31
package_code_9 --> 80539198069930.78
package_code_10 --> 52308387992189.57
package_code_11 --> 12505463059671.24
package_code_12 --> 36457565652759.28
package_code_13 --> 30630989077819.70
package_code_14 --> 34246146645368.00
package_code_15 --> 53050212284986.17
package_code_16 --> 15315951026684.14
package_code_17 --> 160703410819010.22
package_code_18 --> 30630989077818.58
package_code_19 --> 33085030448346.32
package_code_20 --> 8842727014492.20
package_code_21 --> 15315951026684.02
package_code_22 --> 109679743109100.42
package_code_23 --> 73966655269482.78
package_code_24 --> 92287756278337.91
nationality_0 --> 49517054086578.52
nationality_1 --> -111333535174557.67
nationality_2 --> 22145873243350.06
nationality_3 --> 33218259821886.08
nationality_4 --> 364589109417011.56
nationality_5 --> 81355659777653.00
nationality_6 --> 33218259821888.10
nationality_7 --> 409756524883875.75
nationality_8 --> 198794699171436.44
nationality_9 --> 139113654520862.66
nationality_10 --> 75089863803110.97
nationality_11 --> 19178952330606.52
nationality_12 --> 35015004354384.10
nationality_13 --> 132813620852052.83
nationality_14 --> 710179469605392.38
nationality_15 --> 590649285114710.88
nationality_16 --> 216147476321798.50
nationality_17 --> 349173437743121.31
nationality_18 --> 519370763222750.38
nationality_19 --> 163374046120799.19
nationality_20 --> 133731870656661.25
nationality_21 --> 22145873243347.36
nationality_22 --> 54242496398620.25
nationality_23 --> 75901418280306.53
nationality_24 --> 400241792747761.50
nationality_25 --> 11073046628843.19
nationality_26 --> 98393966178584.78
nationality_27 --> 273599568510478.34
nationality_28 --> 15659600861595.29
nationality_29 --> 173180492320304.53
nationality_30 --> 15659600861593.94
nationality_31 --> 944753705989860.12
nationality_32 --> 38356761414250.78
nationality_33 --> 45652921749752.51
nationality_34 --> 41429763043773.60
nationality_35 --> 472712376681204.44
nationality_36 --> 647635758985348.00
nationality_37 --> 36723924764870.05
nationality_38 --> 22145873243345.62
nationality_39 --> 24759757001563.18
nationality_40 --> 133273539641795.94
nationality_41 --> 122756403194355.56
nationality_42 --> 31318579423512.81
nationality_43 --> 351246098265023.62
nationality_44 --> 113964345167798.36
nationality_45 --> 50739713481310.21
nationality_46 --> 63603068997583.98
nationality_47 --> 152936231711223.41
nationality_48 --> 288099732544115.31
nationality_49 --> 27122865034837.02
nationality_50 --> 111794878768299.91
nationality_51 --> 95230919070880.58
nationality_52 --> 1250522667871779.50
nationality_53 --> 1002089789361610.62
nationality_54 --> 48263414119974.20
nationality_55 --> 15659600861593.84
nationality_56 --> 244715092628096.50
nationality_57 --> 218672358785212.38
nationality_58 --> 72600722779635.17
nationality_59 --> 113425879511973.36
nationality_60 --> 44289986328279.72
nationality_61 --> 29295945529624.17
nationality_62 --> 15659600861593.88
nationality_63 --> 42883736888043.08
nationality_64 --> 24759757001562.87
nationality_65 --> 39922850826297.10
nationality_66 --> 581896037368622.00
nationality_67 --> 19178952330606.93
nationality_68 --> 19178952330606.86
nationality_69 --> 65501651059426.73
nationality_70 --> 27122865034835.25
nationality_71 --> -370825071741189.81
nationality_72 --> 27122865034836.21
nationality_73 --> 141295333846095.66
nationality_74 --> 68250479623414.80
nationality_75 --> 105598646001949.17
nationality_76 --> 95230919070878.95
nationality_77 --> 11073046628842.08
nationality_78 --> 124243178598872.34
nationality_79 --> 163374046120795.59
nationality_80 --> 326595750341357.88
nationality_81 --> 22145873243346.70
nationality_82 --> 275813013493849.25
nationality_83 --> 22145873243347.68
nationality_84 --> 223635739054257.84
nationality_85 --> 123749578119618.97
nationality_86 --> 75089863803107.86
nationality_87 --> 344463115138406.31
nationality_88 --> 65809835273811.08
nationality_89 --> 213877856600141.81
nationality_90 --> 15659600861596.90
nationality_91 --> 22145873243346.28
nationality_92 --> 55360832704430.16
nationality_93 --> 15659600861593.54
nationality_94 --> 15659600861593.58
nationality_95 --> 127164418697677.97
nationality_96 --> 159204681065094.16
nationality_97 --> 54242496398623.02
nationality_98 --> 19178952330608.86
nationality_99 --> 63603068997585.74
nationality_100 --> 410636812871716.94
nationality_101 --> 27122865034838.66
nationality_102 --> 42883736888044.00
nationality_103 --> 122756403194353.58
nationality_104 --> 33218259821886.47
nationality_105 --> 11073046628842.63
nationality_106 --> 191600797512127.84
nationality_107 --> 2134712452404176.00
nationality_108 --> 31318579423511.89
nationality_109 --> 55360832704437.28
nationality_110 --> 19178952330607.30
nationality_111 --> 280403438375314.03
nationality_112 --> 31318579423513.30
market_segment_bi_id --> -39.20
MainCust --> 20.16
group_member --> -84.31
m_length_of_stay --> -22.75
bed_nights --> 897004943565794.50
m_lead_days --> 18.28
adults --> -727378250087248.88
juniors --> -12255814238111.42
children --> -514455947796077.19
babies --> 9.00
Model: ridge_regressor
CV Mean Accuracy:  0.5881830396443439
CV STD Accuracy:  0.0031918702717578743

Train Accuracy:  0.5901833351194532
Test Accuracy:  0.5852091266024526

Model: lasso_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3284794.170997143, tolerance: 959657.6659436013
  positive)

CV Mean Accuracy:  0.5881373901544716
CV STD Accuracy:  0.003169870677229308

Train Accuracy:  0.5900413111449359
Test Accuracy:  0.5851509495048159

Model: elasticnet_regressor
CV Mean Accuracy:  0.5687515827302219
CV STD Accuracy:  0.0023041294495525113

Train Accuracy:  0.5700172374363253
Test Accuracy:  0.5652141554467832

Model: supportvect_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

CV Mean Accuracy:  0.5686406311191616
CV STD Accuracy:  0.0034419822896635914

Train Accuracy:  0.5711345465304911
Test Accuracy:  0.5658292206468563

Model: decisiontree_regressor
CV Mean Accuracy:  0.8245159204385051
CV STD Accuracy:  0.006046938276532588

Train Accuracy:  0.940982292081385
Test Accuracy:  0.8388902845869649

Model: randomforest_regressor
CV Mean Accuracy:  0.47622852528811166
CV STD Accuracy:  0.003474617160784349

Train Accuracy:  0.47633985671371104
Test Accuracy:  0.47821944017301177

Model: xgboost_regressor
CV Mean Accuracy:  0.7133707778996288
CV STD Accuracy:  0.004049868171967504

Train Accuracy:  0.718053815072147
Test Accuracy:  0.7138377596741818

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -6.199962302723268e+35
CV STD Accuracy:  6.975606325231381e+35

Train Accuracy:  0.8441843136927283
Test Accuracy:  -7.801498811247842e+34

                        train_accuracy  test_accuracy
linear_regressor                0.5898         0.0000
ridge_regressor                 0.5902         0.5852
lasso_regressor                 0.5900         0.5852
elasticnet_regressor            0.5700         0.5652
supportvect_regressor           0.5711         0.5658
decisiontree_regressor          0.9410         0.8389
randomforest_regressor          0.4763         0.4782
xgboost_regressor               0.7181         0.7138
mlp_regressor                   0.8442         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 554.0

reservations_df shape: (202850, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-12-22,breakfast board,superior room,4.0,1984.0,t.a.,,gold,,,rus,0.0,16.0,1.0,180.0,1.0,0.0,0.0,0.0,960.00
2018-12-24,breakfast board,superior room,4.0,1984.0,t.a.,,gold,,,rus,0.0,16.0,1.0,180.0,1.0,0.0,0.0,0.0,1053.75
2018-12-26,breakfast board,superior room,4.0,1984.0,t.a.,,gold,,,rus,0.0,11.0,1.0,180.0,1.0,0.0,0.0,0.0,1080.00
2018-12-31,breakfast board,superior room,4.0,1984.0,t.a.,,gold,,,rus,0.0,11.0,1.0,180.0,1.0,0.0,0.0,0.0,1210.17
2018-12-25,breakfast board,superior room,4.0,1984.0,t.a.,,gold,,,rus,0.0,16.0,1.0,180.0,1.0,0.0,0.0,0.0,1053.75

<class 'pandas.core.frame.DataFrame'>
Index: 202850 entries, 2018-12-22 to 2019-06-30
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   plan_desc             202850 non-null  object
 1   RoomTypes_desc        202850 non-null  object
 2   market_segment_bi_id  202850 non-null  float64
 3   MainCust              202850 non-null  float64
 4   source                202850 non-null  object
 5   sales_channel         202850 non-null  object
 6   club_code             202850 non-null  object
 7   StatisticSource       202850 non-null  object
 8   package_code          202850 non-null  object
 9   nationality           202850 non-null  object
 10  group_member          202850 non-null  float64
 11  m_length_of_stay      202850 non-null  float64
 12  bed_nights            202850 non-null  float64
 13  m_lead_days           202850 non-null  float64
 14  adults                202850 non-null  float64
 15  juniors               202850 non-null  float64
 16  children              202850 non-null  float64
 17  babies                202850 non-null  float64
 18  ARR                   202850 non-null  float64
dtypes: float64(11), object(8)
memory usage: 31.0+ MB
(202850, 169)

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-12-22,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,1984.0,0.0,16.0,1.0,180.0,1.0,0.0,0.0,0.0
2018-12-24,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,1984.0,0.0,16.0,1.0,180.0,1.0,0.0,0.0,0.0
2018-12-26,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,1984.0,0.0,11.0,1.0,180.0,1.0,0.0,0.0,0.0
2018-12-31,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,1984.0,0.0,11.0,1.0,180.0,1.0,0.0,0.0,0.0
2018-12-25,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,1984.0,0.0,16.0,1.0,180.0,1.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,plan_desc_3,plan_desc_4,plan_desc_5,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000,...,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000,202850.000000
mean,0.000030,0.386591,0.000039,0.000434,0.018748,0.594158,0.017146,0.000182,0.039635,0.000291,...,19.374912,7827.562736,0.425526,3.302066,2.037619,66.731545,1.700325,0.000015,0.337279,0.094326
std,0.005439,0.486970,0.006280,0.020824,0.135634,0.491055,0.129814,0.013504,0.195101,0.017052,...,12.789063,3820.631954,0.494424,2.014237,0.738733,76.538036,0.627850,0.003846,0.765422,0.309039
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,186.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,13.000000,2865.000000,0.000000,2.000000,2.000000,13.000000,1.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,15.000000,8919.000000,0.000000,3.000000,2.000000,28.000000,2.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,21.000000,10482.000000,1.000000,4.000000,2.000000,106.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13146.000000,1.000000,28.000000,6.000000,299.000000,6.000000,1.000000,5.000000,3.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

plan_desc_1         0.330996
plan_desc_5         0.318103
RoomTypes_desc_4    0.418965
RoomTypes_desc_6    0.222013
source_1            0.220831
source_7            0.228947
sales_channel_0     0.355368
sales_channel_4     0.274133
club_code_0         0.241801
club_code_6         0.224499
group_member        0.393460
bed_nights          0.348518
ARR                 1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

plan_desc_1         0.364168
plan_desc_5         0.356814
RoomTypes_desc_4    0.419497
source_1            0.240839
source_7            0.214340
sales_channel_0     0.375563
sales_channel_4     0.277240
club_code_0         0.235149
club_code_6         0.220023
group_member        0.416082
bed_nights          0.339503
adults              0.233366
children            0.214383
ARR                 1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -2.2527972374087165e+25
CV STD Accuracy:  3.869394004926246e+25

Train Accuracy:  0.43965584669665936
Test Accuracy:  -5.426327486798079e+24

plan_desc_0 --> -6270879521132.80
plan_desc_1 --> -561497359541356.81
plan_desc_2 --> -7240952261752.67
plan_desc_3 --> -24010785501546.25
plan_desc_4 --> -156391350391105.69
plan_desc_5 --> -566208244176660.00
RoomTypes_desc_0 --> 234698148342262.50
RoomTypes_desc_1 --> 24415270949961.41
RoomTypes_desc_2 --> 352733281933739.00
RoomTypes_desc_3 --> 30829262517374.59
RoomTypes_desc_4 --> 844911732361368.50
RoomTypes_desc_5 --> 184587719301084.78
RoomTypes_desc_6 --> 241616747336802.00
RoomTypes_desc_7 --> 392919523727888.38
RoomTypes_desc_8 --> 507752035829509.94
RoomTypes_desc_9 --> 339574809717212.69
RoomTypes_desc_10 --> 315360749828681.38
RoomTypes_desc_11 --> 10620423234700.61
RoomTypes_desc_12 --> 186964548425785.91
RoomTypes_desc_13 --> 117401969668686.98
RoomTypes_desc_14 --> 232900573992559.09
RoomTypes_desc_15 --> 27516862148815.68
source_0 --> 3568878073870.76
source_1 --> 640463003158188.12
source_2 --> 113416577098328.00
source_3 --> 1228991884989564.50
source_4 --> 24723047943824.58
source_5 --> 100241115597445.09
source_6 --> 396342700290527.31
source_7 --> 589879532591850.88
source_8 --> 803539882960330.25
source_9 --> 357023886914458.31
source_10 --> 110144261439713.22
sales_channel_0 --> 415816778115434.75
sales_channel_1 --> 213344105906438.69
sales_channel_2 --> 118852442277778.34
sales_channel_3 --> 222187959889508.25
sales_channel_4 --> 305825224525996.69
sales_channel_5 --> 52283107112180.94
sales_channel_6 --> -1148811940459726.75
club_code_0 --> -164914031693108.19
club_code_1 --> -10167335285231.50
club_code_2 --> -15957049735839.80
club_code_3 --> -52131885335976.01
club_code_4 --> -4123509428210.30
club_code_5 --> -6626993259412.75
club_code_6 --> -159851793135924.69
StatisticSource_0 --> 499083199908083.94
StatisticSource_1 --> 499083199908082.62
package_code_0 --> 602910685919814.50
package_code_1 --> 165260429721779.88
package_code_2 --> 45266690288244.69
package_code_3 --> 61290632986860.68
package_code_4 --> 192002009719151.81
package_code_5 --> 206552613605893.12
package_code_6 --> 448989041435905.00
package_code_7 --> 82642439169687.91
package_code_8 --> 45266690288242.76
package_code_9 --> 104532243317541.94
package_code_10 --> 36960280059285.39
package_code_11 --> 55439736802575.55
package_code_12 --> 48893493151822.34
package_code_13 --> 107748838857561.09
package_code_14 --> 110872093821433.94
nationality_0 --> -6810130553109.27
nationality_1 --> -5342371779855.86
nationality_2 --> -24904966307055.19
nationality_3 --> -2671225396040.47
nationality_4 --> -29607499687779.06
nationality_5 --> -18211242388657.94
nationality_6 --> -10515873123585.56
nationality_7 --> -27552394457513.02
nationality_8 --> -6264439872237.78
nationality_9 --> -2671225396040.64
nationality_10 --> -4626652486795.68
nationality_11 --> -15573252656679.73
nationality_12 --> -33338091000823.96
nationality_13 --> -57898962522191.61
nationality_14 --> -34128816198463.77
nationality_15 --> -12239885593455.47
nationality_16 --> -28442480650883.84
nationality_17 --> -396738802990523.50
nationality_18 --> -7315217610069.06
nationality_19 --> -1888846247416.78
nationality_20 --> -6264439872239.59
nationality_21 --> -21857806922778.74
nationality_22 --> -49674468069408.91
nationality_23 --> -7787605441321.27
nationality_24 --> -2671225396040.69
nationality_25 --> -2671225396039.02
nationality_26 --> -19349952265854.81
nationality_27 --> -14870553811621.97
nationality_28 --> -88587239935906.56
nationality_29 --> -121349180833050.03
nationality_30 --> -106458694563155.56
nationality_31 --> -5972923784016.89
nationality_32 --> -4626652486794.06
nationality_33 --> 122000828855500.66
nationality_34 --> -4223546965379.25
nationality_35 --> -6542977924443.49
nationality_36 --> -5342371779858.18
nationality_37 --> -4626652486796.84
nationality_38 --> -8655354183852.15
nationality_39 --> -30958910412536.05
nationality_40 --> -14750178855630.72
nationality_41 --> -9994169672949.25
nationality_42 --> -3271561540030.62
nationality_43 --> -4626652486796.24
nationality_44 --> -307551322817079.94
nationality_45 --> -30901388658716.59
nationality_46 --> 16499459577053.64
nationality_47 --> -7787605441318.69
nationality_48 --> -5972923784015.09
nationality_49 --> -11642568299697.80
nationality_50 --> -3777664559967.42
nationality_51 --> -209620626892416.34
nationality_52 --> -1888846247418.25
nationality_53 --> -24833358454130.72
nationality_54 --> -6810130553108.98
nationality_55 --> -11642568299701.00
nationality_56 --> -2671225396041.31
nationality_57 --> -4626652486794.47
nationality_58 --> -8232924609842.78
nationality_59 --> -16785204596251.66
nationality_60 --> -3777664559967.24
nationality_61 --> 185506558709750.00
nationality_62 --> -27616927561441.20
nationality_63 --> -12527860537496.64
nationality_64 --> -3271561540031.02
nationality_65 --> -7787605441319.81
nationality_66 --> -25470557857250.38
nationality_67 --> -6542977924447.38
nationality_68 --> -6264439872236.59
nationality_69 --> -5342371779855.32
nationality_70 --> -17715148262101.85
nationality_71 --> -11173628560855.89
nationality_72 --> -3271561540028.30
nationality_73 --> -2671225396040.75
nationality_74 --> -18977990262261.48
nationality_75 --> -4997343526522.40
nationality_76 --> -149097984739674.72
nationality_77 --> -3271561540030.56
nationality_78 --> -8232924609847.59
nationality_79 --> -5342371779858.82
nationality_80 --> -18883852675752.11
nationality_81 --> -34180876709070.75
nationality_82 --> -5972923784017.08
nationality_83 --> -2671225396038.34
nationality_84 --> -4626652486791.92
nationality_85 --> -5972923784012.66
nationality_86 --> -7067189045488.26
nationality_87 --> -10515873123591.67
nationality_88 --> -41161482326113.06
nationality_89 --> -11944964140994.05
nationality_90 --> -170388714984545.88
nationality_91 --> -3777664559969.08
nationality_92 --> -6542977924448.00
nationality_93 --> -18598575571184.89
nationality_94 --> -3271561540028.57
market_segment_bi_id --> 12.00
MainCust --> 44.19
group_member --> -76.77
m_length_of_stay --> -3.59
bed_nights --> 1010353905827917.25
m_lead_days --> 42.30
adults --> -858700842464351.62
juniors --> -5259655114416.92
children --> -1046857049353362.00
babies --> 16.69
Model: ridge_regressor
CV Mean Accuracy:  0.43819612746118536
CV STD Accuracy:  0.004347026490212363

Train Accuracy:  0.4398041786161395
Test Accuracy:  0.4359436610321632

Model: lasso_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 7966810.378341675, tolerance: 3785819.98543273
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 9083532.028060913, tolerance: 3023795.399353175
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 16692923.988229752, tolerance: 3022075.6609595474
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 21235664.317897797, tolerance: 3026996.564040381
  positive)

CV Mean Accuracy:  0.43820148318254387
CV STD Accuracy:  0.004298826311312012

Train Accuracy:  0.43975778509069874
Test Accuracy:  0.4359989587344454

Model: elasticnet_regressor
CV Mean Accuracy:  0.41395229642853815
CV STD Accuracy:  0.0032229315675646924

Train Accuracy:  0.41486357775063265
Test Accuracy:  0.41315282015697086

Model: supportvect_regressor
CV Mean Accuracy:  0.4106752248195134
CV STD Accuracy:  0.004491416665127516

Train Accuracy:  0.41250242719574703
Test Accuracy:  0.4101648340760943

Model: decisiontree_regressor
CV Mean Accuracy:  0.5875808032030226
CV STD Accuracy:  0.005518750311222157

Train Accuracy:  0.8315497753620932
Test Accuracy:  0.6201013453824753

Model: randomforest_regressor
CV Mean Accuracy:  0.2856808136027623
CV STD Accuracy:  0.0032072880109324416

Train Accuracy:  0.2857389444813464
Test Accuracy:  0.28531991324558403

Model: xgboost_regressor
CV Mean Accuracy:  0.5402014452785181
CV STD Accuracy:  0.0024273939720836344

Train Accuracy:  0.5431213505789034
Test Accuracy:  0.5400925629017328

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -2.0062070203485451e+34
CV STD Accuracy:  2.1508844917843187e+34

Train Accuracy:  0.6644456753233821
Test Accuracy:  -1.6764439839972077e+35

                        train_accuracy  test_accuracy
linear_regressor                0.4397         0.0000
ridge_regressor                 0.4398         0.4359
lasso_regressor                 0.4398         0.4360
elasticnet_regressor            0.4149         0.4132
supportvect_regressor           0.4125         0.4102
decisiontree_regressor          0.8315         0.6201
randomforest_regressor          0.2857         0.2853
xgboost_regressor               0.5431         0.5401
mlp_regressor                   0.6644         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 555.0

reservations_df shape: (186865, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-11-09,half board,eilat quadro room,21.0,9613.0,t.a.,,,,,rus,0.0,3.0,1.0,246.0,1.0,0.0,0.0,0.0,476.74
2018-11-10,half board,eilat quadro room,21.0,9613.0,t.a.,,,,,rus,0.0,3.0,1.0,246.0,1.0,0.0,0.0,0.0,476.74
2018-11-08,half board,eilat quadro room,21.0,9613.0,t.a.,,,,,rus,0.0,3.0,1.0,246.0,1.0,0.0,0.0,0.0,476.74
2018-11-09,half board,eilat quadro room,21.0,9613.0,t.a.,,,,,rus,0.0,3.0,1.0,246.0,1.0,0.0,0.0,0.0,476.74
2018-11-10,half board,eilat quadro room,21.0,9613.0,t.a.,,,,,rus,0.0,3.0,1.0,246.0,1.0,0.0,0.0,0.0,476.74

<class 'pandas.core.frame.DataFrame'>
Index: 186865 entries, 2018-11-09 to 2019-04-04
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   plan_desc             186865 non-null  object
 1   RoomTypes_desc        186865 non-null  object
 2   market_segment_bi_id  186865 non-null  float64
 3   MainCust              186865 non-null  float64
 4   source                186865 non-null  object
 5   sales_channel         186865 non-null  object
 6   club_code             186865 non-null  object
 7   StatisticSource       186865 non-null  object
 8   package_code          186865 non-null  object
 9   nationality           186865 non-null  object
 10  group_member          186865 non-null  float64
 11  m_length_of_stay      186865 non-null  float64
 12  bed_nights            186865 non-null  float64
 13  m_lead_days           186865 non-null  float64
 14  adults                186865 non-null  float64
 15  juniors               186865 non-null  float64
 16  children              186865 non-null  float64
 17  babies                186865 non-null  float64
 18  ARR                   186865 non-null  float64
dtypes: float64(11), object(8)
memory usage: 28.5+ MB
(186865, 161)

,plan_desc_0,plan_desc_1,plan_desc_2,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,RoomTypes_desc_4,RoomTypes_desc_5,RoomTypes_desc_6,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-11-09,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,9613.0,0.0,3.0,1.0,246.0,1.0,0.0,0.0,0.0
2018-11-10,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,9613.0,0.0,3.0,1.0,246.0,1.0,0.0,0.0,0.0
2018-11-08,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,9613.0,0.0,3.0,1.0,246.0,1.0,0.0,0.0,0.0
2018-11-09,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,9613.0,0.0,3.0,1.0,246.0,1.0,0.0,0.0,0.0
2018-11-10,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,9613.0,0.0,3.0,1.0,246.0,1.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,RoomTypes_desc_4,RoomTypes_desc_5,RoomTypes_desc_6,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,186865.000000,186865.000000,186865.000000,186865.000000,186865.000000,186865.000000,186865.000000,186865.000000,186865.000000,186865.000000,...,186865.00000,186865.000000,186865.000000,186865.000000,186865.000000,186865.000000,186865.000000,186865.000000,186865.000000,186865.000000
mean,0.311407,0.102443,0.586150,0.104535,0.808182,0.020646,0.002424,0.040949,0.008455,0.014807,...,20.03966,7446.987579,0.471726,3.473074,2.053124,61.580869,1.736473,0.000005,0.316646,0.097434
std,0.463070,0.303231,0.492524,0.305955,0.393731,0.142196,0.049177,0.198173,0.091563,0.120782,...,13.04463,3583.087711,0.499201,2.158146,0.800798,76.566170,0.574818,0.002313,0.702026,0.327277
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.00000,388.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,13.00000,2865.000000,0.000000,2.000000,2.000000,7.000000,1.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,15.00000,8587.000000,0.000000,3.000000,2.000000,21.000000,2.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,21.00000,9841.000000,1.000000,4.000000,2.000000,95.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.00000,13239.000000,1.000000,35.000000,6.000000,299.000000,5.000000,1.000000,5.000000,3.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

plan_desc_0         0.218348
RoomTypes_desc_0    0.271178
RoomTypes_desc_1    0.332929
source_9            0.233116
sales_channel_0     0.299508
sales_channel_4     0.267253
club_code_6         0.200070
group_member        0.302010
bed_nights          0.452372
adults              0.239296
children            0.320081
ARR                 1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

plan_desc_0             0.227891
plan_desc_1             0.207396
RoomTypes_desc_0        0.230445
RoomTypes_desc_1        0.299537
source_9                0.298712
sales_channel_0         0.282356
sales_channel_4         0.234153
market_segment_bi_id    0.222482
group_member            0.285981
bed_nights              0.466847
adults                  0.289453
children                0.360229
ARR                     1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -1.045054291662153e+25
CV STD Accuracy:  9.866007472533677e+24

Train Accuracy:  0.4216417010988737
Test Accuracy:  -1.4717383461118423e+25

plan_desc_0 --> 96931665699057.28
plan_desc_1 --> 63473490375297.17
plan_desc_2 --> 103097023754754.31
RoomTypes_desc_0 --> 35559392905406.34
RoomTypes_desc_1 --> 45761204586973.76
RoomTypes_desc_2 --> 16526675711326.42
RoomTypes_desc_3 --> 5715530897688.27
RoomTypes_desc_4 --> 23032590087172.90
RoomTypes_desc_5 --> 10641901069053.61
RoomTypes_desc_6 --> 14037819621134.76
source_0 --> 12915513510857.72
source_1 --> 685586012972641.88
source_2 --> 106351189491765.89
source_3 --> 441451086469469.38
source_4 --> 10210691926891.15
source_5 --> 22369367834472.27
source_6 --> 6457860434257.92
source_7 --> 584485535853596.88
source_8 --> 588503241387961.50
source_9 --> 959950791704652.50
source_10 --> 386007629274956.56
source_11 --> 116929191558212.00
sales_channel_0 --> 300186807327795.12
sales_channel_1 --> 175226512806154.34
sales_channel_2 --> 91892094538172.52
sales_channel_3 --> 131594263424519.52
sales_channel_4 --> 230743276013649.00
sales_channel_5 --> 46005232666995.14
sales_channel_6 --> -346449099802813.50
sales_channel_7 --> 1557140473628.20
club_code_0 --> -924449441741243.50
club_code_1 --> -36262744745013.41
club_code_2 --> -47903503925714.15
club_code_3 --> -183646518747678.19
club_code_4 --> -11978761093584.00
club_code_5 --> -54438976393414.04
club_code_6 --> -913509689961808.25
StatisticSource_0 --> -735702255347004.62
StatisticSource_1 --> -730720258468362.25
StatisticSource_2 --> -85573810438272.95
package_code_0 --> -2465746190936904.00
package_code_1 --> -266852108392740.88
package_code_2 --> -46113043020298.97
package_code_3 --> -1126839446910640.50
package_code_4 --> -1887183133613086.50
package_code_5 --> -371647884704995.56
package_code_6 --> -97818704037277.34
package_code_7 --> -200982731591817.03
package_code_8 --> -243972028680070.12
package_code_9 --> -300553489449403.62
package_code_10 --> -478946314216202.62
package_code_11 --> -32606932668682.39
package_code_12 --> -190112666750123.53
package_code_13 --> -149415740530856.41
package_code_14 --> -192887664750628.16
package_code_15 --> -56476561825200.48
package_code_16 --> -522370709332978.81
package_code_17 --> -581882690481979.00
package_code_18 --> -97818704037277.03
package_code_19 --> -97818704037274.84
nationality_0 --> -635904624832488.25
nationality_1 --> 650631154452.03
nationality_2 --> 1840193866818.67
nationality_3 --> 7582114250583.59
nationality_4 --> 5907072888316.38
nationality_5 --> 5798770196720.07
nationality_6 --> 4506570940180.12
nationality_7 --> 2206273610450.10
nationality_8 --> 650631154451.32
nationality_9 --> 3317137070969.27
nationality_10 --> 920126478617.88
nationality_11 --> 8599022852334.52
nationality_12 --> 8463066164979.78
nationality_13 --> 11381295275876.47
nationality_14 --> 7665161112194.25
nationality_15 --> 2945550413577.28
nationality_16 --> 4576407668908.70
nationality_17 --> 2005288677102.70
nationality_18 --> 1028729924371.98
nationality_19 --> 920126478617.86
nationality_20 --> 4165180227466.04
nationality_21 --> 18380448561672.56
nationality_22 --> 3592660688479.26
nationality_23 --> 920126478618.53
nationality_24 --> 460066932385.83
nationality_25 --> 1454824346579.38
nationality_26 --> 5303876383644.19
nationality_27 --> 3119950013634.00
nationality_28 --> 1028729924374.92
nationality_29 --> 26995877313876.31
nationality_30 --> 22310394689880.44
nationality_31 --> 19816104869955.56
nationality_32 --> 1028729924373.92
nationality_33 --> 460066932386.21
nationality_34 --> 650631154452.00
nationality_35 --> 1217203147534.37
nationality_36 --> 1028729924373.47
nationality_37 --> 2057377266821.22
nationality_38 --> 2721545050527.96
nationality_39 --> 2300186934698.72
nationality_40 --> 460066932385.61
nationality_41 --> 650631154451.98
nationality_42 --> 4845679035795.78
nationality_43 --> 4459404291655.02
nationality_44 --> 1951809896882.59
nationality_45 --> 1126914154911.03
nationality_46 --> 75847616000069.84
nationality_47 --> 8647927796903.91
nationality_48 --> 1028729924373.56
nationality_49 --> 3563100498829.95
nationality_50 --> 1840193866816.04
nationality_51 --> 8804978912047.06
nationality_52 --> 1525828564290.16
nationality_53 --> 4553248025277.28
nationality_54 --> 2390411588680.38
nationality_55 --> 4622378121747.97
nationality_56 --> 1896823345287.45
nationality_57 --> 4165180227468.64
nationality_58 --> 460066932386.94
nationality_59 --> 460066932388.59
nationality_60 --> 1028729924373.94
nationality_61 --> 7181801013353.51
nationality_62 --> 4867444446522.00
nationality_63 --> 2345733335573.91
nationality_64 --> 23593500873198.12
nationality_65 --> 1126914154909.88
nationality_66 --> 1840193866818.59
nationality_67 --> 5632399258673.14
nationality_68 --> 460066932385.72
nationality_69 --> 2477350627271.09
nationality_70 --> -127229730645134.52
nationality_71 --> 4889112731013.04
nationality_72 --> 3533292691174.08
nationality_73 --> 41233021323983.00
nationality_74 --> 13272467272366.98
nationality_75 --> 920126478619.38
nationality_76 --> 4506570940178.84
nationality_77 --> 796855037382.97
nationality_78 --> 8599022852320.06
nationality_79 --> 3187036330078.45
nationality_80 --> 920126478621.55
nationality_81 --> 460066932386.34
nationality_82 --> 8054420977856.30
nationality_83 --> 1525828564290.16
nationality_84 --> 34139444610740.12
nationality_85 --> 2157783932849.25
nationality_86 --> 1217203147533.30
nationality_87 --> 920126478616.44
nationality_88 --> 650631154452.25
nationality_89 --> 3679914972322.84
nationality_90 --> 650631154452.84
market_segment_bi_id --> 0.66
MainCust --> 26.22
group_member --> -92.25
m_length_of_stay --> -18.50
bed_nights --> 2584621537245894.00
m_lead_days --> 25.66
adults --> -1855259282650543.25
juniors --> -7466379274563.31
children --> -2265828582593001.00
babies --> 17.72
Model: ridge_regressor
CV Mean Accuracy:  0.42094904350687196
CV STD Accuracy:  0.0030540466406725666

Train Accuracy:  0.42237866986073214
Test Accuracy:  0.4154992126592182

Model: lasso_regressor
CV Mean Accuracy:  0.42088189611380883
CV STD Accuracy:  0.0032026670191008795

Train Accuracy:  0.4222135803584454
Test Accuracy:  0.4152683690389393

Model: elasticnet_regressor
CV Mean Accuracy:  0.39141130485210895
CV STD Accuracy:  0.0030545264602072444

Train Accuracy:  0.3921062922460393
Test Accuracy:  0.38441160161680377

Model: supportvect_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

CV Mean Accuracy:  0.37897941938446367
CV STD Accuracy:  0.003774835529252393

Train Accuracy:  0.3810060831105092
Test Accuracy:  0.3709278389845281

Model: decisiontree_regressor
CV Mean Accuracy:  0.5682338652630481
CV STD Accuracy:  0.007005656008123386

Train Accuracy:  0.8331896212219538
Test Accuracy:  0.6152154040925288

Model: randomforest_regressor
CV Mean Accuracy:  0.2592479815759943
CV STD Accuracy:  0.007594555535997328

Train Accuracy:  0.25866718154144386
Test Accuracy:  0.25894362195747045

Model: xgboost_regressor
CV Mean Accuracy:  0.5381117014756993
CV STD Accuracy:  0.0031715904023909697

Train Accuracy:  0.5403554150686534
Test Accuracy:  0.5338196209721606

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -1.4099609991964985e+35
CV STD Accuracy:  1.5955374315147e+35

Train Accuracy:  0.6454781168506628
Test Accuracy:  0.5945696944077556

                        train_accuracy  test_accuracy
linear_regressor                0.4216         0.0000
ridge_regressor                 0.4224         0.4155
lasso_regressor                 0.4222         0.4153
elasticnet_regressor            0.3921         0.3844
supportvect_regressor           0.3810         0.3709
decisiontree_regressor          0.8332         0.6152
randomforest_regressor          0.2587         0.2589
xgboost_regressor               0.5404         0.5338
mlp_regressor                   0.6455         0.5946

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 643.0

reservations_df shape: (26501, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2018-11-07,breakfast board,queen room,4.0,8448.0,t.a.,,,,,can,0.0,2.0,2.0,158.0,2.0,0.0,0.0,0.0,777.85
2018-11-06,breakfast board,queen room,4.0,8448.0,t.a.,,,,,can,0.0,2.0,2.0,158.0,2.0,0.0,0.0,0.0,851.65
2018-10-25,breakfast board,queen room,15.0,2865.0,ot,booking.com,,,,isr,0.0,1.0,2.0,138.0,2.0,0.0,0.0,0.0,658.98
2018-12-31,room only,queen room,4.0,2865.0,ot,booking.com,,,,ita,0.0,1.0,2.0,194.0,2.0,0.0,0.0,0.0,581.20
2018-10-02,room only,queen plus room,4.0,2865.0,ot,booking.com,,,,isr,0.0,7.0,2.0,98.0,2.0,0.0,0.0,0.0,550.26

<class 'pandas.core.frame.DataFrame'>
Index: 26501 entries, 2018-11-07 to 2019-06-28
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   plan_desc             26501 non-null  object
 1   RoomTypes_desc        26501 non-null  object
 2   market_segment_bi_id  26501 non-null  float64
 3   MainCust              26501 non-null  float64
 4   source                26501 non-null  object
 5   sales_channel         26501 non-null  object
 6   club_code             26501 non-null  object
 7   StatisticSource       26501 non-null  object
 8   package_code          26501 non-null  object
 9   nationality           26501 non-null  object
 10  group_member          26501 non-null  float64
 11  m_length_of_stay      26501 non-null  float64
 12  bed_nights            26501 non-null  float64
 13  m_lead_days           26501 non-null  float64
 14  adults                26501 non-null  float64
 15  juniors               26501 non-null  float64
 16  children              26501 non-null  float64
 17  babies                26501 non-null  float64
 18  ARR                   26501 non-null  float64
dtypes: float64(11), object(8)
memory usage: 4.0+ MB
(26501, 162)

,plan_desc_0,plan_desc_1,plan_desc_2,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,RoomTypes_desc_4,RoomTypes_desc_5,RoomTypes_desc_6,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2018-11-07,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,4.0,8448.0,0.0,2.0,2.0,158.0,2.0,0.0,0.0,0.0
2018-11-06,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,4.0,8448.0,0.0,2.0,2.0,158.0,2.0,0.0,0.0,0.0
2018-10-25,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,15.0,2865.0,0.0,1.0,2.0,138.0,2.0,0.0,0.0,0.0
2018-12-31,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,4.0,2865.0,0.0,1.0,2.0,194.0,2.0,0.0,0.0,0.0
2018-10-02,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,4.0,2865.0,0.0,7.0,2.0,98.0,2.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,RoomTypes_desc_4,RoomTypes_desc_5,RoomTypes_desc_6,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000,...,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000,26501.000000
mean,0.796838,0.000113,0.203049,0.000604,0.056187,0.048262,0.175956,0.705219,0.000264,0.013509,...,18.307951,8400.551602,0.140221,5.980831,1.254519,22.410664,1.231916,0.000264,0.022339,0.002943
std,0.402360,0.010639,0.402276,0.024564,0.230286,0.214324,0.380790,0.455953,0.016251,0.115442,...,16.091838,3723.926458,0.347223,6.513076,0.501705,32.788685,0.434053,0.016251,0.186403,0.054173
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,651.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,4715.000000,0.000000,3.000000,1.000000,5.000000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,9.000000,9763.000000,0.000000,4.000000,1.000000,12.000000,1.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,40.000000,12346.000000,0.000000,7.000000,1.000000,27.000000,1.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13221.000000,1.000000,69.000000,4.000000,257.000000,4.000000,1.000000,2.000000,1.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

RoomTypes_desc_4    0.236557
ARR                 1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

RoomTypes_desc_1    0.226278
RoomTypes_desc_4    0.282534
ARR                 1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -5.372987949885354e+25
CV STD Accuracy:  6.355659624972503e+25

Train Accuracy:  0.19946923433532315
Test Accuracy:  -2.2859573447658456e+25

plan_desc_0 --> -157415849673952.66
plan_desc_1 --> -4162430522797.12
plan_desc_2 --> -157383165171235.28
RoomTypes_desc_0 --> 5914431490211.93
RoomTypes_desc_1 --> 55446557125223.95
RoomTypes_desc_2 --> 51603369281752.78
RoomTypes_desc_3 --> 91683706898209.00
RoomTypes_desc_4 --> 109780998077940.23
RoomTypes_desc_5 --> 3912693343915.04
RoomTypes_desc_6 --> 27795356608770.20
source_0 --> -558646582294582.31
source_1 --> -31543333792291.27
source_2 --> -96376915856061.09
source_3 --> -50942746132664.88
source_4 --> -570248338398118.62
source_5 --> -20288249177811.89
source_6 --> -7437220981675.09
source_7 --> -564030319775251.00
source_8 --> -24661816988790.54
source_9 --> -331480856232335.44
source_10 --> -347660326984066.94
source_11 --> -342324532874760.56
source_12 --> -90528989763754.58
sales_channel_0 --> 376806820932047.62
sales_channel_1 --> 267792777891125.31
sales_channel_2 --> 282014966823024.44
sales_channel_3 --> 213577076108358.03
sales_channel_4 --> 116423181910608.75
sales_channel_5 --> 31764757059001.42
sales_channel_6 --> 434168625340842.69
sales_channel_7 --> 24959926986170.30
club_code_0 --> 918822622048544.88
club_code_1 --> 35755470436231.44
club_code_2 --> 30965730030706.30
club_code_3 --> 363922568796418.00
club_code_4 --> 66879736217491.52
club_code_5 --> 855751444343546.25
StatisticSource_0 --> 271585321823409.84
package_code_0 --> -871250133425804.00
package_code_1 --> -435200723710881.75
package_code_2 --> -85104837743887.08
package_code_3 --> -232954820083363.97
package_code_4 --> -680209186116680.75
package_code_5 --> -95148305699580.75
package_code_6 --> -60180478970508.37
package_code_7 --> -104227779765672.25
package_code_8 --> -127645211546626.88
package_code_9 --> -85104837743888.83
package_code_10 --> -73704342237209.16
nationality_0 --> -3470182059640.30
nationality_1 --> -4479816703080.12
nationality_2 --> -22701338978533.30
nationality_3 --> -37756995999359.98
nationality_4 --> -27083961434042.02
nationality_5 --> -16257235994578.52
nationality_6 --> -30899135985902.53
nationality_7 --> -24060731987790.12
nationality_8 --> -51165492620723.47
nationality_9 --> -4006945481948.09
nationality_10 --> -33642691190172.88
nationality_11 --> -37549521496495.73
nationality_12 --> -31026433744204.12
nationality_13 --> -18975741798146.41
nationality_14 --> -50452238157355.23
nationality_15 --> -330874787162692.31
nationality_16 --> -14708560544092.56
nationality_17 --> -8497769128510.92
nationality_18 --> -4479816703080.22
nationality_19 --> -17669466979902.12
nationality_20 --> -26863791920498.30
nationality_21 --> -80419403601201.92
nationality_22 --> -21439802688375.23
nationality_23 --> -8012076087078.77
nationality_24 --> -10211504741810.82
nationality_25 --> -2003586154721.88
nationality_26 --> -57011026148482.53
nationality_27 --> -12662463515545.22
nationality_28 --> -8730462998839.38
nationality_29 --> -11675538014086.23
nationality_30 --> -70318878417440.03
nationality_31 --> -3470182059639.16
nationality_32 --> -70498882086231.64
nationality_33 --> -6334819739109.88
nationality_34 --> -13868936816737.55
nationality_35 --> -2003586154721.36
nationality_36 --> -32025924698805.12
nationality_37 --> -14154389257724.70
nationality_38 --> -19697259845748.97
nationality_39 --> -44638054107523.77
nationality_40 --> -6939185377827.09
nationality_41 --> -45873777347651.86
nationality_42 --> -21159507882643.06
nationality_43 --> -2833445250644.91
nationality_44 --> -3470182059639.59
nationality_45 --> -129657122261314.28
nationality_46 --> -65817519497886.64
nationality_47 --> -2833445250645.38
nationality_48 --> -2003586154720.20
nationality_49 --> -40735387293807.42
nationality_50 --> -9393927740290.97
nationality_51 --> -21898851317903.06
nationality_52 --> -23644495032834.84
nationality_53 --> -2833445250641.88
nationality_54 --> -22875774020785.69
nationality_55 --> -9604872228240.90
nationality_56 --> -10783939953917.39
nationality_57 --> -7757805765900.06
nationality_58 --> -2003586154718.44
nationality_59 --> -14012395345844.80
nationality_60 --> -29860493754744.16
nationality_61 --> -3470182059636.99
nationality_62 --> -7494893888990.27
nationality_63 --> -153139109019922.50
nationality_64 --> -6643889591394.10
nationality_65 --> -8497769128511.95
nationality_66 --> -41584773680965.31
nationality_67 --> -21532409414706.73
nationality_68 --> -18550670783127.27
nationality_69 --> -15884357716241.42
nationality_70 --> -9604872228243.36
nationality_71 --> -11675538014086.67
nationality_72 --> -16257235994582.25
nationality_73 --> -2833445250645.33
nationality_74 --> -36493464350818.02
nationality_75 --> -20970527302141.39
nationality_76 --> -2003586154721.55
nationality_77 --> -25579388666987.19
nationality_78 --> -19595835606263.69
nationality_79 --> -63421919238391.81
nationality_80 --> -4907300716352.56
nationality_81 --> -32574141062840.25
nationality_82 --> -2833445250645.08
nationality_83 --> -15630782784463.81
nationality_84 --> -16501095178273.84
nationality_85 --> -6009851111382.36
nationality_86 --> -23306036753318.44
nationality_87 --> -3470182059640.69
nationality_88 --> -8730462998841.35
nationality_89 --> -4907300716352.94
nationality_90 --> -25887487095224.69
nationality_91 --> -17211743970026.69
nationality_92 --> -4479816703075.72
nationality_93 --> -51831181213780.69
nationality_94 --> -5666248905984.07
nationality_95 --> -114713364175377.14
nationality_96 --> -2833445250644.60
nationality_97 --> -4479816703079.50
nationality_98 --> -10596579005548.87
nationality_99 --> -2003586154721.05
nationality_100 --> -25188831420541.00
nationality_101 --> -3772868553149.78
nationality_102 --> -2003586154719.52
market_segment_bi_id --> -44.25
MainCust --> 0.69
group_member --> 14.17
m_length_of_stay --> -14.84
bed_nights --> 196322725871664.12
m_lead_days --> -2.14
adults --> -169849469422169.75
juniors --> -6359024210009.98
children --> -72941667509619.62
babies --> 1.22
Model: ridge_regressor
CV Mean Accuracy:  0.18314271784946687
CV STD Accuracy:  0.019148848645139202

Train Accuracy:  0.20023149377103377
Test Accuracy:  0.19383173303980117

Model: lasso_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 89912.41022092104, tolerance: 51071.03369243947
  positive)

CV Mean Accuracy:  0.18316658616235806
CV STD Accuracy:  0.018947180527102363

Train Accuracy:  0.19991940833090638
Test Accuracy:  0.19472949744924994

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 60573.511213600636, tolerance: 48805.66733162213
  positive)

Model: elasticnet_regressor
CV Mean Accuracy:  0.16267403866342917
CV STD Accuracy:  0.013688937441594013

Train Accuracy:  0.17313681538396075
Test Accuracy:  0.17484178241130233

Model: supportvect_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

CV Mean Accuracy:  0.14271095178304055
CV STD Accuracy:  0.01870487393081875

Train Accuracy:  0.16449784334814654
Test Accuracy:  0.164490316049535

Model: decisiontree_regressor
CV Mean Accuracy:  0.2812343593327984
CV STD Accuracy:  0.030967653130195397

Train Accuracy:  0.7803987805723435
Test Accuracy:  0.2770169141820856

Model: randomforest_regressor
CV Mean Accuracy:  0.10650499691618223
CV STD Accuracy:  0.010154881732475939

Train Accuracy:  0.10844445739259422
Test Accuracy:  0.11569867367551347

Model: xgboost_regressor
CV Mean Accuracy:  0.2934282676378398
CV STD Accuracy:  0.02316952354928101

Train Accuracy:  0.3357040201681275
Test Accuracy:  0.2946655350871309

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -2.302325033940032e+35
CV STD Accuracy:  2.5137423437920305e+35

Train Accuracy:  0.5807453190033129
Test Accuracy:  -6.043386655153245e+35

                        train_accuracy  test_accuracy
linear_regressor                0.1995         0.0000
ridge_regressor                 0.2002         0.1938
lasso_regressor                 0.1999         0.1947
elasticnet_regressor            0.1731         0.1748
supportvect_regressor           0.1645         0.1645
decisiontree_regressor          0.7804         0.2770
randomforest_regressor          0.1084         0.1157
xgboost_regressor               0.3357         0.2947
mlp_regressor                   0.5807         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 956.0

reservations_df shape: (75320, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2019-12-02,half board,patio room,26.0,10844.0,t.a.,,,,,can,1.0,3.0,1.0,262.0,1.0,0.0,0.0,0.0,321.32
2019-12-02,half board,patio room,26.0,10844.0,t.a.,,,,,can,1.0,3.0,1.0,262.0,1.0,0.0,0.0,0.0,321.32
2019-12-02,half board,patio room,26.0,10844.0,t.a.,,,,,can,1.0,3.0,1.0,262.0,1.0,0.0,0.0,0.0,321.32
2019-12-02,half board,patio room,26.0,10844.0,t.a.,,,,,can,1.0,3.0,1.0,262.0,1.0,0.0,0.0,0.0,321.32
2019-12-02,half board,patio room,26.0,10844.0,t.a.,,,,,can,1.0,3.0,1.0,262.0,1.0,0.0,0.0,0.0,321.32

<class 'pandas.core.frame.DataFrame'>
Index: 75320 entries, 2019-12-02 to 2019-06-29
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   plan_desc             75320 non-null  object
 1   RoomTypes_desc        75320 non-null  object
 2   market_segment_bi_id  75320 non-null  float64
 3   MainCust              75320 non-null  float64
 4   source                75320 non-null  object
 5   sales_channel         75320 non-null  object
 6   club_code             75320 non-null  object
 7   StatisticSource       75320 non-null  object
 8   package_code          75320 non-null  object
 9   nationality           75320 non-null  object
 10  group_member          75320 non-null  float64
 11  m_length_of_stay      75320 non-null  float64
 12  bed_nights            75320 non-null  float64
 13  m_lead_days           75320 non-null  float64
 14  adults                75320 non-null  float64
 15  juniors               75320 non-null  float64
 16  children              75320 non-null  float64
 17  babies                75320 non-null  float64
 18  ARR                   75320 non-null  float64
dtypes: float64(11), object(8)
memory usage: 11.5+ MB
(75320, 150)

,plan_desc_0,plan_desc_1,plan_desc_2,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,source_0,source_1,source_2,source_3,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2019-12-02,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,26.0,10844.0,1.0,3.0,1.0,262.0,1.0,0.0,0.0,0.0
2019-12-02,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,26.0,10844.0,1.0,3.0,1.0,262.0,1.0,0.0,0.0,0.0
2019-12-02,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,26.0,10844.0,1.0,3.0,1.0,262.0,1.0,0.0,0.0,0.0
2019-12-02,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,26.0,10844.0,1.0,3.0,1.0,262.0,1.0,0.0,0.0,0.0
2019-12-02,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,26.0,10844.0,1.0,3.0,1.0,262.0,1.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,source_0,source_1,source_2,source_3,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000,...,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000,75320.000000
mean,0.068494,0.030364,0.901142,0.003240,0.000186,0.996575,0.012055,0.000531,0.016729,0.022637,...,26.908577,8844.038170,0.964140,2.526381,1.091277,109.318309,1.085157,0.000027,0.006094,0.000624
std,0.252594,0.171587,0.298474,0.056825,0.013632,0.058427,0.109133,0.023039,0.128254,0.148743,...,5.605735,3017.253652,0.185943,1.732482,0.323483,82.364308,0.298516,0.005153,0.095450,0.026520
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,186.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,26.000000,7671.000000,1.000000,2.000000,1.000000,38.000000,1.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,26.000000,8882.000000,1.000000,2.000000,1.000000,80.000000,1.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,26.000000,10835.000000,1.000000,3.000000,1.000000,179.000000,1.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,55.000000,12876.000000,1.000000,40.000000,4.000000,293.000000,4.000000,1.000000,3.000000,2.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

plan_desc_0             0.340217
plan_desc_2             0.245031
source_2                0.245514
source_4                0.273445
sales_channel_0         0.308792
sales_channel_1         0.235203
market_segment_bi_id    0.321578
group_member            0.357930
bed_nights              0.294072
adults                  0.275183
ARR                     1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

plan_desc_0             0.289539
source_4                0.200102
nationality_17          0.216250
market_segment_bi_id    0.294885
group_member            0.216021
bed_nights              0.226082
adults                  0.222962
ARR                     1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -5.254093138488805e+24
CV STD Accuracy:  8.446604017137199e+24

Train Accuracy:  0.37264052489911736
Test Accuracy:  -3.558798583638664e+25

plan_desc_0 --> -8631039818860.11
plan_desc_1 --> -5863070599474.44
plan_desc_2 --> -10198720949639.98
RoomTypes_desc_0 --> -64792873861151.30
RoomTypes_desc_1 --> -15543920814004.02
RoomTypes_desc_2 --> -66619548686690.16
source_0 --> 2803232145690.26
source_1 --> 591785680991.42
source_2 --> 3294365477285.68
source_3 --> 3820674164235.48
source_4 --> 5838274769987.33
source_5 --> -29875888963834.92
source_6 --> 1129808686507.40
sales_channel_0 --> -13371629443740.41
sales_channel_1 --> -9195197258961.05
sales_channel_2 --> -7714654969656.71
sales_channel_3 --> 27615003802342.34
sales_channel_4 --> -5268613164769.79
club_code_0 --> 34709166256127.21
club_code_1 --> 2085556002509.00
club_code_2 --> 4171028935271.73
club_code_3 --> 34396763086218.41
StatisticSource_0 --> 21135317676677.21
package_code_0 --> -122998328426158.08
package_code_1 --> -122998328426159.55
nationality_0 --> 949188021782.29
nationality_1 --> 941115931229.32
nationality_2 --> 1440367849697.50
nationality_3 --> 2313931749655.01
nationality_4 --> 2104758754051.99
nationality_5 --> 882540027895.80
nationality_6 --> 1745958989389.55
nationality_7 --> 349637764596.06
nationality_8 --> 2872908641391.82
nationality_9 --> 1456138551712.73
nationality_10 --> 276418428334.94
nationality_11 --> 302799206779.58
nationality_12 --> 3556579822494.65
nationality_13 --> 327058352483.12
nationality_14 --> 4211408537341.63
nationality_15 --> 2247533522966.05
nationality_16 --> 1204159875649.81
nationality_17 --> 9743666747080.31
nationality_18 --> 2671690106599.76
nationality_19 --> 2694187963475.97
nationality_20 --> 1191432922404.22
nationality_21 --> 1776167739254.01
nationality_22 --> 605526040409.91
nationality_23 --> 174089501881925.47
nationality_24 --> 1628803932385.48
nationality_25 --> 5322893562565.56
nationality_26 --> 838190364661.59
nationality_27 --> 26582038796328.95
nationality_28 --> 1091236082407.77
nationality_29 --> 916471847448.85
nationality_30 --> 2710935688386.47
nationality_31 --> 5624150403214.67
nationality_32 --> 1018954357075.02
nationality_33 --> 1011441016235.33
nationality_34 --> 7699878051746.20
nationality_35 --> 829035045896.66
nationality_36 --> 4564630881349.71
nationality_37 --> 247237799737.90
nationality_38 --> 524421826808.38
nationality_39 --> 349637764595.93
nationality_40 --> 1026412504052.68
nationality_41 --> 891144458613.50
nationality_42 --> 174825845945.13
nationality_43 --> 665597654057.58
nationality_44 --> 174825845945.21
nationality_45 --> 1216753048259.28
nationality_46 --> 709999784405.34
nationality_47 --> 5004341547714.90
nationality_48 --> 462508862225.97
nationality_49 --> 5014542914513.39
nationality_50 --> 1859747172126.85
nationality_51 --> 3873648861572.54
nationality_52 --> 123621361848.82
nationality_53 --> 1375464744380.77
nationality_54 --> 7153274977865.05
nationality_55 --> 14595670736532.91
nationality_56 --> 214115636783.21
nationality_57 --> 1380990653438.07
nationality_58 --> 524421826807.81
nationality_59 --> 3161966114803.94
nationality_60 --> 2585535511524.61
nationality_61 --> 1927909870905.83
nationality_62 --> 247237799738.05
nationality_63 --> 781647695505.75
nationality_64 --> 302799206779.77
nationality_65 --> 214115636783.22
nationality_66 --> 174825845944.72
nationality_67 --> 838190364662.26
nationality_68 --> 1336139381820.29
nationality_69 --> 3720669912314.58
nationality_70 --> 1595778639073.90
nationality_71 --> 214115636783.02
nationality_72 --> 1265867151699.05
nationality_73 --> 2330230263478.83
nationality_74 --> 276418428333.70
nationality_75 --> 3171448395871.59
nationality_76 --> 630243114681.84
nationality_77 --> 2988472716079.91
nationality_78 --> 302799206779.46
nationality_79 --> 1724053740614.88
nationality_80 --> 390901714033.92
nationality_81 --> 924759735959.01
nationality_82 --> 1235400905956.77
nationality_83 --> 1557170214404.32
nationality_84 --> 2129823927750.88
nationality_85 --> 1993714152054.57
nationality_86 --> 1018954357075.34
nationality_87 --> 8785456389651.62
nationality_88 --> 1943596392962.65
nationality_89 --> 819777238912.12
nationality_90 --> 5559645317141.04
nationality_91 --> 5450676362229.55
nationality_92 --> 1216753048260.15
nationality_93 --> 1507507734384.10
nationality_94 --> 302799206779.11
nationality_95 --> 247237799737.54
nationality_96 --> 1633466829164.44
nationality_97 --> 2496336218661.04
nationality_98 --> 2086667812526.59
nationality_99 --> 2343185892639.03
nationality_100 --> 1318924457838.66
nationality_101 --> 1566912284879.83
nationality_102 --> 538788631218.14
nationality_103 --> 1867897049426.25
nationality_104 --> 771820383897.32
nationality_105 --> 1197813387073.80
nationality_106 --> 2079386683153.50
nationality_107 --> 8416400117412.10
nationality_108 --> 214115636783.57
nationality_109 --> 214115636782.94
nationality_110 --> 5045011425376.01
nationality_111 --> 1552276055340.90
nationality_112 --> 2597191984089.56
nationality_113 --> 1041167952076.35
nationality_114 --> 1105123051561.45
market_segment_bi_id --> -5.19
MainCust --> 6.56
group_member --> -12.71
m_length_of_stay --> 0.00
bed_nights --> 144629527131582.62
m_lead_days --> 0.12
adults --> -133466738200131.08
juniors --> -2303894609169.34
children --> -42675600111718.68
babies --> 0.57
Model: ridge_regressor
CV Mean Accuracy:  0.36592391320261425
CV STD Accuracy:  0.0187206222785087

Train Accuracy:  0.3728741477624036
Test Accuracy:  0.3419657594359252

Model: lasso_regressor
CV Mean Accuracy:  0.3661162128590785
CV STD Accuracy:  0.018542545988012697

Train Accuracy:  0.37256408286693643
Test Accuracy:  0.3420324373632443

Model: elasticnet_regressor
CV Mean Accuracy:  0.32780817687253033
CV STD Accuracy:  0.013265524526685337

Train Accuracy:  0.3314126439003109
Test Accuracy:  0.3083310673413453

Model: supportvect_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

CV Mean Accuracy:  0.28126835983549936
CV STD Accuracy:  0.023232831362907838

Train Accuracy:  0.29116665399328834
Test Accuracy:  0.2488247909037511

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

Model: decisiontree_regressor
CV Mean Accuracy:  0.6683301392640102
CV STD Accuracy:  0.03364944866164718

Train Accuracy:  0.7953117314387429
Test Accuracy:  0.6822491822588206

Model: randomforest_regressor
CV Mean Accuracy:  0.25271223221561256
CV STD Accuracy:  0.022037302139038702

Train Accuracy:  0.2531677218882624
Test Accuracy:  0.21828374010659524

Model: xgboost_regressor
CV Mean Accuracy:  0.5094775230190589
CV STD Accuracy:  0.021750683644012506

Train Accuracy:  0.5364775143123108
Test Accuracy:  0.491561837853681

Base Score:  0.5
Model: mlp_regressor
CV Mean Accuracy:  -4.641389615877999e+35
CV STD Accuracy:  6.607952558416382e+35

Train Accuracy:  0.6353998223577011
Test Accuracy:  -2.2303738619038188e+36

                        train_accuracy  test_accuracy
linear_regressor                0.3726         0.0000
ridge_regressor                 0.3729         0.3420
lasso_regressor                 0.3726         0.3420
elasticnet_regressor            0.3314         0.3083
supportvect_regressor           0.2912         0.2488
decisiontree_regressor          0.7953         0.6822
randomforest_regressor          0.2532         0.2183
xgboost_regressor               0.5365         0.4916
mlp_regressor                   0.6354         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 957.0

reservations_df shape: (13071, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2019-12-02,breakfast board,artist colony room,40.0,12678.0,co,,,,,isr,0.0,2.0,1.0,113.0,1.0,0.0,0.0,0.0,365.60
2019-12-02,breakfast board,artist colony room,15.0,12637.0,slf,,silver,,,fra,0.0,1.0,2.0,43.0,2.0,0.0,0.0,0.0,485.22
2019-12-02,breakfast board,artist colony room,15.0,12637.0,slf,,silver,,,fra,0.0,1.0,2.0,43.0,2.0,0.0,0.0,0.0,485.22
2019-12-02,breakfast board,artist colony room,15.0,12637.0,slf,,silver,,,isr,0.0,1.0,2.0,43.0,2.0,0.0,0.0,0.0,485.22
2019-12-02,breakfast board,artist colony room,4.0,2865.0,ot,booking.com,,,,usa,0.0,2.0,2.0,35.0,2.0,0.0,0.0,0.0,535.13

<class 'pandas.core.frame.DataFrame'>
Index: 13071 entries, 2019-12-02 to 2019-06-19
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   plan_desc             13071 non-null  object
 1   RoomTypes_desc        13071 non-null  object
 2   market_segment_bi_id  13071 non-null  float64
 3   MainCust              13071 non-null  float64
 4   source                13071 non-null  object
 5   sales_channel         13071 non-null  object
 6   club_code             13071 non-null  object
 7   StatisticSource       13071 non-null  object
 8   package_code          13071 non-null  object
 9   nationality           13071 non-null  object
 10  group_member          13071 non-null  float64
 11  m_length_of_stay      13071 non-null  float64
 12  bed_nights            13071 non-null  float64
 13  m_lead_days           13071 non-null  float64
 14  adults                13071 non-null  float64
 15  juniors               13071 non-null  float64
 16  children              13071 non-null  float64
 17  babies                13071 non-null  float64
 18  ARR                   13071 non-null  float64
dtypes: float64(11), object(8)
memory usage: 2.0+ MB
(13071, 120)

,plan_desc_0,plan_desc_1,plan_desc_2,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,RoomTypes_desc_4,RoomTypes_desc_5,RoomTypes_desc_6,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2019-12-02,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40.0,12678.0,0.0,2.0,1.0,113.0,1.0,0.0,0.0,0.0
2019-12-02,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,12637.0,0.0,1.0,2.0,43.0,2.0,0.0,0.0,0.0
2019-12-02,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,12637.0,0.0,1.0,2.0,43.0,2.0,0.0,0.0,0.0
2019-12-02,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,12637.0,0.0,1.0,2.0,43.0,2.0,0.0,0.0,0.0
2019-12-02,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,2865.0,0.0,2.0,2.0,35.0,2.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,RoomTypes_desc_4,RoomTypes_desc_5,RoomTypes_desc_6,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000,...,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000,13071.000000
mean,0.556805,0.087752,0.355443,0.817229,0.002678,0.015148,0.021957,0.135414,0.005432,0.000612,...,19.097315,8954.489787,0.316732,2.320863,1.849820,48.481830,1.627113,0.001071,0.221636,0.048351
std,0.496782,0.282944,0.478666,0.386493,0.051679,0.122146,0.146549,0.342179,0.073504,0.024733,...,12.977345,4343.456012,0.465220,1.852113,0.777564,60.118135,0.579723,0.044589,0.625578,0.230006
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,388.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,13.000000,4715.000000,0.000000,1.000000,1.000000,6.000000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,15.000000,10343.000000,0.000000,2.000000,2.000000,22.000000,2.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,26.000000,12637.000000,1.000000,3.000000,2.000000,73.000000,2.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,48.000000,13110.000000,1.000000,25.000000,5.000000,279.000000,4.000000,2.000000,4.000000,2.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

plan_desc_1         0.229301
RoomTypes_desc_0    0.311426
RoomTypes_desc_4    0.204499
source_7            0.227916
bed_nights          0.381733
adults              0.250413
children            0.242817
ARR                 1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

plan_desc_1         0.252734
RoomTypes_desc_0    0.313353
RoomTypes_desc_4    0.219436
source_0            0.224661
source_7            0.227179
bed_nights          0.353079
adults              0.276104
children            0.232705
ARR                 1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -3.657687573894296e+26
CV STD Accuracy:  3.4091649315647946e+26

Train Accuracy:  0.388311421591119
Test Accuracy:  -9.214499657126644e+26

plan_desc_0 --> 537082012449085.12
plan_desc_1 --> 305897206041276.25
plan_desc_2 --> 517496450333937.94
RoomTypes_desc_0 --> -1046017038260989.38
RoomTypes_desc_1 --> -139865497696330.75
RoomTypes_desc_2 --> -330580229434390.38
RoomTypes_desc_3 --> -396623759092114.00
RoomTypes_desc_4 --> -926082052481509.75
RoomTypes_desc_5 --> -198932274188978.53
RoomTypes_desc_6 --> -66937710500229.02
RoomTypes_desc_7 --> -105789189462319.08
source_0 --> 504543023587366.25
source_1 --> 292234771470741.56
source_2 --> 31190580241905.99
source_3 --> 54007129728380.19
source_4 --> 41256522508728.42
source_5 --> 22056758578631.65
source_6 --> 595603205219676.88
source_7 --> 817233425492549.12
source_8 --> 856693879299403.25
source_9 --> -1060672185452941.88
source_10 --> 172862555643200.31
sales_channel_0 --> 356216337980529.12
sales_channel_1 --> 219000648882107.00
sales_channel_2 --> 163474444268839.59
sales_channel_3 --> 1780212570991394.25
sales_channel_4 --> 184103904125419.28
sales_channel_5 --> 7109405811418.66
sales_channel_6 --> 7109405811417.35
club_code_0 --> 3598259729548214.50
club_code_1 --> 256675903028870.81
club_code_2 --> 256675903028872.84
club_code_3 --> 393787419124932.31
club_code_4 --> 137251569670267.53
club_code_5 --> 3594693300852017.50
club_code_6 --> 3580774805722321.00
StatisticSource_0 --> 139640951242759.48
package_code_0 --> 2765586933284637.50
package_code_1 --> 541843799566612.88
package_code_2 --> 230535851245078.12
package_code_3 --> 196624213813710.00
package_code_4 --> 559241118159792.75
package_code_5 --> 1896769828068058.25
package_code_6 --> 650128802402855.75
package_code_7 --> 1633086540993756.00
package_code_8 --> 824132767725543.12
package_code_9 --> 302890655615326.88
package_code_10 --> 392887013663387.06
package_code_11 --> 269166645700483.38
package_code_12 --> 367568516104665.75
package_code_13 --> 120430290092719.64
nationality_0 --> -4948929402644.31
nationality_1 --> -44130591616880.69
nationality_2 --> -78105841404454.02
nationality_3 --> -12120032851741.31
nationality_4 --> -19784354909412.88
nationality_5 --> -4948929402648.12
nationality_6 --> -30061675682157.44
nationality_7 --> -65213944858537.09
nationality_8 --> -18507986952841.53
nationality_9 --> -14842243736390.16
nationality_10 --> -74710743198355.62
nationality_11 --> -25210541874154.56
nationality_12 --> -17136378604989.88
nationality_13 --> -9896722796093.12
nationality_14 --> -12120032851740.78
nationality_15 --> -53965442126876.53
nationality_16 --> -16407461574247.38
nationality_17 --> 960902940070669.00
nationality_18 --> -34578834441404.50
nationality_19 --> -9896722796097.12
nationality_20 --> -85281471585745.38
nationality_21 --> -48312861909766.81
nationality_22 --> -8571141305785.56
nationality_23 --> -11064449065237.75
nationality_24 --> -6998575330757.50
nationality_25 --> -1976146221735291.25
nationality_26 --> -25210541874155.06
nationality_27 --> -12120032851739.03
nationality_28 --> -273843505844288.12
nationality_29 --> -47810638528387.75
nationality_30 --> -12120032851740.88
nationality_31 --> -4948929402649.04
nationality_32 --> -6998575330758.56
nationality_33 --> -64107613964710.12
nationality_34 --> -8571141305790.38
nationality_35 --> -33507439846406.89
nationality_36 --> -6998575330762.75
nationality_37 --> -11064449065241.66
nationality_38 --> -4948929402647.25
nationality_39 --> -28394610983539.25
nationality_40 --> -11064449065235.09
nationality_41 --> -43578821889692.38
nationality_42 --> -9896722796096.12
nationality_43 --> -910743152183894.62
nationality_44 --> -12120032851740.22
nationality_45 --> -22116192298811.69
nationality_46 --> -4948929402643.75
nationality_47 --> -6998575330759.91
nationality_48 --> -9896722796093.44
nationality_49 --> -4948929402650.12
nationality_50 --> -11064449065233.38
nationality_51 --> -9896722796094.44
nationality_52 --> -6998575330762.48
nationality_53 --> -27962152285153.36
nationality_54 --> -8571141305786.81
nationality_55 --> -20982869825140.95
nationality_56 --> -232475702084144.88
nationality_57 --> -16407461574241.64
nationality_58 --> -22116192298806.75
market_segment_bi_id --> 17.00
MainCust --> 92.25
group_member --> 9.50
m_length_of_stay --> 22.81
bed_nights --> -3740188936254570.00
m_lead_days --> -9.22
adults --> 2788547320908281.00
juniors --> 214477142588716.38
children --> 3009117153124267.00
babies --> 11.75
Model: ridge_regressor
CV Mean Accuracy:  0.37954503058379263
CV STD Accuracy:  0.01576350769646036

Train Accuracy:  0.39126043530137844
Test Accuracy:  0.3925989721121663

Model: lasso_regressor
CV Mean Accuracy:  0.379855464344736
CV STD Accuracy:  0.015745515957379587

Train Accuracy:  0.39123605489920255
Test Accuracy:  0.39273473313710694

Model: elasticnet_regressor
CV Mean Accuracy:  0.3458148676102427
CV STD Accuracy:  0.014342672598289226

Train Accuracy:  0.3526499114651977
Test Accuracy:  0.35469478637683705

Model: supportvect_regressor
CV Mean Accuracy:  0.306271295819341
CV STD Accuracy:  0.025671168809825815

Train Accuracy:  0.3360291191920991
Test Accuracy:  0.33101099012301016

Model: decisiontree_regressor
CV Mean Accuracy:  0.49866733106839256
CV STD Accuracy:  0.023587980852955815

Train Accuracy:  0.8601430203549427
Test Accuracy:  0.5576304567660186

Model: randomforest_regressor
CV Mean Accuracy:  0.21198947707490853
CV STD Accuracy:  0.02166168716762065

Train Accuracy:  0.21365995843802252
Test Accuracy:  0.20797720153404764

Model: xgboost_regressor
CV Mean Accuracy:  0.5699255017726834
CV STD Accuracy:  0.017543616997029266

Train Accuracy:  0.6037010712415589
Test Accuracy:  0.5542076177532189

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -2.6878081685196054e+34
CV STD Accuracy:  2.0686439364482203e+34

Train Accuracy:  0.7293409770055065
Test Accuracy:  -9.677577790670284e+34

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

                        train_accuracy  test_accuracy
linear_regressor                0.3883         0.0000
ridge_regressor                 0.3913         0.3926
lasso_regressor                 0.3912         0.3927
elasticnet_regressor            0.3526         0.3547
supportvect_regressor           0.3360         0.3310
decisiontree_regressor          0.8601         0.5576
randomforest_regressor          0.2137         0.2080
xgboost_regressor               0.6037         0.5542
mlp_regressor                   0.7293         0.0000

Completed
Hotels:
[542. 543. 545. 546. 547. 548. 549. 550. 551. 552. 554. 555. 643. 956.
 957. 960.]

Selected: 960.0

reservations_df shape: (53711, 19)

,plan_desc,RoomTypes_desc,market_segment_bi_id,MainCust,source,sales_channel,club_code,StatisticSource,package_code,nationality,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies,ARR
res_date,,,,,,,,,,,,,,,,,,,
2019-12-02,breakfast board,superior room,21.0,10593.0,t.a.,,,,,fin,0.0,7.0,2.0,34.0,2.0,0.0,0.0,0.0,365.57
2019-12-02,breakfast board,superior room,4.0,4715.0,ot,expedia,,,,usa,0.0,3.0,4.0,28.0,2.0,0.0,2.0,0.0,1233.50
2019-12-02,breakfast board,standard room,15.0,9509.0,t.a.,,,,,isr,0.0,2.0,2.0,23.0,2.0,0.0,0.0,0.0,231.20
2019-12-02,breakfast board,standard room,15.0,9509.0,t.a.,,,,,isr,0.0,2.0,2.0,23.0,2.0,0.0,0.0,0.0,231.20
2019-12-02,breakfast board,standard room,4.0,2865.0,ot,booking.com,,,,deu,0.0,5.0,2.0,18.0,2.0,0.0,0.0,0.0,311.20

<class 'pandas.core.frame.DataFrame'>
Index: 53711 entries, 2019-12-02 to 2019-06-27
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   plan_desc             53711 non-null  object
 1   RoomTypes_desc        53711 non-null  object
 2   market_segment_bi_id  53711 non-null  float64
 3   MainCust              53711 non-null  float64
 4   source                53711 non-null  object
 5   sales_channel         53711 non-null  object
 6   club_code             53711 non-null  object
 7   StatisticSource       53711 non-null  object
 8   package_code          53711 non-null  object
 9   nationality           53711 non-null  object
 10  group_member          53711 non-null  float64
 11  m_length_of_stay      53711 non-null  float64
 12  bed_nights            53711 non-null  float64
 13  m_lead_days           53711 non-null  float64
 14  adults                53711 non-null  float64
 15  juniors               53711 non-null  float64
 16  children              53711 non-null  float64
 17  babies                53711 non-null  float64
 18  ARR                   53711 non-null  float64
dtypes: float64(11), object(8)
memory usage: 8.2+ MB
(53711, 122)

,plan_desc_0,plan_desc_1,plan_desc_2,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,RoomTypes_desc_4,RoomTypes_desc_5,RoomTypes_desc_6,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
res_date,,,,,,,,,,,,,,,,,,,,,
2019-12-02,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,10593.0,0.0,7.0,2.0,34.0,2.0,0.0,0.0,0.0
2019-12-02,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4715.0,0.0,3.0,4.0,28.0,2.0,0.0,2.0,0.0
2019-12-02,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,15.0,9509.0,0.0,2.0,2.0,23.0,2.0,0.0,0.0,0.0
2019-12-02,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,15.0,9509.0,0.0,2.0,2.0,23.0,2.0,0.0,0.0,0.0
2019-12-02,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,4.0,2865.0,0.0,5.0,2.0,18.0,2.0,0.0,0.0,0.0

,plan_desc_0,plan_desc_1,plan_desc_2,RoomTypes_desc_0,RoomTypes_desc_1,RoomTypes_desc_2,RoomTypes_desc_3,RoomTypes_desc_4,RoomTypes_desc_5,RoomTypes_desc_6,...,market_segment_bi_id,MainCust,group_member,m_length_of_stay,bed_nights,m_lead_days,adults,juniors,children,babies
count,53711.000000,53711.000000,53711.000000,53711.00000,53711.000000,53711.000000,53711.000000,53711.000000,53711.000000,53711.000000,...,53711.000000,53711.000000,53711.000000,53711.000000,53711.000000,53711.000000,53711.000000,53711.0,53711.000000,53711.000000
mean,0.291132,0.023608,0.685260,0.00229,0.000335,0.002532,0.004096,0.053453,0.882259,0.000335,...,20.322895,7584.925267,0.383683,3.184618,2.122712,45.577889,1.773249,0.0,0.349463,0.084135
std,0.454289,0.151825,0.464417,0.04780,0.018304,0.050256,0.063869,0.224937,0.322304,0.018304,...,11.867439,3600.275774,0.486287,1.445396,0.750128,54.983935,0.578350,0.0,0.743927,0.295778
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,1143.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,13.000000,2865.000000,0.000000,2.000000,2.000000,9.000000,2.000000,0.0,0.000000,0.000000
50%,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,15.000000,8627.000000,0.000000,3.000000,2.000000,17.000000,2.000000,0.0,0.000000,0.000000
75%,1.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,32.000000,10083.000000,1.000000,4.000000,2.000000,67.000000,2.000000,0.0,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,59.000000,13213.000000,1.000000,29.000000,4.000000,227.000000,4.000000,0.0,4.000000,2.000000

ARR min, mean, max = 0.01, 802.23, 2999.99
ARR uniques (87157):
 [1.00000e-02 2.00000e-02 3.00000e-02 ... 2.99937e+03 2.99943e+03
 2.99999e+03]

Relevant Features (Pearson):

RoomTypes_desc_4    0.299910
RoomTypes_desc_5    0.413951
sales_channel_0     0.222058
sales_channel_4     0.244617
bed_nights          0.447697
adults              0.225688
children            0.275973
ARR                 1.000000
Name: ARR, dtype: float64

Relevant Features (Spearman):

RoomTypes_desc_4    0.221977
RoomTypes_desc_5    0.304860
bed_nights          0.412951
adults              0.241990
children            0.296500
ARR                 1.000000
Name: ARR, dtype: float64

Model: linear_regressor
CV Mean Accuracy:  -5.96763346392806e+23
CV STD Accuracy:  6.20027991099724e+23

Train Accuracy:  0.4081245091887685
Test Accuracy:  0.39222485856082046

plan_desc_0 --> 154232213096776.62
plan_desc_1 --> 51545114661760.50
plan_desc_2 --> 157670708066061.62
RoomTypes_desc_0 --> 85030001469212.22
RoomTypes_desc_1 --> 32559741188014.80
RoomTypes_desc_2 --> 89399769808844.25
RoomTypes_desc_3 --> 113615492506344.50
RoomTypes_desc_4 --> 400133786326957.94
RoomTypes_desc_5 --> 573338881248092.62
RoomTypes_desc_6 --> 32559741188012.24
RoomTypes_desc_7 --> 387662474762026.00
RoomTypes_desc_8 --> 121801453363106.98
source_0 --> -216795554401420.16
source_1 --> -28812832818416.37
source_2 --> -7965396635516.01
source_3 --> -23132462141359.43
source_4 --> -158058728259022.88
source_5 --> -5310511627727.25
source_6 --> -184035102917222.06
source_7 --> -294903645974865.88
source_8 --> 1173042381706887.50
source_9 --> -37668647196451.94
sales_channel_0 --> 939498849504720.38
sales_channel_1 --> 455413350854567.31
sales_channel_2 --> 274151982457526.91
sales_channel_3 --> -912721945096465.62
sales_channel_4 --> 813915977919105.00
club_code_0 --> -870208068213581.00
club_code_1 --> -29357389140865.65
club_code_2 --> -40005142701758.71
club_code_3 --> -15692915039400.12
club_code_4 --> -87325635103325.83
club_code_5 --> -865812187714792.38
StatisticSource_0 --> 181589671932293.78
package_code_0 --> -228576964690201.62
package_code_1 --> -134016430507020.75
package_code_2 --> -8309401780583.50
package_code_3 --> -44196390892421.84
package_code_4 --> -156283202679822.38
package_code_5 --> -14391502122342.00
package_code_6 --> -53576003908323.62
package_code_7 --> -49345235278848.45
package_code_8 --> -56082447889911.62
package_code_9 --> -14391502122336.57
package_code_10 --> -16617411073102.12
package_code_11 --> -17948521121475.56
nationality_0 --> -13026041201903.12
nationality_1 --> -13026041201904.36
nationality_2 --> -13026041201903.66
nationality_3 --> -85350642498635.31
nationality_4 --> -53691741749474.50
nationality_5 --> -22560925019145.69
nationality_6 --> -18421261139424.78
nationality_7 --> -26050627183456.91
nationality_8 --> -24368357285383.61
nationality_9 --> -36838406102509.12
nationality_10 --> -13026041201905.00
nationality_11 --> -47849591273880.09
nationality_12 --> -72485406183785.09
nationality_13 --> -63119618592854.72
nationality_14 --> -26050627183456.41
nationality_15 --> -36838406102512.19
nationality_16 --> -9210887812771.94
nationality_17 --> -18421261139425.34
nationality_18 --> -18421261139422.03
nationality_19 --> -33206618133911.10
nationality_20 --> -106887259857507.31
nationality_21 --> -54475096818788.62
nationality_22 --> -20595404328290.40
nationality_23 --> -46955564847121.50
nationality_24 --> -24368357285385.28
nationality_25 --> -127071645120994.69
nationality_26 --> -146164037286855.94
nationality_27 --> -83851099764576.39
nationality_28 --> -22560925019145.75
nationality_29 --> -13026041201904.00
nationality_30 --> -13026041201908.38
nationality_31 --> -13026041201905.66
nationality_32 --> -13026041201903.12
nationality_33 --> -55247317179535.12
nationality_34 --> -20595404328292.89
nationality_35 --> -18421261139425.25
nationality_36 --> -15953428637222.03
nationality_37 --> -513415262657608.69
nationality_38 --> -60376210320178.93
nationality_39 --> -20595404328291.47
nationality_40 --> -26050627183460.27
nationality_41 --> -34459815329219.66
nationality_42 --> -15953428637216.44
nationality_43 --> -22560925019145.69
nationality_44 --> -46044148335501.58
nationality_45 --> -15953428637220.58
nationality_46 --> -39072302453302.53
nationality_47 --> -26050627183457.02
nationality_48 --> -26050627183456.06
nationality_49 --> -55247317179534.19
nationality_50 --> -102450594115699.47
nationality_51 --> -15953428637222.83
nationality_52 --> -27630605445949.25
nationality_53 --> -73643873591657.17
nationality_54 --> -13026041201902.95
nationality_55 --> -40142600907379.51
nationality_56 --> -310308308141338.44
nationality_57 --> -18421261139428.25
nationality_58 --> -30546214839337.33
nationality_59 --> -24368357285382.97
nationality_60 --> -22560925019146.38
nationality_61 --> -91100761902802.53
nationality_62 --> -27630605445950.98
nationality_63 --> -195216015461892.72
nationality_64 --> -27630605445945.50
nationality_65 --> -26050627183459.84
market_segment_bi_id --> -36.62
MainCust --> 18.59
group_member --> -0.84
m_length_of_stay --> -13.75
bed_nights --> -368118796198342.00
m_lead_days --> 38.81
adults --> 283820287317152.12
juniors --> -0.25
children --> 365075602047450.75
babies --> 14.06
Model: ridge_regressor
CV Mean Accuracy:  0.40422969166188133
CV STD Accuracy:  0.014266520801744424

Train Accuracy:  0.4083946892722842
Test Accuracy:  0.39232080405988556

Model: lasso_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2391143.757081032, tolerance: 507522.6603059885
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1935029.737944603, tolerance: 406837.98913011776
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1901206.6072368622, tolerance: 409298.15076228837
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1833778.8345236778, tolerance: 403820.55003354046
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1911566.7356734276, tolerance: 404340.71979148267
  positive)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1920727.441936016, tolerance: 405789.96310417895
  positive)

CV Mean Accuracy:  0.40427977869051
CV STD Accuracy:  0.014202923575932247

Train Accuracy:  0.4083283827628449
Test Accuracy:  0.3922480285864586

Model: elasticnet_regressor
CV Mean Accuracy:  0.37157775160298917
CV STD Accuracy:  0.012268455333042941

Train Accuracy:  0.37424272844508255
Test Accuracy:  0.3619745280068444

Model: supportvect_regressor
CV Mean Accuracy:  0.3752476684473961
CV STD Accuracy:  0.013882854615386258

Train Accuracy:  0.381941034184059
Test Accuracy:  0.3667616766563063

Model: decisiontree_regressor
CV Mean Accuracy:  0.5480833622364216
CV STD Accuracy:  0.013291830667195121

Train Accuracy:  0.8039122675693994
Test Accuracy:  0.5645183097756934

Model: randomforest_regressor
CV Mean Accuracy:  0.27793394524094006
CV STD Accuracy:  0.01603708478513314

Train Accuracy:  0.28013178665160265
Test Accuracy:  0.25972482728793267

Model: xgboost_regressor
CV Mean Accuracy:  0.5175848904945112
CV STD Accuracy:  0.01375337929860315

Train Accuracy:  0.5320710085931891
Test Accuracy:  0.5096036736604723

Base Score:  0.5
Model: mlp_regressor

/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/shahargino/Library/Python/3.7/lib/python/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

CV Mean Accuracy:  -4.484585981397455e+35
CV STD Accuracy:  8.67212410914618e+35

Train Accuracy:  0.6319101859739158
Test Accuracy:  0.5575076061551318

                        train_accuracy  test_accuracy
linear_regressor                0.4081         0.3922
ridge_regressor                 0.4084         0.3923
lasso_regressor                 0.4083         0.3922
elasticnet_regressor            0.3742         0.3620
supportvect_regressor           0.3819         0.3668
decisiontree_regressor          0.8039         0.5645
randomforest_regressor          0.2801         0.2597
xgboost_regressor               0.5321         0.5096
mlp_regressor                   0.6319         0.5575

Completed

In [2]:
for hotel_sel in hotels_sweep:
    
    print('Hotel %.2f' % hotel_sel)
    display(summary_all[hotel_sel])
    print('\n\n')

Hotel 542.00

                        train_accuracy  test_accuracy
linear_regressor                0.5060         0.0000
ridge_regressor                 0.5077         0.5161
lasso_regressor                 0.5076         0.5162
elasticnet_regressor            0.4752         0.4817
supportvect_regressor           0.4830         0.4893
decisiontree_regressor          0.9127         0.7209
randomforest_regressor          0.2815         0.3020
xgboost_regressor               0.6819         0.6804
mlp_regressor                   0.8248         0.0000

Hotel 543.00

                        train_accuracy  test_accuracy
linear_regressor                0.4703         0.0000
ridge_regressor                 0.4704         0.4775
lasso_regressor                 0.4703         0.4773
elasticnet_regressor            0.4394         0.4410
supportvect_regressor           0.4334         0.4426
decisiontree_regressor          0.8922         0.6964
randomforest_regressor          0.3030         0.3005
xgboost_regressor               0.6504         0.6520
mlp_regressor                   0.7802         0.0000

Hotel 545.00

                        train_accuracy  test_accuracy
linear_regressor                0.5056         0.0000
ridge_regressor                 0.5079         0.5159
lasso_regressor                 0.5078         0.5160
elasticnet_regressor            0.4745         0.4880
supportvect_regressor           0.4518         0.4590
decisiontree_regressor          0.9551         0.7960
randomforest_regressor          0.4216         0.4336
xgboost_regressor               0.7208         0.7206
mlp_regressor                   0.8559         0.0000

Hotel 546.00

                        train_accuracy  test_accuracy
linear_regressor                0.7284         0.0000
ridge_regressor                 0.7285         0.7297
lasso_regressor                 0.7285         0.7297
elasticnet_regressor            0.7084         0.7089
supportvect_regressor           0.7177         0.7185
decisiontree_regressor          0.9651         0.8838
randomforest_regressor          0.5813         0.5809
xgboost_regressor               0.8034         0.8024
mlp_regressor                   0.9032         0.0000

Hotel 547.00

                        train_accuracy  test_accuracy
linear_regressor                0.6313         0.0000
ridge_regressor                 0.6313         0.6254
lasso_regressor                 0.6313         0.6254
elasticnet_regressor            0.6046         0.5992
supportvect_regressor           0.6055         0.5976
decisiontree_regressor          0.9253         0.8121
randomforest_regressor          0.4464         0.4474
xgboost_regressor               0.7254         0.7185
mlp_regressor                   0.8475         0.0000

Hotel 548.00

                        train_accuracy  test_accuracy
linear_regressor                0.4002         0.0000
ridge_regressor                 0.4010         0.3985
lasso_regressor                 0.4009         0.3983
elasticnet_regressor            0.3800         0.3792
supportvect_regressor           0.3795         0.3773
decisiontree_regressor          0.8756         0.6958
randomforest_regressor          0.2462         0.2430
xgboost_regressor               0.5320         0.5241
mlp_regressor                   0.7215         0.0000

Hotel 549.00

                        train_accuracy  test_accuracy
linear_regressor                0.6182         0.0000
ridge_regressor                 0.6183         0.6194
lasso_regressor                 0.6183         0.6194
elasticnet_regressor            0.5894         0.5911
supportvect_regressor           0.6107         0.6104
decisiontree_regressor          0.9618         0.8746
randomforest_regressor          0.4481         0.4542
xgboost_regressor               0.7067         0.7037
mlp_regressor                   0.8550         0.0000

Hotel 550.00

                        train_accuracy  test_accuracy
linear_regressor                0.4381         0.0000
ridge_regressor                 0.4388         0.4271
lasso_regressor                 0.4388         0.4270
elasticnet_regressor            0.4137         0.4044
supportvect_regressor           0.4130         0.4008
decisiontree_regressor          0.9120         0.6031
randomforest_regressor          0.3055         0.3118
xgboost_regressor               0.5441         0.5216
mlp_regressor                   0.7250         0.0000

Hotel 551.00

                        train_accuracy  test_accuracy
linear_regressor                0.4696         0.0000
ridge_regressor                 0.4697         0.4755
lasso_regressor                 0.4697         0.4755
elasticnet_regressor            0.4455         0.4526
supportvect_regressor           0.4392         0.4458
decisiontree_regressor          0.8881         0.7215
randomforest_regressor          0.3346         0.3422
xgboost_regressor               0.5948         0.5981
mlp_regressor                   0.7673         0.0000

Hotel 552.00

                        train_accuracy  test_accuracy
linear_regressor                0.5898         0.0000
ridge_regressor                 0.5902         0.5852
lasso_regressor                 0.5900         0.5852
elasticnet_regressor            0.5700         0.5652
supportvect_regressor           0.5711         0.5658
decisiontree_regressor          0.9410         0.8389
randomforest_regressor          0.4763         0.4782
xgboost_regressor               0.7181         0.7138
mlp_regressor                   0.8442         0.0000

Hotel 554.00

                        train_accuracy  test_accuracy
linear_regressor                0.4397         0.0000
ridge_regressor                 0.4398         0.4359
lasso_regressor                 0.4398         0.4360
elasticnet_regressor            0.4149         0.4132
supportvect_regressor           0.4125         0.4102
decisiontree_regressor          0.8315         0.6201
randomforest_regressor          0.2857         0.2853
xgboost_regressor               0.5431         0.5401
mlp_regressor                   0.6644         0.0000

Hotel 555.00

                        train_accuracy  test_accuracy
linear_regressor                0.4216         0.0000
ridge_regressor                 0.4224         0.4155
lasso_regressor                 0.4222         0.4153
elasticnet_regressor            0.3921         0.3844
supportvect_regressor           0.3810         0.3709
decisiontree_regressor          0.8332         0.6152
randomforest_regressor          0.2587         0.2589
xgboost_regressor               0.5404         0.5338
mlp_regressor                   0.6455         0.5946

Hotel 643.00

                        train_accuracy  test_accuracy
linear_regressor                0.1995         0.0000
ridge_regressor                 0.2002         0.1938
lasso_regressor                 0.1999         0.1947
elasticnet_regressor            0.1731         0.1748
supportvect_regressor           0.1645         0.1645
decisiontree_regressor          0.7804         0.2770
randomforest_regressor          0.1084         0.1157
xgboost_regressor               0.3357         0.2947
mlp_regressor                   0.5807         0.0000

Hotel 956.00

                        train_accuracy  test_accuracy
linear_regressor                0.3726         0.0000
ridge_regressor                 0.3729         0.3420
lasso_regressor                 0.3726         0.3420
elasticnet_regressor            0.3314         0.3083
supportvect_regressor           0.2912         0.2488
decisiontree_regressor          0.7953         0.6822
randomforest_regressor          0.2532         0.2183
xgboost_regressor               0.5365         0.4916
mlp_regressor                   0.6354         0.0000

Hotel 957.00

                        train_accuracy  test_accuracy
linear_regressor                0.3883         0.0000
ridge_regressor                 0.3913         0.3926
lasso_regressor                 0.3912         0.3927
elasticnet_regressor            0.3526         0.3547
supportvect_regressor           0.3360         0.3310
decisiontree_regressor          0.8601         0.5576
randomforest_regressor          0.2137         0.2080
xgboost_regressor               0.6037         0.5542
mlp_regressor                   0.7293         0.0000

Hotel 960.00

                        train_accuracy  test_accuracy
linear_regressor                0.4081         0.3922
ridge_regressor                 0.4084         0.3923
lasso_regressor                 0.4083         0.3922
elasticnet_regressor            0.3742         0.3620
supportvect_regressor           0.3819         0.3668
decisiontree_regressor          0.8039         0.5645
randomforest_regressor          0.2801         0.2597
xgboost_regressor               0.5321         0.5096
mlp_regressor                   0.6319         0.5575

In [3]:
print('Completed')

Completed